package souther.compiler;

import org.junit.jupiter.api.Test;
import souther.test.Nightly;
import souther.test.OnItsOwnStack;

import java.util.ArrayList;
import java.util.List;

/**
 * A chain of newtypes, one to a module, each wrapping the one in the module before, compiles on a
 * small stack.
 *
 * <p>One newtype to a module puts a module boundary at every link, so a pass that works within one
 * module meets one link of the chain, and only a reader that opens the declarations of the modules
 * beneath can follow it. The code a module's classes are emitted by is such a reader. A newtype's
 * decoder is generated knowing only what the type it wraps is handed; generated by asking what the
 * end of the chain is handed instead, each module's classes would be emitted by reading through
 * every module beneath it, on the call stack, and run out of this one.
 *
 * <p>Asked once a night. A compile of a module chain costs more than its length beside the codecs,
 * so a chain long enough to run out of this stack takes seconds, and a shorter one fits on any stack
 * a thread can be given and still compile. What a newtype's decoder is handed is held on every
 * change by {@link CompileNewtypeTest}, which reads it off the generated signature; a walk to the
 * end of the chain coming back by another route is found by the morning.
 */
@Nightly
class AChainOfNewtypesAcrossModulesIsNotWalkedOnTheCallStackTest {

    private static final long STACK = 160L << 10;

    private static final int LINKS = 600;

    @Test
    void aChainOfModulesEachWrappingTheNewtypeBeforeOverAnObject() {
        List<String> modules = new ArrayList<>();
        modules.add("module m1 exposing ( T1 )\n\ndata T1 = { x: Int }\n");
        for (int i = 2; i <= LINKS; i++) {
            modules.add("module m" + i + " exposing ( T" + i + " )\n\nimport m" + (i - 1)
                    + " ( T" + (i - 1) + " )\n\ndata T" + i + " = T" + (i - 1) + "\n");
        }
        OnItsOwnStack.ask("a compile of the chain on a small stack", STACK,
                () -> Compiler.compileModules(modules));
    }
}
