package souther.compiler;

import org.junit.jupiter.api.Test;

import souther.compiler.diag.SourceNameResolver;
import souther.compiler.query.Adequacy;
import souther.compiler.query.Compilation;
import souther.compiler.report.GeneratedRows;

import java.util.List;
import java.util.Map;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * What the block offers is one row per row, and what is said above it is read off the block.
 *
 * <p>A boundary is probed once per obligation, and a probe fills the positions its edge does not name
 * from the bottom of each one's own domain — which is the value a minimum edge names. So two edges of
 * one behavior compose the same input, and offering a row per obligation offers a reader two rows they
 * cannot tell apart. What is offered is a row, and it is offered without a name: an edge cannot name
 * it, since which of the two is still owed is what an unrelated row changes, and a name that moved
 * with that would be a name for the state of the generation rather than for the row.
 *
 * <p>The sentence above the block describes the block. Counted from the obligations instead, it is a
 * number about work the reader cannot see, and the line telling them to answer each placeholder is
 * printed over blocks that hold none.
 */
class TheBlockAndItsHeaderComeFromOneListOfRowsTest {

    /** Two minimum edges, and a free position at each of them takes the value the other edge names. */
    private static final String POLICY = """
            module example.policy

            data Rate = Int
                invariant nonNegative = value >= 0

            data Cap = Int
                invariant nonNegative = value >= 0

            data Policy =
                { rate: Rate
                , cap: Cap
                }

            behavior fee : (days: Int, policy: Policy) -> Int

            let fee (days, policy) = {
                let accrued = days * policy.rate.value

                if accrued > policy.cap.value then policy.cap.value else accrued
            }

            example fee
                | "under the cap" : (5, Policy { rate = Rate(10), cap = Cap(500) }) -> 50
            """;

    /**
     * The same model with a rule the composing cannot reason through, so no candidate it puts
     * together satisfies it.
     *
     * <p>A product of two fields and not a sum. A sum was what this used to say, and a sum is a rule
     * the interval algebra now narrows both fields through — the composing finds
     * {@code rate = 0, cap = 10} and the block it produces has rows in it, which is the right answer
     * and the wrong fixture. What is wanted here is a rule outside what the algebra reasons in.
     *
     * <p>Here for the shape of the block it produces — explanations and no rows — and not for why the
     * search failed. Whether that failure may be read as a fact about the model is #602's question.
     */
    private static final String RELATED = POLICY.replace("""
                }

            behavior fee""", """
                }
                invariant together = rate.value * cap.value >= 10

            behavior fee""");

    private static String block(String source, String module) {
        Compilation compilation = Compilation.ofSource(source, "Main");
        compilation.measure(Adequacy.Asked.fullReport());
        compilation.answerEverything();
        Map<String, Adequacy.Filling> generated =
                compilation.db().ask(new Adequacy.Generated(module)).value();
        assertNotNull(generated, "the model under test compiles");
        return GeneratedRows.of(module, generated, Map.of(), true, SourceNameResolver.identity());
    }

    /** Where each row starts. A row the formatter wrapped is still one row, and one {@code |}. */
    private static List<String> rows(String block) {
        return block.lines().filter(line -> line.startsWith("//     | ")).toList();
    }

    /** The rows as printed, which is what a reader pastes — and not what is said under them. */
    private static List<String> written(String block) {
        return block.lines().dropWhile(line -> !line.startsWith("// example "))
                .takeWhile(line -> line.startsWith("// example ") || line.startsWith("//     "))
                .toList();
    }

    /** The number the sentence above the block claims, or -1 where it does not appear. */
    private static int claimed(String block) {
        Matcher said = Pattern.compile("^// generated by [^:]+: (\\d+) rows?").matcher(block);
        return said.find() ? Integer.parseInt(said.group(1)) : -1;
    }

    /** Which says the count as well: two edges meet at this input, and one {@code |} is written. */
    @Test
    void twoEdgesMeetingAtOneInputAreOneRow() {
        String block = block(POLICY, "example.policy");

        assertEquals(List.of(
                        "// example fee",
                        "//     | (0, Policy { rate = Rate(0), cap = Cap(0) }) -> <?>"),
                written(block));
    }

    @Test
    void theHeaderCountsTheRowsThatWerePrinted() {
        String block = block(POLICY, "example.policy");

        assertEquals(rows(block).size(), claimed(block),
                "the number above the block is the number of rows in it: " + block);
    }

    @Test
    void nothingAsksForAPlaceholderTheBlockDoesNotHold() {
        String block = block(RELATED, "example.policy");

        assertFalse(block.isBlank(), "the block says what it could not offer");
        // Which covers the line above the block as well as the rows: it is written with the
        // placeholder in it, so a block holding no `<?>` anywhere is one that does not ask for one.
        assertFalse(block.contains("<?>"),
                "no row was composed, so nothing asks for an answer: " + block);
        assertTrue(block.contains("`then`"),
                "and the gap it offers nothing for is named: " + block);
    }
}
