package souther.compiler;

import org.junit.jupiter.api.Test;

import souther.compiler.diag.SourceNameResolver;
import souther.compiler.query.Adequacy;
import souther.compiler.query.Bodies;
import souther.compiler.query.Compilation;
import souther.compiler.report.GeneratedRows;

import java.util.List;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * What the behavior declares about its answer, printed with the rows that ask for one.
 *
 * <p>A generated row leaves the answer as {@code <?>} and is a question: these inputs, and what does
 * the old system answer? Where the behavior carries an {@code ensures}, part of that is already
 * written down, and whoever fills the row was reading the declaration a second time to find it.
 *
 * <p>What is printed is the source, cut out of the file. Not the rule the checker made of it: that
 * is the same words resolved, typed and specialized per case, and printing it would hand back the
 * compiler's equivalent for the author's — a quote that moves the day a normalization changes,
 * without anybody having edited the model.
 */
class WhatIsWrittenInAnEnsuresIsQuotedOverTheRowsTest {

    private static final String TODO = """
            module example.todo

            data TodoId = Int
                invariant value >= 0

            data Todo = { id: TodoId }
            data NotFound

            behavior findTodo : (id: TodoId) -> Todo | NotFound
                constructs Todo
                ensures found = Todo -> value.id.value == id.value
                ensures asked = NotFound -> id.value > 0

            behavior echo : (id: TodoId) -> TodoId

            let findTodo (id) = if id.value > 0 then Todo { id = id } else NotFound
            let echo (id) = id
            """;

    private static String block(String source) {
        return GeneratedRows.of(compiled(source), null, null, true,
                SourceNameResolver.identity()).text();
    }

    private static Compilation compiled(String source) {
        Compilation compilation = Compilation.ofSource(source, "Main");
        compilation.measure(Adequacy.Asked.fullReport());
        compilation.answerEverything();
        return compilation;
    }

    /**
     * Every clause of the behavior, in the author's words and in the order they are written, over
     * the rows they are about — and nothing over the rows of a behavior that declares none.
     *
     * <p>{@code echo} carries {@code TodoId} and is offered one row rather than two. The line the
     * invariant draws is the declaration's and is owed once over every behavior carrying the type,
     * so it is resolved at the first reading that composes a row — {@code findTodo}'s {@code
     * TodoId(0)} — and what is left beside {@code echo} is the region of its own position
     * (issue #1076).
     */
    @Test
    void theClausesAreQuotedOverTheRowsOfTheBehaviorTheyAreWrittenOn() {
        assertEquals("""
                // generated by `souther examples --generate`: 4 rows to fill what nothing covers.
                // Replace each `<?>` with what the system actually answers, then uncomment.
                // `ensures` written for `findTodo`:
                //     ensures found = Todo -> value.id.value == id.value
                //     ensures asked = NotFound -> id.value > 0
                //
                // example findTodo
                //     | "id=0 <= x <= 0" : (TodoId(0)) -> <?>
                //     | "id=0 < x"       : (TodoId(1)) -> <?>
                //     | (TodoId(2))                    -> <?>
                //
                // example echo
                //     | (TodoId(1)) -> <?>
                """, block(TODO));
    }

    /**
     * A clause written over more than one line keeps the shape its author gave it.
     *
     * <p>Which is what cutting the source means. The arms stay where they were put relative to the
     * keyword — the block indents the whole clause as one and does not lay it out again.
     */
    @Test
    void aClauseWrittenOverSeveralLinesKeepsItsShape() {
        String block = block("""
                module example.todo

                data TodoId = Int
                    invariant value >= 0

                data Todo = { id: TodoId }
                data NotFound

                behavior findTodo : (id: TodoId) -> Todo | NotFound
                    constructs Todo
                    ensures both = Todo -> value.id.value == id.value
                          | NotFound -> id.value > 0

                let findTodo (id) = if id.value > 0 then Todo { id = id } else NotFound
                """);

        assertTrue(block.contains("""
                // `ensures` written for `findTodo`:
                //     ensures both = Todo -> value.id.value == id.value
                //           | NotFound -> id.value > 0
                """), block);
    }

    /**
     * The same where the file is indented with tabs.
     *
     * <p>What is taken off the lines under the first is a count of code units, which is what a column
     * is, and a tab is one of them. Measured in the columns a tab advances to instead, the cut would
     * start past the text on every line of a tab-indented clause.
     */
    @Test
    void aClauseIndentedWithTabsKeepsItsShape() {
        String block = block(("""
                module example.todo

                data TodoId = Int
                \tinvariant value >= 0

                data Todo = { id: TodoId }
                data NotFound

                behavior findTodo : (id: TodoId) -> Todo | NotFound
                \tconstructs Todo
                \tconstructs NotFound
                \tensures both = Todo -> value.id.value == id.value
                \t\t| NotFound -> id.value > 0

                let findTodo (id) = if id.value > 0 then Todo { id = id } else NotFound
                """));

        assertTrue(block.contains("""
                // `ensures` written for `findTodo`:
                //     ensures both = Todo -> value.id.value == id.value
                //     \t| NotFound -> id.value > 0
                """), block.replace("\t", "<TAB>"));
    }

    /**
     * A clause this compiler refused is quoted all the same, which is the whole of why the words are
     * read off the settled module rather than off the contracts.
     *
     * <p>{@link Bodies.Contracts} answers a different question — which clauses the checker could
     * read — and takes each behavior's reading on its own, so a behavior carrying a clause it refused
     * has no entry there. {@code souther examples} says what is wrong with the source and then
     * reports what it observed, so that behavior's rows are offered anyway. Taken from the contracts
     * the block would print nothing over them, which reads as a behavior that states nothing rather
     * than one whose statement was refused.
     */
    @Test
    void aClauseTheCheckerRefusedIsStillWhatTheAuthorWrote() {
        String source = """
                module example.todo

                data TodoId = Int
                    invariant value >= 0

                data Todo = { id: TodoId }
                data NotFound
                data Other

                data A
                data B
                data Kind = A | B

                behavior wrong : (n: TodoId, k: Kind) -> Todo | NotFound
                    constructs Todo
                    ensures nope = Other -> n.value > 0

                let wrong (n, k) = if n.value > 5 then Todo { id = n } else NotFound
                """;
        Compilation compilation = compiled(source);

        // The arm names a data that is no case of the answer, so the reading of the contract is
        // refused and the behavior is not among them.
        assertFalse(compilation.db().ask(new Bodies.Contracts("example.todo")).value()
                        .containsKey("wrong"),
                "the checker could not read this behavior's clause");

        String block = GeneratedRows.of(compilation, null, null, true,
                SourceNameResolver.identity()).text();
        assertTrue(block.contains("""
                // `ensures` written for `wrong`:
                //     ensures nope = Other -> n.value > 0
                """), block);
        assertTrue(block.contains("// example wrong"), block);
    }

    /**
     * A clause that calls a helper is quoted as the call, and not as what the call was expanded to.
     *
     * <p>Which is the property the rest of this rests on. What a reader is shown is a slice of the
     * file, so the passes that rewrite what a clause states — resolving its names, inlining the
     * helpers it calls — cannot move it: each of them carries the clause's own position over, and
     * the quote is taken from that.
     *
     * <p>The other reading is a live one and not a worry. The rule this model's clause becomes is an
     * expansion holding the helper's body, at the helper's own positions, so anything built from the
     * expression would print {@code id.value > 0} from line 6 where the author wrote
     * {@code positive(id)} on line 10.
     */
    @Test
    void aClauseCallingAHelperIsQuotedAsTheCallTheAuthorWrote() {
        String block = block("""
                module example.todo

                data TodoId = Int
                    invariant value >= 0

                data Todo = { id: TodoId }
                data NotFound

                let positive (id: TodoId) = id.value > 0

                behavior findTodo : (id: TodoId) -> Todo | NotFound
                    constructs Todo
                    ensures asked = NotFound -> positive(id)

                let findTodo (id) = if id.value > 0 then Todo { id = id } else NotFound
                """);

        assertTrue(block.contains("""
                // `ensures` written for `findTodo`:
                //     ensures asked = NotFound -> positive(id)
                """), block);
        assertFalse(block.contains("id.value > 0"),
                "the helper's body is not what the author wrote here: " + block);
    }

    /** Nothing is quoted where nothing is asked. The clause is what a reader fills a {@code <?>}
     *  against, and a behavior nothing is offering a row for has none to fill. */
    @Test
    void aBehaviorWithNoRowToFillIsNotQuoted() {
        // The composition and not what is offered: this filling is built here rather than searched
        // for, so there is no store to ask what its rows would settle.
        String block = GeneratedRows.of(souther.compiler.query.EveryRowOfIt.offered(
                        souther.compiler.query.Composition.composed(
                        souther.compiler.query.OfferingRequest.overTheModule("example.todo", true),
                        Map.of("findTodo", nothingOffered()), null)),
                Map.of("findTodo", List.of("ensures asked = NotFound -> id.value > 0")),
                SourceNameResolver.identity()).text();

        assertEquals("", block);
    }

    /** A behavior nothing was asked for and nothing composed for, which is what an empty offer is. */
    private static Adequacy.Filling nothingOffered() {
        souther.compiler.partition.Generator.Subject subject =
                new souther.compiler.partition.Generator.Subject("findTodo",
                        new souther.compiler.partition.BehaviorInputs(List.of(), List.of(),
                                souther.compiler.check.Symbols.none(DefaultStdlib.get()),
                                souther.compiler.query.ReadAs.THE_COMPILATION_DOES),
                        List.of(), souther.compiler.partition.HeldCounts.NONE);
        return new Adequacy.Filling(
                souther.compiler.partition.FillResult.nothingAskedOf(
                        new souther.compiler.partition.GenerationPlan(subject, List.of(),
                                List.of())),
                souther.compiler.partition.Generator.GenerationResult.NONE, List.of());
    }
}
