package souther.unicode;

import java.util.Arrays;
import java.util.TreeMap;
import java.util.TreeSet;
import org.jspecify.annotations.Nullable;

/**
 * Unicode 18.0.0 Normalization Form C: the one NFC this language runs, everywhere a
 * {@code String} is built or arrives — a boundary door (a decoder's string leaf, a name, a
 * literal) and every {@code String}-producing operation that cannot preserve NFC by construction
 * alone (spec §stdlib-string). Not the JVM's own {@code java.text.Normalizer}: this JDK's own
 * Unicode data is version 16.0, which does not have combining classes newer than that (Unicode
 * 18.0.0 added, among others, U+1E6E3 at combining class 230 — unassigned and so combining class 0
 * to a Normalizer that has never heard of it), so it cannot answer Unicode 18.0.0's NFC for text
 * using them.
 *
 * <p>The algorithm is the standard three steps (UAX #15): fully decompose canonically (recursively,
 * plus the Hangul syllable's algorithmic decomposition, which {@code UnicodeData.txt} does not
 * state because it is generated by formula rather than looked up), reorder combining marks by
 * canonical combining class, then compose canonically (again, plus Hangul's algorithmic
 * composition) wherever nothing blocks it.
 */
public final class Normalization {

    private Normalization() {}

    /** Unicode 18.0.0's Normalization Form C of {@code s}. Idempotent — {@code nfc(nfc(s)) ==
     *  nfc(s)} — because composing an already-canonical sequence recomposes nothing further.
     *
     *  <p>Of text that is a sequence of scalar values, which is the only text there is to normalize:
     *  whether text from outside is one is asked by {@code Strings.admitted} before this, and this
     *  asks nothing. Half a surrogate pair handed in comes back out where it was. */
    public static String nfc(String s) {
        String canonical = nfcWithin(s, Long.MAX_VALUE);
        if (canonical == null) {
            throw new IllegalStateException("no text is longer than Long.MAX_VALUE UTF-16 units");
        }
        return canonical;
    }

    /**
     * {@link #nfc}, or null where the answer is longer than {@code longest} UTF-16 units — which is
     * found out before that much is built, so a caller whose carrier has a bound on a text's length
     * can ask for the answer without asking for more than the bound.
     *
     * <p>The work is done a stretch at a time, cut before a code point nothing before it can reach:
     * one whose decomposition begins with a starter that is not the second of any composition.
     * Canonical ordering never moves a mark past a starter, and composition never joins a starter to
     * anything before a starter that cannot be a second, so the NFC of the whole is the NFC of each
     * stretch laid end to end. What a stretch is worked on in is as long as the stretch; the full
     * decomposition of the whole text, which is longer than the text and longer than the answer, is
     * never held at once.
     */
    public static @Nullable String nfcWithin(String s, long longest) {
        return nfcWithin(s, longest, STRETCH);
    }

    /** How many UTF-16 units a stretch runs to before it looks for the next place to cut. */
    private static final int STRETCH = 4096;

    /** {@link #nfcWithin(String, long)} with the stretch it cuts at given, so that the cut can be
     *  held against the text taken whole. */
    static @Nullable String nfcWithin(String s, long longest, int stretch) {
        StringBuilder out = new StringBuilder((int) Math.min(s.length(), longest));
        int from = 0;
        while (from < s.length()) {
            int to = stretchEnd(s, from, stretch);
            int[] decomposed = canonicalDecompose(s.substring(from, to).codePoints().toArray());
            canonicalOrder(decomposed);
            for (int cp : canonicalCompose(decomposed)) {
                if (out.length() + Character.charCount(cp) > longest) {
                    return null;
                }
                out.appendCodePoint(cp);
            }
            from = to;
        }
        return out.toString();
    }

    /** Where the stretch starting at {@code from} ends: the first place at least {@code stretch}
     *  units on that nothing before it can reach, or the end of the text. Never {@code from} itself,
     *  so every stretch holds at least one code point. */
    private static int stretchEnd(String s, int from, int stretch) {
        int at = from + Math.min(stretch, s.length() - from);
        if (at < s.length() && at > from
                && Character.isLowSurrogate(s.charAt(at)) && Character.isHighSurrogate(s.charAt(at - 1))) {
            at++;
        }
        while (at < s.length()) {
            int cp = s.codePointAt(at);
            if (at > from && nothingBeforeReaches(cp)) {
                return at;
            }
            at += Character.charCount(cp);
        }
        return s.length();
    }

    /** Whether no code point before {@code cp} can be reordered past it or composed with it: its
     *  decomposition begins with a starter, and that starter is not the second of a composition. */
    private static boolean nothingBeforeReaches(int cp) {
        int[] decomposed = decomposeOne(cp);
        int first = decomposed == null ? cp : decomposed[0];
        return combiningClass(first) == 0 && Arrays.binarySearch(SECONDS, first) < 0;
    }

    // ---- Hangul algorithmic decomposition/composition (UAX #15, the Hangul section) ----

    private static final int S_BASE = 0xAC00;
    private static final int L_BASE = 0x1100;
    private static final int V_BASE = 0x1161;
    private static final int T_BASE = 0x11A7;
    private static final int L_COUNT = 19;
    private static final int V_COUNT = 21;
    private static final int T_COUNT = 28;
    private static final int N_COUNT = V_COUNT * T_COUNT;
    private static final int S_COUNT = L_COUNT * N_COUNT;

    private static boolean isHangulSyllable(int cp) {
        return cp >= S_BASE && cp < S_BASE + S_COUNT;
    }

    /** A Hangul syllable's L, V and (if present) T jamo — the syllable's decomposition is
     *  algorithmic, not a lookup, so it is not in {@link NormalizationTables#DECOMP}. */
    private static int[] decomposeHangul(int s) {
        int sIndex = s - S_BASE;
        int l = L_BASE + sIndex / N_COUNT;
        int v = V_BASE + (sIndex % N_COUNT) / T_COUNT;
        int t = T_BASE + sIndex % T_COUNT;
        return t == T_BASE ? new int[] {l, v} : new int[] {l, v, t};
    }

    // ---- Canonical decomposition ----

    /** Every code point's canonical decomposition, applied recursively (a decomposition may map to
     *  code points that themselves decompose) until every element is either a Hangul syllable's
     *  own algorithmic split or has no canonical decomposition at all. */
    private static int[] canonicalDecompose(int[] codePoints) {
        StringBuilder out = null;
        int[] result = codePoints;
        for (int i = 0; i < codePoints.length; i++) {
            int[] d = decomposeOne(codePoints[i]);
            if (d != null) {
                if (out == null) {
                    out = new StringBuilder();
                    for (int j = 0; j < i; j++) {
                        out.appendCodePoint(codePoints[j]);
                    }
                }
                for (int cp : d) {
                    out.appendCodePoint(cp);
                }
            } else if (out != null) {
                out.appendCodePoint(codePoints[i]);
            }
        }
        if (out != null) {
            result = out.codePoints().toArray();
        }
        return result;
    }

    /** {@code cp}'s decomposition — Hangul's algorithmic split, or a table lookup expanded fully —
     *  or {@code null} if it has none, meaning it is already its own decomposition. */
    private static int @Nullable [] decomposeOne(int cp) {
        if (isHangulSyllable(cp)) {
            return decomposeHangul(cp);
        }
        int[] mapped = lookupDecomp(cp);
        if (mapped == null) {
            return null;
        }
        return canonicalDecompose(mapped);
    }

    private static int @Nullable [] lookupDecomp(int cp) {
        int index = Arrays.binarySearch(NormalizationTables.DECOMP.codePoints(), cp);
        return index >= 0 ? NormalizationTables.DECOMP.mapped()[index] : null;
    }

    // ---- Canonical ordering ----

    /** Unicode's canonical ordering algorithm (UAX #15's Canonical Ordering Behavior section): a stable
     *  insertion sort that only ever moves a combining mark earlier past marks of a strictly
     *  higher combining class, never past a starter (combining class 0) or past one of equal
     *  class — which is what keeps two canonically-equivalent orderings converging on one. */
    private static void canonicalOrder(int[] codePoints) {
        for (int i = 1; i < codePoints.length; i++) {
            int cpCcc = combiningClass(codePoints[i]);
            if (cpCcc == 0) {
                continue;
            }
            int j = i;
            while (j > 0 && combiningClass(codePoints[j - 1]) > cpCcc) {
                int t = codePoints[j - 1];
                codePoints[j - 1] = codePoints[j];
                codePoints[j] = t;
                j--;
            }
        }
    }

    /** {@code CCC_KEYS} holds only non-zero entries (spec of the generator that wrote it), and no
     *  Hangul jamo or syllable is one of them — every one of them is 0 in {@code UnicodeData.txt}
     *  — so a plain table lookup already answers 0 for them without a special case. */
    private static int combiningClass(int cp) {
        int index = Arrays.binarySearch(NormalizationTables.CCC_KEYS, cp);
        return index >= 0 ? NormalizationTables.CCC_VALUES[index] : 0;
    }

    // ---- Canonical composition ----

    /** Unicode's canonical composition algorithm (UAX #15's Canonical Composition Algorithm section): scan
     *  left to right, tracking the most recent starter and the combining class of the last
     *  character folded into the run since it. A character composes with the starter only if
     *  nothing between them blocks it — a combining class it is not strictly greater than, or
     *  another starter, resets the block for the run that follows. */
    private static int[] canonicalCompose(int[] codePoints) {
        int[] result = new int[codePoints.length];
        int length = 0;
        int starterAt = -1;
        int lastClass = -1;
        for (int cp : codePoints) {
            int cpCcc = combiningClass(cp);
            Integer composed = starterAt >= 0 && (lastClass < 0 || lastClass < cpCcc)
                    ? compose(result[starterAt], cp)
                    : null;
            if (composed != null) {
                result[starterAt] = composed;
                continue;
            }
            result[length++] = cp;
            if (cpCcc == 0) {
                starterAt = length - 1;
                lastClass = -1;
            } else {
                lastClass = cpCcc;
            }
        }
        return Arrays.copyOf(result, length);
    }

    /** The pair-composition table, inverted once from {@link NormalizationTables#DECOMP} rather
     *  than kept as a fourth generated table: every two-member canonical decomposition whose first
     *  member is a starter and whose result is not a {@link NormalizationTables#SCRIPT_SPECIFIC_EXCLUSIONS}
     *  entry, a singleton decomposition, or a non-starter decomposition — the last two read off
     *  {@code DECOMP}/{@code CCC} themselves, so decomposition and composition cannot disagree with
     *  each other. Keyed by {@code (long) starter << 32 | (cp & 0xFFFFFFFFL)}, sorted for binary
     *  search. */
    private static final long[] COMPOSE_KEYS;
    private static final int[] COMPOSE_VALUES;

    /** Every code point that composes with a starter before it, sorted: the second of each pair in
     *  {@link #COMPOSE_KEYS}, and Hangul's vowel and trailing consonant jamo, which compose by
     *  formula rather than by table. */
    private static final int[] SECONDS;

    static {
        int[] keys = NormalizationTables.DECOMP.codePoints();
        int[][] mapped = NormalizationTables.DECOMP.mapped();
        TreeMap<Long, Integer> pairs = new TreeMap<>();
        for (int i = 0; i < keys.length; i++) {
            int[] m = mapped[i];
            if (m.length == 2 && combiningClass(m[0]) == 0
                    && Arrays.binarySearch(NormalizationTables.SCRIPT_SPECIFIC_EXCLUSIONS, keys[i]) < 0) {
                pairs.put(pairKey(m[0], m[1]), keys[i]);
            }
        }
        COMPOSE_KEYS = pairs.keySet().stream().mapToLong(Long::longValue).toArray();
        COMPOSE_VALUES = pairs.values().stream().mapToInt(Integer::intValue).toArray();
        TreeSet<Integer> seconds = new TreeSet<>();
        for (long key : COMPOSE_KEYS) {
            seconds.add((int) key);
        }
        for (int cp = V_BASE; cp < V_BASE + V_COUNT; cp++) {
            seconds.add(cp);
        }
        for (int cp = T_BASE + 1; cp < T_BASE + T_COUNT; cp++) {
            seconds.add(cp);
        }
        SECONDS = seconds.stream().mapToInt(Integer::intValue).toArray();
    }

    private static long pairKey(int starter, int cp) {
        return ((long) starter << 32) | (cp & 0xFFFFFFFFL);
    }

    /** The primary composite of {@code starter} followed by {@code cp}, or {@code null} if the pair
     *  does not compose — Hangul's algorithmic L+V and LV+T composition, or {@link #COMPOSE_KEYS}. */
    private static @Nullable Integer compose(int starter, int cp) {
        Integer hangul = composeHangul(starter, cp);
        if (hangul != null) {
            return hangul;
        }
        int index = Arrays.binarySearch(COMPOSE_KEYS, pairKey(starter, cp));
        return index >= 0 ? COMPOSE_VALUES[index] : null;
    }

    private static @Nullable Integer composeHangul(int starter, int cp) {
        if (starter >= L_BASE && starter < L_BASE + L_COUNT && cp >= V_BASE && cp < V_BASE + V_COUNT) {
            int lIndex = starter - L_BASE;
            int vIndex = cp - V_BASE;
            return S_BASE + (lIndex * V_COUNT + vIndex) * T_COUNT;
        }
        if (isHangulSyllable(starter) && (starter - S_BASE) % T_COUNT == 0
                && cp > T_BASE && cp < T_BASE + T_COUNT) {
            return starter + (cp - T_BASE);
        }
        return null;
    }
}
