package souther.unicode;

import java.util.Arrays;
import java.util.TreeMap;
import java.util.stream.IntStream;
import org.jspecify.annotations.Nullable;

/**
 * Unicode 18.0.0 Normalization Form C: the one NFC this language runs, everywhere a
 * {@code String} is built or arrives — a boundary door (a decoder's string leaf, a name, a
 * literal) and every {@code String}-producing operation that cannot preserve NFC by construction
 * alone (spec §stdlib-string). Not the JVM's own {@code java.text.Normalizer}: this JDK's own
 * Unicode data is version 16.0, which does not have combining classes newer than that (Unicode
 * 18.0.0 added, among others, U+1E6E3 at combining class 230 — unassigned and so combining class 0
 * to a Normalizer that has never heard of it), so it cannot answer Unicode 18.0.0's NFC for text
 * using them.
 *
 * <p>The algorithm is the standard three steps (UAX #15): fully decompose canonically (recursively,
 * plus the Hangul syllable's algorithmic decomposition, which {@code UnicodeData.txt} does not
 * state because it is generated by formula rather than looked up), reorder combining marks by
 * canonical combining class, then compose canonically (again, plus Hangul's algorithmic
 * composition) wherever nothing blocks it.
 */
public final class Normalization {

    private Normalization() {}

    /** Unicode 18.0.0's Normalization Form C of {@code s}. Idempotent — {@code nfc(nfc(s)) ==
     *  nfc(s)} — because composing an already-canonical sequence recomposes nothing further.
     *
     *  <p>Of text that is a sequence of scalar values, which is the only text there is to normalize:
     *  whether text from outside is one is asked by {@code Strings.admitted} before this, and this
     *  asks nothing. Half a surrogate pair handed in comes back out where it was. */
    public static String nfc(String s) {
        String canonical = nfcWithin(s, Long.MAX_VALUE);
        if (canonical == null) {
            throw new IllegalStateException("no text is longer than Long.MAX_VALUE UTF-16 units");
        }
        return canonical;
    }

    /**
     * {@link #nfc}, or null where the answer is longer than {@code longest} UTF-16 units — which is
     * found out before that much is built, so a caller whose carrier has a bound on a text's length
     * can ask for the answer without asking for more than the bound.
     *
     * <p>Text made only of code points below {@link NormalizationTables#NFC_TRIVIAL_LIMIT} is its own
     * NFC, so it is answered with itself, as long as it is. Any other text is normalized, and its
     * length says nothing about the answer's, which may be shorter.
     */
    public static @Nullable String nfcWithin(String s, long longest) {
        if (belowTrivialLimit(s)) {
            return s.length() <= longest ? s : null;
        }
        return normalizeWithin(s, longest);
    }

    private static boolean belowTrivialLimit(String s) {
        for (int at = 0; at < s.length(); ) {
            int cp = s.codePointAt(at);
            if (cp >= NormalizationTables.NFC_TRIVIAL_LIMIT) {
                return false;
            }
            at += Character.charCount(cp);
        }
        return true;
    }

    /**
     * {@link #nfcWithin} worked out by the algorithm, whatever the text.
     *
     * <p>The three steps are taken one combining run at a time, as the text is read: each code point
     * is decomposed as it arrives, the marks after a starter are held until the next starter, and
     * then they are put in canonical order and composed into it. Canonical ordering never moves a
     * mark past a starter, and composition joins a starter only to the marks after it or, where
     * nothing is between them, to the starter after it, so a run settled when the next starter
     * arrives is settled as the whole text's algorithm would settle it. What is held at once is one
     * run's marks, never the decomposition of the whole text, which is longer than the text and
     * longer than the answer.
     */
    static @Nullable String normalizeWithin(String s, long longest) {
        Composing composing = new Composing(longest, (int) Math.min(s.length(), longest));
        for (int at = 0; at < s.length(); ) {
            int cp = s.codePointAt(at);
            at += Character.charCount(cp);
            int[] decomposed = decomposeOne(cp);
            if (decomposed == null) {
                if (!composing.take(cp)) {
                    return null;
                }
            } else {
                for (int part : decomposed) {
                    if (!composing.take(part)) {
                        return null;
                    }
                }
            }
        }
        return composing.finish();
    }

    /** The largest array this asks for; the JDK's portable bound on one. */
    private static final int LONGEST_ARRAY = Integer.MAX_VALUE - 8;

    /** How many marks a run may hold before they are put in order by counting rather than by
     *  insertion, which is quadratic in the run. */
    private static final int FEW_MARKS = 32;

    /**
     * One pass of canonical ordering and composition over code points already decomposed, holding
     * the starter of the run it is in and the marks after it, and writing what is settled.
     */
    private static final class Composing {

        private final long longest;
        private final StringBuilder out;
        private int starter = -1;
        private int[] marks = new int[8];
        private int markCount;

        Composing(long longest, int expected) {
            this.longest = longest;
            this.out = new StringBuilder(expected);
        }

        /** Takes the next decomposed code point; false where what is written has passed
         *  {@code longest}. */
        boolean take(int cp) {
            if (combiningClass(cp) != 0) {
                holdMark(cp);
                return true;
            }
            int kept = settle();
            if (starter >= 0 && kept == 0) {
                Integer composed = compose(starter, cp);
                if (composed != null) {
                    starter = composed;
                    return true;
                }
            }
            if (!write(kept)) {
                return false;
            }
            starter = cp;
            return true;
        }

        /** What is left, once the text has been read; null where it passes {@code longest}. */
        @Nullable String finish() {
            return write(settle()) ? out.toString() : null;
        }

        private void holdMark(int cp) {
            if (markCount == marks.length) {
                if (markCount == LONGEST_ARRAY) {
                    throw new IllegalStateException("a combining run of more marks than an array holds");
                }
                marks = Arrays.copyOf(marks, (int) Math.min(2L * marks.length, LONGEST_ARRAY));
            }
            marks[markCount++] = cp;
        }

        /** Puts the held marks in canonical order and composes into the starter each one nothing
         *  blocks; answers how many marks are left after the starter. */
        private int settle() {
            if (markCount > 1) {
                order();
            }
            if (starter < 0) {
                return markCount;
            }
            int kept = 0;
            int lastClass = -1;
            for (int i = 0; i < markCount; i++) {
                int mark = marks[i];
                int markClass = combiningClass(mark);
                Integer composed = lastClass < markClass ? compose(starter, mark) : null;
                if (composed != null) {
                    starter = composed;
                } else {
                    marks[kept++] = mark;
                    lastClass = markClass;
                }
            }
            markCount = kept;
            return kept;
        }

        /** Canonical ordering of the held marks: stable, by combining class. */
        private void order() {
            if (markCount <= FEW_MARKS) {
                for (int i = 1; i < markCount; i++) {
                    int mark = marks[i];
                    int markClass = combiningClass(mark);
                    int j = i;
                    while (j > 0 && combiningClass(marks[j - 1]) > markClass) {
                        marks[j] = marks[j - 1];
                        j--;
                    }
                    marks[j] = mark;
                }
                return;
            }
            int[] starts = new int[257];
            for (int i = 0; i < markCount; i++) {
                starts[combiningClass(marks[i]) + 1]++;
            }
            for (int c = 1; c < starts.length; c++) {
                starts[c] += starts[c - 1];
            }
            int[] ordered = new int[markCount];
            for (int i = 0; i < markCount; i++) {
                ordered[starts[combiningClass(marks[i])]++] = marks[i];
            }
            marks = ordered;
        }

        /** Writes the starter and the {@code kept} marks after it, and empties the run. */
        private boolean write(int kept) {
            if (starter >= 0 && !writeOne(starter)) {
                return false;
            }
            for (int i = 0; i < kept; i++) {
                if (!writeOne(marks[i])) {
                    return false;
                }
            }
            starter = -1;
            markCount = 0;
            return true;
        }

        private boolean writeOne(int cp) {
            if (out.length() + Character.charCount(cp) > longest) {
                return false;
            }
            out.appendCodePoint(cp);
            return true;
        }
    }

    // ---- Hangul algorithmic decomposition/composition (UAX #15, the Hangul section) ----

    private static final int S_BASE = 0xAC00;
    private static final int L_BASE = 0x1100;
    private static final int V_BASE = 0x1161;
    private static final int T_BASE = 0x11A7;
    private static final int L_COUNT = 19;
    private static final int V_COUNT = 21;
    private static final int T_COUNT = 28;
    private static final int N_COUNT = V_COUNT * T_COUNT;
    private static final int S_COUNT = L_COUNT * N_COUNT;

    private static boolean isHangulSyllable(int cp) {
        return cp >= S_BASE && cp < S_BASE + S_COUNT;
    }

    /** A Hangul syllable's L, V and (if present) T jamo — the syllable's decomposition is
     *  algorithmic, not a lookup, so it is not in {@link NormalizationTables#DECOMP}. */
    private static int[] decomposeHangul(int s) {
        int sIndex = s - S_BASE;
        int l = L_BASE + sIndex / N_COUNT;
        int v = V_BASE + (sIndex % N_COUNT) / T_COUNT;
        int t = T_BASE + sIndex % T_COUNT;
        return t == T_BASE ? new int[] {l, v} : new int[] {l, v, t};
    }

    // ---- Canonical decomposition ----

    /** {@code cp}'s decomposition — Hangul's algorithmic split, or a table lookup expanded fully,
     *  since a decomposition may map to code points that themselves decompose — or {@code null} if
     *  it has none, meaning it is already its own decomposition. */
    static int @Nullable [] decomposeOne(int cp) {
        if (isHangulSyllable(cp)) {
            return decomposeHangul(cp);
        }
        int[] mapped = lookupDecomp(cp);
        if (mapped == null) {
            return null;
        }
        IntStream.Builder full = IntStream.builder();
        for (int part : mapped) {
            int[] further = decomposeOne(part);
            if (further == null) {
                full.add(part);
            } else {
                for (int each : further) {
                    full.add(each);
                }
            }
        }
        return full.build().toArray();
    }

    private static int @Nullable [] lookupDecomp(int cp) {
        int index = Arrays.binarySearch(NormalizationTables.DECOMP.codePoints(), cp);
        return index >= 0 ? NormalizationTables.DECOMP.mapped()[index] : null;
    }

    /** Unicode's canonical combining class of {@code cp}: 0 for a starter, and for a mark the class
     *  canonical ordering sorts it by (UAX #15's Canonical Ordering Behavior section: stable, a mark
     *  moving earlier only past marks of a strictly higher class and never past a starter).
     *  {@code CCC_KEYS} holds only non-zero entries (spec of the generator that wrote it), and no
     *  Hangul jamo or syllable is one of them — every one of them is 0 in {@code UnicodeData.txt}
     *  — so a plain table lookup already answers 0 for them without a special case. */
    public static int combiningClass(int cp) {
        int index = Arrays.binarySearch(NormalizationTables.CCC_KEYS, cp);
        return index >= 0 ? NormalizationTables.CCC_VALUES[index] : 0;
    }

    // ---- Canonical composition ----
    // Unicode's canonical composition algorithm (UAX #15's Canonical Composition Algorithm section):
    // left to right, a code point composes with the most recent starter where nothing between them
    // blocks it — a mark of a class it is not strictly greater than, or anything at all for a
    // starter. {@link Composing#settle} and {@link Composing#take} are the two halves of it.

    /** The pair-composition table, inverted once from {@link NormalizationTables#DECOMP} rather
     *  than kept as a fourth generated table: every two-member canonical decomposition whose first
     *  member is a starter and whose result is not a {@link NormalizationTables#SCRIPT_SPECIFIC_EXCLUSIONS}
     *  entry, a singleton decomposition, or a non-starter decomposition — the last two read off
     *  {@code DECOMP}/{@code CCC} themselves, so decomposition and composition cannot disagree with
     *  each other. Keyed by {@code (long) starter << 32 | (cp & 0xFFFFFFFFL)}, sorted for binary
     *  search. */
    private static final long[] COMPOSE_KEYS;
    private static final int[] COMPOSE_VALUES;

    static {
        int[] keys = NormalizationTables.DECOMP.codePoints();
        int[][] mapped = NormalizationTables.DECOMP.mapped();
        TreeMap<Long, Integer> pairs = new TreeMap<>();
        for (int i = 0; i < keys.length; i++) {
            int[] m = mapped[i];
            if (m.length == 2 && combiningClass(m[0]) == 0
                    && Arrays.binarySearch(NormalizationTables.SCRIPT_SPECIFIC_EXCLUSIONS, keys[i]) < 0) {
                pairs.put(pairKey(m[0], m[1]), keys[i]);
            }
        }
        COMPOSE_KEYS = pairs.keySet().stream().mapToLong(Long::longValue).toArray();
        COMPOSE_VALUES = pairs.values().stream().mapToInt(Integer::intValue).toArray();
    }

    private static long pairKey(int starter, int cp) {
        return ((long) starter << 32) | (cp & 0xFFFFFFFFL);
    }

    /** The primary composite of {@code starter} followed by {@code cp}, or {@code null} if the pair
     *  does not compose — Hangul's algorithmic L+V and LV+T composition, or {@link #COMPOSE_KEYS}. */
    static @Nullable Integer compose(int starter, int cp) {
        Integer hangul = composeHangul(starter, cp);
        if (hangul != null) {
            return hangul;
        }
        int index = Arrays.binarySearch(COMPOSE_KEYS, pairKey(starter, cp));
        return index >= 0 ? COMPOSE_VALUES[index] : null;
    }

    private static @Nullable Integer composeHangul(int starter, int cp) {
        if (starter >= L_BASE && starter < L_BASE + L_COUNT && cp >= V_BASE && cp < V_BASE + V_COUNT) {
            int lIndex = starter - L_BASE;
            int vIndex = cp - V_BASE;
            return S_BASE + (lIndex * V_COUNT + vIndex) * T_COUNT;
        }
        if (isHangulSyllable(starter) && (starter - S_BASE) % T_COUNT == 0
                && cp > T_BASE && cp < T_BASE + T_COUNT) {
            return starter + (cp - T_BASE);
        }
        return null;
    }
}
