package souther.bench;

import souther.compiler.check.ChoicesRead;

import java.util.function.Supplier;

/**
 * A measurement's figure, beside what the runs it was taken over did with the choices they read.
 *
 * <p>Both out of one execution, which is the whole of why this exists. A figure for a path nothing
 * arrives at reports a number and answers nothing, and the two are indistinguishable in a report; so
 * what a measurement reaches has to be held to. Held by running the workload a second way, the
 * holding is about that second way — the source could part from the one that is timed, or the
 * questions asked of the store, or how many rounds precede the ones the figure comes from, and each
 * time the check would stay green about something adjacent. There is no second way here: a
 * measurement is run once, and a reader takes the figure and a reader takes the reading out of the
 * same result.
 *
 * <p><b>Which claims have to come through here.</b> A claim about what a run reached — that these
 * compiles settled a choice, that this shape held its alternatives apart — is about the run, and a
 * run made to check it is a different run. A claim about what a workload <em>is</em> — that a shape
 * still compiles, that it writes as many imports as the report says — is about the source, and is
 * answered by asking the source, which the shapes are generated by one producer so that it can be.
 * {@code EveryShapeThatIsTimedStillCompilesTest} is the second kind and needs the diagnostics a
 * timed run never collects; bringing it through here would mean timing a compile that gathers
 * diagnostics, which is changing what is measured to suit what checks it.
 *
 * @param figure what the measurement reports
 * @param read what the compiler did with the choices the measured runs read
 * @param <F> what the measurement reports it as
 */
record Taken<F>(F figure, ChoicesRead.Snapshot read) {

    /**
     * Runs {@code measurement} and keeps what it did beside what it came to.
     *
     * <p>For a measurement whose every run counts. Where a measurement warms itself first, the
     * reading has to start where the warm-up ends, and {@link #from} is how that is said.
     */
    static <F> Taken<F> of(Supplier<F> measurement) {
        ChoicesRead.Snapshot before = ChoicesRead.snapshot();
        return new Taken<>(measurement.get(), ChoicesRead.snapshot().since(before));
    }

    /**
     * The same, for a measurement that says when its warm-up ends.
     *
     * <p>The measurement is handed something to run at that moment and hands back its figure, so
     * what comes back here is the reading of the runs the figure was taken over and not of the runs
     * that warmed them. Taken around the whole of it, a reading would say a workload reached
     * something that only its warm-up did.
     */
    static <F> Taken<F> from(java.util.function.Function<Runnable, F> measurement) {
        ChoicesRead.Snapshot[] before = new ChoicesRead.Snapshot[1];
        F figure = measurement.apply(() -> {
            // Once, because a measurement that said twice would have this reading start at
            // whichever of the two came last, and a reader would be told about a run that had
            // already begun. Refused here rather than left to be noticed in a figure.
            if (before[0] != null) {
                throw new IllegalStateException(
                        "a measurement says once where its warm-up stops");
            }
            before[0] = ChoicesRead.snapshot();
        });
        ChoicesRead.Snapshot started = before[0];
        if (started == null) {
            throw new IllegalStateException("a measurement that warms itself says when it stops");
        }
        return new Taken<>(figure, ChoicesRead.snapshot().since(started));
    }
}
