version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      maven-plugins:
        patterns:
          - "org.apache.maven.plugins:*"
          - "org.sonatype.central:*"
      maven-test-dependencies:
        dependency-type: development
        patterns:
          - "*"
        exclude-patterns:
          - "org.apache.maven.plugins:*"
          - "org.sonatype.central:*"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
          - "*"
