package souther.compiler.check;

import souther.compiler.ast.Hir;
import souther.compiler.core.Kernel;
import souther.compiler.execute.WrittenValue;
import souther.compiler.numeric.Rel;
import souther.compiler.types.BindingId;
import souther.compiler.types.ValueName;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.function.Function;

/**
 * Folds a compile-time-constant expression to its value ({@code Long} / {@code BigDecimal} /
 * {@code String} / {@code Boolean}), or {@link Optional#empty()} when it is not constant-foldable.
 *
 * <p>Used to recognise a newtype constructor's constant argument ({@code 金額(500)}) and to produce
 * the value fed to compile-time function evaluation. The invariant itself is not folded here — CTFE
 * runs the real generated bytecode (ADR-0032) — so a construction with a constant argument is
 * verified without a second evaluator that could disagree, and may sit anywhere (not only a
 * behavior's tail) because CTFE either passes it or rejects it as a compile error.
 *
 * <p>The supported fragment covers constant arguments and simple sub-expressions: literals,
 * arithmetic, negation, comparison, logic, string concatenation, and {@code String.length} /
 * {@code contains}. Anything outside it folds to empty, which the caller treats as "not a
 * compile-time constant".
 *
 * <p>This is where "known at compile time" is decided, for every position that demands it — a
 * {@code String.matches} pattern is one, and both the check that compiles the regex and the codec
 * derivation that carries it to the boundary ask here rather than each recognising its own set of
 * expressions (issue #208).
 *
 * <p><b>It folds an expression under the bindings in force.</b> It resolves no module name: what a
 * module's value stands for is settled before a body is read here. A {@code let} is a different
 * question — it is part of the expression, and the binding it writes is an edge of that expression
 * rather than a name to look up. A binding denotes the expression it was given, which is the
 * environment's answer (ADR-0106, ADR-0111); folding that expression is this reader's, and it is
 * done once per binding however many times the binding is read.
 *
 * <p><b>A binding is read where the name is read, and not where it is written.</b> A body that
 * never reads a binder never folds what it was given, so {@code let x = <not foldable> in "a"}
 * comes to {@code "a"}. What is being asked is whether the answer is known at compile time, which
 * is not the same question as whether the whole expression could be run at compile time; nothing
 * here asks the second.
 *
 * <p>What an operator makes of the values under it is {@link ConstantAlgebra}, which the reading
 * over {@code Core} asks as well. One account of the arithmetic, two walks to reach it.
 */
public final class ConstEval {

    /** The symbols this folds against. Which operations fold is a fact about the library the
     *  expression was resolved against, so it is held here rather than asked at each call: an
     *  expression folded against one library and read against another would be answered from
     *  whichever the reader happened to reach. */
    private final Symbols symbols;

    /** What a name of a value of the module folds to, for a reader that resolves those; empty for
     *  every name otherwise. */
    private final Function<Hir.Var.Denoting, Optional<Object>> values;

    private ConstEval(Symbols symbols, Function<Hir.Var.Denoting, Optional<Object>> values) {
        this.symbols = symbols;
        this.values = values;
    }

    /**
     * What a fold answered, in the four a source can write it as — or null where it is a value no
     * source writes.
     *
     * <p>A fold answers with the object it happened to make, and which of the four it is is what
     * the language wrote. The one it makes that none of them is is the exact ratio a division
     * leaves, which is known at compile time and has no literal.
     */
    public static WrittenValue asWritten(Object folded) {
        return switch (folded) {
            case Long whole -> new WrittenValue.Whole(whole);
            case Boolean truth -> new WrittenValue.Truth(truth);
            case String text -> new WrittenValue.Text(text);
            case BigDecimal decimal -> new WrittenValue.Decimal(decimal);
            default -> null;
        };
    }

    /** Folding against the library {@code symbols} names. */
    public static ConstEval against(Symbols symbols) {
        return new ConstEval(symbols, _ -> Optional.empty());
    }

    /** The same, reading a name of a value of the module as what {@code values} says it folds to. */
    static ConstEval against(Symbols symbols, Function<Hir.Var.Denoting, Optional<Object>> values) {
        return new ConstEval(symbols, values);
    }

    /**
     * What each binding read so far came to.
     *
     * <p>On the reading and not in the environment. An environment answers what a name denotes; what
     * a reader makes of that value is the reader's, and a result kept beside the denotation would be
     * this fold's answer offered to every other reader of the same name (ADR-0111).
     *
     * <p>Kept per fold rather than per call, which is what stops a binding read twice from being
     * folded twice: a chain of bindings each reading the one before it twice is a count that doubles
     * per link otherwise, over a body that grows by a line.
     */
    private final Map<BindingId, Optional<Object>> folded = new HashMap<>();

    /**
     * The string {@code e} evaluates to at compile time, or empty when it does not evaluate to one:
     * what a position accepting a written string but not a computed one is asking about.
     */
    public Optional<String> evalString(BoundExpr e) {
        return eval(e).filter(String.class::isInstance).map(String.class::cast);
    }

    /** Folds {@code e} to its constant value under the bindings it is read beneath, or empty when
     *  it is not a compile-time constant. */
    Optional<Object> eval(BoundExpr e) {
        return eval(e.expr(), e.at());
    }

    /** The same, for an expression no binding stands over. A caller that has bindings in force and
     *  hands over a part of what it is reading takes {@link #eval(BoundExpr)}: dropping them reads
     *  every name they gave as a name standing for nothing. */
    Optional<Object> eval(Hir.Expr root) {
        return eval(root, BoundValues.NONE);
    }

    private Optional<Object> eval(Hir.Expr e, BoundValues env) {
        return switch (e) {
            case Hir.IntLit i -> Optional.of(i.value());
            case Hir.DecimalLit d -> Optional.of(d.value());
            case Hir.StringLit s -> Optional.of(s.value());
            case Hir.BoolLit b -> Optional.of(b.value());
            case Hir.Neg neg -> ConstantAlgebra.negate(eval(neg.operand(), env).orElse(null));
            case Hir.Binary bin -> binary(bin, env);
            case Hir.Apply call -> call(call, env);
            // A binding is an edge of the expression: the body is folded under it, and what it was
            // given is folded where the binder is read.
            case Hir.LetIn li -> eval(li.body(), env.binding(li.binder(), li.value()));
            case Hir.Var.Denoting v when v.denotes() instanceof ValueName.Local local ->
                    given(local.id(), env);
            case Hir.Var.Denoting v when v.denotes() instanceof ValueName.Helper -> values.apply(v);
            default -> Optional.empty();
        };
    }

    /** What the binding {@code id} was given comes to, folded once however often it is read. */
    private Optional<Object> given(BindingId id, BoundValues env) {
        BoundValues.Bound bound = env.read(id);
        if (bound == null) {
            return Optional.empty();
        }
        Optional<Object> already = folded.get(id);
        if (already != null) {
            return already;
        }
        // Put before the fold as "not a constant", so a binding that reaches itself answers rather
        // than going round. A module whose values do that is refused as the cycle it is, elsewhere.
        folded.put(id, Optional.empty());
        Optional<Object> answer = eval(bound.value(), bound.at());
        folded.put(id, answer);
        return answer;
    }

    private Optional<Object> binary(Hir.Binary bin, BoundValues env) {
        Optional<Object> l = eval(bin.left(), env);
        // Where the left operand settles it, the right one is not read at all — a right operand this
        // cannot fold would otherwise take a settled condition down with it.
        Optional<Object> settled = l.isEmpty() ? Optional.empty()
                : ConstantAlgebra.settledByTheLeft(bin.op(), l.get());
        if (settled.isPresent()) {
            return settled;
        }
        Optional<Object> r = eval(bin.right(), env);
        if (l.isEmpty() || r.isEmpty()) {
            return Optional.empty();
        }
        return ConstantAlgebra.binary(bin.op(), l.get(), r.get());
    }

    /**
     * Whether {@code rel} holds between two folded constants, or {@code null} where these two
     * cannot answer it.
     *
     * <p>The door the readers outside this one come in by. What it answers is
     * {@link ConstantAlgebra#stands}, which is where the rule is.
     */
    static Boolean stands(Rel rel, Object a, Object b) {
        return ConstantAlgebra.stands(rel, a, b);
    }

    /** Whether two folded values are the one value — {@link ConstantAlgebra#equal}. */
    public static boolean equal(Object a, Object b) {
        return ConstantAlgebra.equal(a, b);
    }

    private Optional<Object> call(Hir.Apply call, BoundValues env) {
        // Applying a name nothing declares is not a constant. There is no operation to fold it to,
        // and the name is reported where it is written.
        if (call.answered() == null) {
            return Optional.empty();
        }
        // What this call does, asked as the kernel the library declares the operation to be. The
        // alias an operation is published under is the library's own, and a fold selected by one
        // would be right for exactly as long as the two agreed.
        if (!(call.answered().denotes() instanceof ValueName.Stdlib.Operation operation)) {
            return Optional.empty();
        }
        Kernel kernel = symbols.kernelOf(operation);
        if (kernel == null) {
            return Optional.empty();
        }
        List<Object> args = new ArrayList<>();
        for (Hir.Expr arg : call.args()) {
            Object folds = eval(arg, env).orElse(null);
            if (folds == null) {
                return Optional.empty();
            }
            args.add(folds);
        }
        return ConstantAlgebra.computed(kernel, args);
    }
}
