package souther.compiler.check;

import souther.compiler.ast.Ast;

import java.math.BigDecimal;
import java.util.List;
import java.util.Optional;

/**
 * Folds a compile-time-constant expression to its value ({@code Long} / {@code BigDecimal} /
 * {@code String} / {@code Boolean}), or {@link Optional#empty()} when it is not constant-foldable.
 *
 * <p>Used to recognise a newtype constructor's constant argument ({@code 金額(500)}) and to produce
 * the value fed to compile-time function evaluation. The invariant itself is not folded here — CTFE
 * runs the real generated bytecode (ADR-0032) — so a construction with a constant argument is
 * verified without a second evaluator that could disagree, and may sit anywhere (not only a
 * behavior's tail) because CTFE either passes it or rejects it as a compile error.
 *
 * <p>The supported fragment covers constant arguments and simple sub-expressions: literals,
 * arithmetic, negation, comparison, logic, string concatenation, and {@code String.length} /
 * {@code contains}. Anything outside it folds to empty, which the caller treats as "not a
 * compile-time constant".
 *
 * <p>This is where "known at compile time" is decided, for every position that demands it — a
 * {@code String.matches} pattern is one, and both the check that compiles the regex and the codec
 * derivation that carries it to the boundary ask here rather than each recognising its own set of
 * expressions (issue #208).
 *
 * <p>It folds a tree; it does not resolve names. A name reaches here already standing for what it
 * denotes — a module's value is substituted by {@link HelperInliner} before an invariant or a body is
 * read — so a {@code let} whose body is constant folds, and a parameter or a field read does not.
 */
public final class ConstEval {
    private ConstEval() {}

    /**
     * The string {@code e} evaluates to at compile time, or empty when it does not evaluate to one:
     * what a position accepting a written string but not a computed one is asking about.
     */
    public static Optional<String> evalString(Ast.Expr e) {
        return eval(e).filter(String.class::isInstance).map(String.class::cast);
    }

    /** Folds {@code e} to its constant value, or empty when it is not a compile-time constant. */
    static Optional<Object> eval(Ast.Expr e) {
        return switch (e) {
            case Ast.IntLit i -> Optional.of(i.value());
            case Ast.DecimalLit d -> Optional.of(d.value());
            case Ast.StringLit s -> Optional.of(s.value());
            case Ast.BoolLit b -> Optional.of(b.value());
            case Ast.Neg neg -> negate(eval(neg.operand()).orElse(null));
            case Ast.Binary bin -> binary(bin);
            case Ast.Call call -> call(call);
            default -> Optional.empty();
        };
    }

    private static Optional<Object> negate(Object o) {
        if (o instanceof Long x) {
            return Optional.of(-x);
        }
        if (o instanceof BigDecimal d) {
            return Optional.of(d.negate());
        }
        return Optional.empty();
    }

    private static Optional<Object> binary(Ast.Binary bin) {
        Optional<Object> l = eval(bin.left());
        Optional<Object> r = eval(bin.right());
        if (l.isEmpty() || r.isEmpty()) {
            return Optional.empty();
        }
        Object a = l.get();
        Object b = r.get();
        return switch (bin.op()) {
            case AND -> a instanceof Boolean x && b instanceof Boolean y
                    ? Optional.of(x && y) : Optional.empty();
            case OR -> a instanceof Boolean x && b instanceof Boolean y
                    ? Optional.of(x || y) : Optional.empty();
            case EQ -> Optional.of(a.equals(b));
            case NE -> Optional.of(!a.equals(b));
            case LT, LE, GT, GE -> compare(bin.op(), a, b);
            case ADD, SUB, MUL -> arith(bin.op(), a, b);
            // `++` appends two strings or two lists (spec 18.1); the string case folds, and a list is
            // not a constant here to begin with.
            case CONCAT -> a instanceof String x && b instanceof String y
                    ? Optional.of(x + y) : Optional.empty();
            // `/` is left to the run-time check (it aborts on a zero divisor, and Decimal `/` rounds).
            case DIV -> Optional.empty();
        };
    }

    private static Optional<Object> compare(Ast.BinOp op, Object a, Object b) {
        Integer c = order(a, b);
        if (c == null) {
            return Optional.empty();
        }
        return Optional.of(switch (op) {
            case LT -> c < 0;
            case LE -> c <= 0;
            case GT -> c > 0;
            case GE -> c >= 0;
            default -> throw new IllegalStateException();
        });
    }

    /** Total order over two constants of the same ordered kind, or null if they are not comparable. */
    private static Integer order(Object a, Object b) {
        if (a instanceof Long x && b instanceof Long y) {
            return Long.compare(x, y);
        }
        if (a instanceof BigDecimal x && b instanceof BigDecimal y) {
            return x.compareTo(y);
        }
        if (a instanceof String x && b instanceof String y) {
            return x.compareTo(y);
        }
        return null;
    }

    private static Optional<Object> arith(Ast.BinOp op, Object a, Object b) {
        if (a instanceof Long x && b instanceof Long y) {
            return Optional.of(switch (op) {
                case ADD -> x + y;
                case SUB -> x - y;
                case MUL -> x * y;
                default -> throw new IllegalStateException();
            });
        }
        if (a instanceof BigDecimal x && b instanceof BigDecimal y) {
            return Optional.of(switch (op) {
                case ADD -> x.add(y);
                case SUB -> x.subtract(y);
                case MUL -> x.multiply(y);
                default -> throw new IllegalStateException();
            });
        }
        return Optional.empty();
    }

    private static Optional<Object> call(Ast.Call call) {
        List<Ast.Expr> args = call.args();
        switch (call.fn()) {
            case "length", "String.length" -> {
                if (args.size() == 1 && eval(args.get(0)).orElse(null) instanceof String s) {
                    return Optional.of((long) s.length());
                }
            }
            case "contains", "String.contains" -> {
                // contains(sub, s): the string being searched is the last argument (spec §pipe)
                if (args.size() == 2
                        && eval(args.get(0)).orElse(null) instanceof String sub
                        && eval(args.get(1)).orElse(null) instanceof String s) {
                    return Optional.of(s.contains(sub));
                }
            }
            default -> { }
        }
        return Optional.empty();
    }
}
