package souther.architecture;

import org.junit.jupiter.api.Test;

import java.lang.classfile.ClassModel;
import java.lang.classfile.constantpool.ClassEntry;
import java.lang.classfile.constantpool.PoolEntry;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;
import java.util.TreeSet;

import static org.junit.jupiter.api.Assertions.assertEquals;

/**
 * The run time does not depend on Raoh; only the generated bytecode and the apps that use it do
 * (spec §non-functional).
 *
 * <p>Raoh is on the run time's dependency list so that a project built with Souther resolves the
 * version the generated code was compiled against, and that is all it is there for. A class of the
 * run time that names one of its types has made the run time a reader of the boundary library, and
 * the decoders stop being the one place that says what a refusal is reported as. What the run time
 * answers is the fact a decoder reports, and how it is reported is the decoder's.
 *
 * <p>Read off the compiled classes rather than the source, so that a type reached through a
 * descriptor or a method reference is a row here whatever it is spelled as.
 */
class TheRuntimeDoesNotKnowRaohTest {

    private static final CompiledOutputs COMPILED = CompiledOutputs.ofWhatThisRepositoryPublishes();

    private static final String RAOH = "net/unit8/raoh/";

    @Test
    void noClassOfTheRuntimeNamesATypeOfRaoh() {
        assertEquals(List.of(), namingRaoh(),
                "the run time answers the fact and a decoder reports it: what a refusal is"
                        + " reported as is not the run time's to say");
    }

    private static List<String> namingRaoh() {
        Set<String> out = new TreeSet<>();
        for (ClassModel each : COMPILED.classesOf(COMPILED.module("souther-runtime"))) {
            for (PoolEntry entry : each.constantPool()) {
                if (entry instanceof ClassEntry named
                        && named.asInternalName().startsWith(RAOH)) {
                    out.add(each.thisClass().asInternalName() + " -> " + named.asInternalName());
                }
            }
        }
        return new ArrayList<>(out);
    }
}
