package souther.runtime;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;

import org.jspecify.annotations.Nullable;

/** List helpers the generated bytecode calls (spec 18.4). A {@code List} value is a
 *  {@link PersistentVector} (structural sharing), so the builders here run in O(1) amortized
 *  ({@link #append}) or O(n) ({@code sort}) rather than copying the whole list — which is what turns
 *  the fold-derived combinators from O(n²) into O(n). Inputs may be any {@code java.util.List} (a
 *  {@code []} literal is a JDK list, a decoded list comes from Raoh), so every builder normalizes
 *  through {@link PersistentVector#from}. */
public final class Lists {

    private Lists() {}

    /** The number of elements, as the Int the language carries. A JDK {@code size()} answers an
     *  {@code int}, and Souther's Int is a {@code long}, so the widening is here rather than at
     *  every site that emits the call. */
    public static long length(List<?> list) {
        return list.size();
    }

    /** Safe indexing: {@code Some(element)} when {@code index} is in range, else {@code None}. */
    public static <T> Option<T> get(List<T> list, long index) {
        if (index < 0 || index >= list.size()) {
            return Option.none();
        }
        return Option.some(list.get((int) index));
    }

    /** Immutable concatenation of two lists (spec 18.4, the {@code ++} operator). Grows a
     *  {@link PersistentVector}: {@code from(a)} shares {@code a} when it already is one (O(1)) and
     *  each element of {@code b} is appended in O(1) amortized. The one-element case is kept separate
     *  because {@code b} can still be a singleton here — a {@code ++} whose right side is a variable
     *  rather than a written {@code [x]}, which the backend routes to {@link #append} instead. */
    public static <T> List<T> concat(List<? extends T> a, List<? extends T> b) {
        PersistentVector<T> out = PersistentVector.from(a);
        if (b.size() == 1) {
            return out.append(b.get(0));   // the fold hot path: no iterator, one append
        }
        for (T x : b) {
            out = out.append(x);
        }
        return out;
    }

    /** {@code list} with one element appended — what {@code acc ++ [x]} means, without building the
     *  singleton in between. The backend emits this in place of {@link #concat} when the right-hand
     *  side of {@code ++} is a one-element list literal, which is every fold-derived combinator. */
    public static <T> List<T> append(List<? extends T> list, T element) {
        return PersistentVector.<T>from(list).append(element);
    }

    /**
     * An empty builder to walk with, as the accumulator a fold that only grows its list starts from.
     *
     * <p>The walk itself is emitted at the call site rather than made a loop here: a loop here would
     * be one method for every fold in the program, and the step it applies would be one call site
     * seeing every step there is — which past two or three of them stops being inlined and costs more
     * than the walk. Emitted where it stands, each walk applies the one step it was written with. What
     * is left in this class is the builder, which is not something generated code can name.
     */
    public static List<Object> builder() {
        return new PersistentVector.Builder<>();
    }

    /** The list a walk built, sealed: nothing may be added to the builder after this. */
    public static <T> List<T> sealed(List<T> acc) {
        return ((PersistentVector.Builder<T>) acc).build();
    }

    /**
     * Walks {@code xs} from index {@code from} with a builder as the accumulator and seals it into a
     * list — the same walk as {@link #builder}'s, for the two shapes the backend does not emit in
     * place: one that starts past the head, and one whose step is {@link Fn#NEVER}.
     *
     * <p>The step is the fold's own step, applied per element, except that its {@code acc ++ …} has
     * become {@link #grow}/{@link #growAll} and so adds to the builder and answers with it. The
     * compiler only rewrites a fold whose step touches the accumulator nowhere else, so the builder
     * is what comes back from every step and the cast below cannot fail. That is also what makes the
     * mutation unobservable: no version of the list before the last one is ever read.
     */
    @SuppressWarnings("unchecked")
    public static <T> List<T> build(Fn step, List<? extends T> xs, long from) {
        PersistentVector.Builder<T> builder = new PersistentVector.Builder<>();
        Object acc = builder;
        int n = xs.size();
        for (long i = from; i >= 0 && i < n; i++) {
            acc = step.apply(new Object[] {acc, xs.get((int) i)});
        }
        return ((PersistentVector.Builder<T>) acc).build();
    }

    /** {@code acc ++ [element]} inside a {@link #build}: adds to the builder the walk carries and
     *  answers with it, so the step reads as the fold it was written as. */
    public static <T> List<T> grow(List<T> acc, T element) {
        ((PersistentVector.Builder<T>) acc).add(element);
        return acc;
    }

    /** {@code acc ++ elements} inside a {@link #build}, for a step that adds a list rather than one
     *  element ({@code List.concatMap}, a fold joining what each element gives). */
    public static <T> List<T> growAll(List<T> acc, List<? extends T> elements) {
        PersistentVector.Builder<T> builder = (PersistentVector.Builder<T>) acc;
        for (int i = 0, n = elements.size(); i < n; i++) {
            builder.add(elements.get(i));
        }
        return acc;
    }

    /** The list in reverse order (Elm {@code List.reverse}). A native primitive rather than a fold:
     *  a left fold can only prepend to build a reversed list, and prepending to an array-backed
     *  vector is O(n) per step (O(n²) overall), so reversing walks the input from the end in O(n). */
    public static <T> List<T> reverse(List<? extends T> xs) {
        Object[] a = xs.toArray();
        PersistentVector<T> out = PersistentVector.empty();
        for (int i = a.length - 1; i >= 0; i--) {
            @SuppressWarnings("unchecked")
            T e = (T) a[i];
            out = out.append(e);
        }
        return out;
    }

    /** The consecutive integers from {@code from} to {@code to}, both ends included (Elm
     *  {@code List.range}); {@code from} above {@code to} gives the empty list. A primitive rather
     *  than a fold, because a fold needs a list to walk and this is what produces one.
     *
     *  <p>A span longer than a list can hold aborts up front rather than filling memory until it
     *  dies — an out-of-range bound is a model bug, not a business result, so it gets the treatment
     *  {@link IntMath} gives an overflow. The width is computed before the walk because
     *  {@code to - from} itself can overflow. */
    public static List<Long> range(long from, long to) {
        if (from > to) {
            return PersistentVector.empty();
        }
        long width = to - from + 1;
        if (width <= 0 || width > Integer.MAX_VALUE) {
            throw new ConstraintViolation("List.range is out of range: " + from + " to " + to);
        }
        PersistentVector<Long> out = PersistentVector.empty();
        for (long i = from; ; i++) {
            out = out.append(i);
            if (i == to) {
                return out;
            }
        }
    }

    /** The sum of a list of {@code Int} (Elm {@code List.sum}); the empty list is 0. Adds through
     *  the kernel the {@code +} operator uses, so a total past the range of an {@code Int} aborts
     *  here rather than wrapping. */
    public static long sumInt(List<?> xs) {
        long acc = 0;
        for (Object x : xs) {
            acc = IntMath.addExact(acc, (Long) x);
        }
        return acc;
    }

    /** The product of a list of {@code Int} (Elm {@code List.product}); the empty list is 1. */
    public static long productInt(List<?> xs) {
        long acc = 1;
        for (Object x : xs) {
            acc = IntMath.multiplyExact(acc, (Long) x);
        }
        return acc;
    }

    /** The sum of a list of {@code Decimal}; the empty list is 0. {@code BigDecimal.add} keeps the
     *  larger scale of its two operands, so the elements' own scales carry through the walk. */
    public static BigDecimal sumDecimal(List<?> xs) {
        BigDecimal acc = BigDecimal.ZERO;
        for (Object x : xs) {
            acc = acc.add((BigDecimal) x);
        }
        return acc;
    }

    /** The product of a list of {@code Decimal}; the empty list is 1. */
    public static BigDecimal productDecimal(List<?> xs) {
        BigDecimal acc = BigDecimal.ONE;
        for (Object x : xs) {
            acc = acc.multiply((BigDecimal) x);
        }
        return acc;
    }

    /** Sorts by the elements' natural order (Elm {@code List.sort}). The element type is a
     *  {@link Comparable} — {@code String} and the {@code Int}/{@code Decimal} carriers all are —
     *  and the input is left untouched. */
    @SuppressWarnings({"unchecked", "rawtypes"})
    public static <T> List<T> sort(List<? extends T> xs) {
        List<T> out = new ArrayList<>(xs);
        out.sort((a, b) -> ((Comparable) a).compareTo(b));
        return PersistentVector.from(out);
    }

    /** As {@link #sort(List)}, ordering by {@code by} rather than by the element's natural order.
     *  An enumeration's order belongs to the sum, not to the case value — the same case may be
     *  listed by two sums in different positions — so it arrives as a comparator. */
    public static <T> List<T> sort(Comparator<Object> by, List<? extends T> xs) {
        List<T> out = new ArrayList<>(xs);
        out.sort((a, b) -> by.compare(a, b));
        return PersistentVector.from(out);
    }

    /** The greatest element by natural order, {@code None} for an empty list (Elm {@code List.maximum}).
     *  The element is a {@link Comparable}, as {@code sort} requires. */
    public static <T> Option<T> max(List<? extends T> xs) {
        return extreme(xs, null, true);
    }

    /** The least element by natural order, {@code None} for an empty list (Elm {@code List.minimum}). */
    public static <T> Option<T> min(List<? extends T> xs) {
        return extreme(xs, null, false);
    }

    /** As {@link #max(List)}, ordering by {@code by} rather than by the element's natural order. */
    public static <T> Option<T> max(Comparator<Object> by, List<? extends T> xs) {
        return extreme(xs, by, true);
    }

    /** As {@link #min(List)}, ordering by {@code by}. */
    public static <T> Option<T> min(Comparator<Object> by, List<? extends T> xs) {
        return extreme(xs, by, false);
    }

    /** The first element satisfying {@code p}, or {@code None} if none does (Elm {@code List.Extra
     *  find}). {@code p} is a first-class function value; it is applied to each element in turn. */
    public static <T> Option<T> find(Fn p, List<? extends T> xs) {
        for (T x : xs) {
            if ((Boolean) p.apply(new Object[] {x})) {
                return Option.some(x);
            }
        }
        return Option.none();
    }

    /** Sorts by {@code key(element)}'s natural order, the input untouched (Elm {@code List.sortBy}).
     *  {@code key} maps each element to an ordered value. Each key is computed once (decorate, sort,
     *  undecorate), so a costly key runs {@code O(n)} times, not once per comparison; the sort is stable. */
    public static <T> List<T> sortBy(Fn key, List<? extends T> xs) {
        return sortBy(null, key, xs);
    }

    /** As {@link #sortBy(Fn, List)}, ordering the keys by {@code by} rather than naturally. */
    @SuppressWarnings({"unchecked", "rawtypes"})
    public static <T> List<T> sortBy(@Nullable Comparator<Object> by, Fn key, List<? extends T> xs) {
        List<Object[]> decorated = new ArrayList<>(xs.size());
        for (T x : xs) {
            decorated.add(new Object[] {x, key.apply(new Object[] {x})});
        }
        decorated.sort(by == null
                ? (a, b) -> ((Comparable) a[1]).compareTo(b[1])
                : (a, b) -> by.compare(a[1], b[1]));
        List<T> out = new ArrayList<>(decorated.size());
        for (Object[] pair : decorated) {
            out.add((T) pair[0]);
        }
        return PersistentVector.from(out);
    }

    @SuppressWarnings({"unchecked", "rawtypes"})
    private static <T> Option<T> extreme(
            List<? extends T> xs, @Nullable Comparator<Object> by, boolean greatest) {
        if (xs.isEmpty()) {
            return Option.none();
        }
        T best = xs.get(0);
        for (T x : xs) {
            int cmp = by == null ? ((Comparable) x).compareTo(best) : by.compare(x, best);
            if (greatest ? cmp > 0 : cmp < 0) {
                best = x;
            }
        }
        return Option.some(best);
    }
}
