package souther.runtime;

import org.jspecify.annotations.Nullable;

import java.util.List;
import java.util.Map;
import java.util.function.Function;

/** Map helpers the generated bytecode calls (spec §stdlib-map). A key is compared by value equality
 *  (ADR-0009), so keys are typed {@code Object} here. A {@code Map} value is a {@link PersistentHashMap} (CHAMP, structural sharing): the building
 *  operations return a fresh map that shares structure with the input in O(log n), never mutating it,
 *  so a {@code groupBy} that grows a map is O(n log n) rather than the O(n²) a whole-map copy costs.
 *  The language specifies no iteration order, and it is not insertion order; two maps that are equal
 *  are not guaranteed to iterate in the same order, so a caller may depend on no particular one
 *  ({@link PersistentHashMap}). The boundary does not depend on it either — this runtime writes a
 *  boundary map in ascending order of its rendered keys ({@link Representations#sortedObject}), so
 *  the bytes follow from the keys and not from the trie. Inputs may be any {@code java.util.Map}
 *  (a decoded map comes from Raoh as a {@code LinkedHashMap}), so builders normalize through
 *  {@link PersistentHashMap#from}. */
public final class Maps {

    private Maps() {}

    /** The empty map. Its key and value types are fixed by context (the {@code Map.empty} built-in),
     *  like the empty list; at runtime it is element-agnostic. */
    public static Map<Object, ?> empty() {
        return PersistentHashMap.<Object, Object>empty();
    }

    /** A one-entry map. */
    public static <K, V> Map<K, V> singleton(K key, V value) {
        return singleton(key, value, WorkCheckpoint.NONE);
    }

    /** {@link #singleton(Object, Object)}, hashing the key under {@code checkpoint}. */
    public static <K, V> Map<K, V> singleton(K key, V value, WorkCheckpoint checkpoint) {
        return PersistentHashMap.<K, V>empty().assoc(key, value, checkpoint);
    }

    /** {@code m} with {@code key} set to {@code value} (added, or overwriting an existing entry). */
    public static <K, V> Map<K, V> insert(K key, V value, Map<K, V> m) {
        return insert(key, value, m, WorkCheckpoint.NONE);
    }

    /** {@link #insert(Object, Object, Map)}, comparing keys and values under {@code checkpoint}. */
    public static <K, V> Map<K, V> insert(K key, V value, Map<K, V> m, WorkCheckpoint checkpoint) {
        return PersistentHashMap.from(m, checkpoint).assoc(key, value, checkpoint);
    }

    /** An empty builder to walk with, as the accumulator a fold that only grows a map starts from.
     *  The walk is emitted at the call site, for the reason {@link Lists#builder} gives. */
    public static Map<Object, Object> builder() {
        return new PersistentHashMap.Builder<>();
    }

    /** {@link #builder()}, comparing what is written into it under {@code checkpoint}: the walk
     *  that fills it is the operation the checkpoint was asked for, and the builder is sealed when
     *  the walk ends. */
    public static Map<Object, Object> builder(WorkCheckpoint checkpoint) {
        return new PersistentHashMap.Builder<>(checkpoint);
    }

    /** The map a walk built, handed over: nothing may be written to the builder after this. */
    public static <K, V> Map<K, V> sealed(Map<K, V> acc) {
        return ((PersistentHashMap.Builder<K, V>) acc).build();
    }

    /**
     * Walks {@code xs} from index {@code from} with a builder as the accumulating map and hands over
     * the map it built — the same walk as {@link #builder}'s, for the two shapes the backend does not
     * emit in place: one that starts past the head, and one whose step is {@link Fn#NEVER}.
     *
     * <p>The step is the fold's own, except that its {@code Map.insert} has become {@link #put} and so
     * writes into the builder and answers with it. Reading the accumulator is left as it was: the
     * builder is a {@link java.util.Map}, so the {@code Map.get} in an {@code upsert} answers from
     * what has been written so far. The compiler only rewrites a fold whose accumulator is read and
     * written and nothing else — never stored, never handed on — so no version before the last one is
     * ever seen, which is the whole of what the builder's mutation asks for.
     */
    public static <K, V> Map<K, V> build(Fn step, List<?> xs, long from) {
        return build(step, xs, from, WorkCheckpoint.NONE);
    }

    /** {@link #build(Fn, List, long)}, passing {@code checkpoint} once for each element walked and
     *  comparing what is written under it. */
    @SuppressWarnings("unchecked")
    public static <K, V> Map<K, V> build(Fn step, List<?> xs, long from, WorkCheckpoint checkpoint) {
        PersistentHashMap.Builder<K, V> builder = new PersistentHashMap.Builder<>(checkpoint);
        Object acc = builder;
        int n = xs.size();
        for (long i = from; i >= 0 && i < n; i++) {
            checkpoint.pass();
            acc = step.apply(new Object[] {acc, xs.get((int) i)});
        }
        return ((PersistentHashMap.Builder<K, V>) acc).build();
    }

    /** {@code Map.insert} inside a {@link #build}: writes into the builder the walk carries and
     *  answers with it, so the step reads as the fold it was written as. */
    public static <K, V> Map<K, V> put(Map<K, V> acc, K key, V value) {
        ((PersistentHashMap.Builder<K, V>) acc).set(key, value);
        return acc;
    }

    /** {@code m} without {@code key}; {@code m} unchanged when the key is absent. The
     *  {@code containsKey} probe is worth the extra lookup: when the key is absent it returns the
     *  original map untouched, which avoids normalizing a still-JDK input map (a just-decoded one)
     *  into a {@code PersistentHashMap} for a no-op removal. */
    public static <K, V> Map<K, V> remove(K key, Map<K, V> m) {
        return remove(key, m, WorkCheckpoint.NONE);
    }

    /** {@link #remove(Object, Map)}, comparing keys under {@code checkpoint}. */
    public static <K, V> Map<K, V> remove(K key, Map<K, V> m, WorkCheckpoint checkpoint) {
        if (!containsKey(m, key, checkpoint)) {
            return m;
        }
        return PersistentHashMap.from(m, checkpoint).without(key, checkpoint);
    }

    public static boolean isEmpty(Map<?, ?> m) {
        return m.isEmpty();
    }

    public static long size(Map<?, ?> m) {
        return m.size();
    }

    /** The entries as a list of {@code (key, value)} tuples (ADR-0036), in the map's iteration
     *  order. */
    public static <K, V> List<Tuple> toList(Map<K, V> m) {
        return toList(m, WorkCheckpoint.NONE);
    }

    /** {@link #toList(Map)}, passing {@code checkpoint} once for each entry. */
    public static <K, V> List<Tuple> toList(Map<K, V> m, WorkCheckpoint checkpoint) {
        PersistentVector.Builder<Tuple> out = new PersistentVector.Builder<>();
        for (Map.Entry<K, V> e : m.entrySet()) {
            checkpoint.pass();
            out.add(Tuple.of(e.getKey(), e.getValue()));
        }
        return out.build();
    }

    /** A map from a list of {@code (key, value)} tuples; a later entry overwrites an earlier one
     *  with the same key. */
    public static <K, V> Map<K, V> fromList(List<Tuple> entries) {
        return fromList(entries, WorkCheckpoint.NONE);
    }

    /** {@link #fromList(List)}, passing {@code checkpoint} once for each entry and comparing keys
     *  under it. */
    @SuppressWarnings("unchecked")
    public static <K, V> Map<K, V> fromList(List<Tuple> entries, WorkCheckpoint checkpoint) {
        PersistentHashMap.Builder<K, V> out = new PersistentHashMap.Builder<>(checkpoint);
        for (Tuple e : entries) {
            checkpoint.pass();
            out.set((K) e.get(0), (V) e.get(1));
        }
        return out.build();
    }

    /** {@code Some(value)} when {@code key} is present, else {@code None}. A Souther map never stores a
     *  null value — absence is {@code None}, not a null entry — so a single lookup distinguishes the
     *  two, no {@code containsKey} probe before {@code get}.
     *
     *  <p>The map is read as it stands, by the index it carries. Every map Souther builds is indexed
     *  by the language ({@link Values}), so a Decimal key is found by the amount it is. A map that
     *  arrived from outside carries Java's index instead, and a boundary map's key is a String, a
     *  temporal, an enumeration or a newtype over one of those (ADR-0040) — for every one of those the
     *  two indexes agree, so nothing is bought by rebuilding it and a lookup would cost the whole
     *  map. A {@code java.util.Map} handed in from Java with some other key is answered by its own
     *  index, as a foreign collection is anywhere else (ADR-0085). */
    public static <V> Option<V> get(Map<?, V> map, Object key) {
        return get(map, key, WorkCheckpoint.NONE);
    }

    /** {@link #get(Map, Object)}, comparing keys under {@code checkpoint} where the map is one this
     *  runtime built; a map from outside answers by its own index, as it does without one. */
    public static <V> Option<V> get(Map<?, V> map, Object key, WorkCheckpoint checkpoint) {
        @Nullable V value = map instanceof PersistentHashMap<?, V> ours ? ours.get(key, checkpoint) : map.get(key);
        return value != null ? Option.some(value) : Option.none();
    }

    public static boolean containsKey(Map<?, ?> map, Object key) {
        return containsKey(map, key, WorkCheckpoint.NONE);
    }

    /** {@link #containsKey(Map, Object)}, comparing keys under {@code checkpoint} as
     *  {@link #get(Map, Object, WorkCheckpoint)} does. */
    public static boolean containsKey(Map<?, ?> map, Object key, WorkCheckpoint checkpoint) {
        return map instanceof PersistentHashMap<?, ?> ours ? ours.containsKey(key, checkpoint)
                : map.containsKey(key);
    }

    public static List<Object> keys(Map<?, ?> map) {
        return PersistentVector.from(map.keySet());
    }

    /** {@link #keys(Map)}, passing {@code checkpoint} once for each key. */
    public static List<Object> keys(Map<?, ?> map, WorkCheckpoint checkpoint) {
        return PersistentVector.from(map.keySet(), checkpoint);
    }

    public static <V> List<V> values(Map<?, V> map) {
        return PersistentVector.from(map.values());
    }

    /** {@link #values(Map)}, passing {@code checkpoint} once for each value. */
    public static <V> List<V> values(Map<?, V> map, WorkCheckpoint checkpoint) {
        return PersistentVector.from(map.values(), checkpoint);
    }

    /** {@code m} with every key rewritten by {@code keyFn}, values unchanged.
     *  The encoder uses it to render a boundary map's keys as the text they cross as, before the
     *  map encoder writes a {@code String}-keyed object.
     *
     *  <p>A rendered key is a {@code String} — that is what makes a type a boundary map key at all
     *  (ADR-0040) — so this says so and casts. {@code keyFn} comes from an encoder, which is typed
     *  to its own external form and not to the key position, so the fact is not in its type and has
     *  to be held here. A renderer that writes something else fails at the key it wrote, rather than
     *  reaching {@link Representations#sortedObject} as an object with a key nothing can name.
     *
     *  <p>The result is a fresh trie indexed by the rendered keys, so it is not walked in the source
     *  map's order — a newtype key hashes as the newtype and the string it renders to hashes as a
     *  string, which are different indexes. It is not walked in the written order either: what the
     *  boundary writes is settled after this, by {@link Representations#sortedObject}. This step is
     *  about which keys the object has, not about the order they come out in. */
    public static <K, V> Map<String, V> mapKeys(Map<K, V> m, Function<K, ?> keyFn) {
        return mapKeys(m, keyFn, WorkCheckpoint.NONE);
    }

    /** {@link #mapKeys(Map, Function)}, passing {@code checkpoint} once for each
     *  entry and comparing the rendered keys under it. */
    public static <K, V> Map<String, V> mapKeys(Map<K, V> m, Function<K, ?> keyFn,
                                                WorkCheckpoint checkpoint) {
        PersistentHashMap.Builder<String, V> out = new PersistentHashMap.Builder<>(checkpoint);
        for (Map.Entry<K, V> e : m.entrySet()) {
            checkpoint.pass();
            out.set((String) keyFn.apply(e.getKey()), e.getValue());
        }
        return out.build();
    }

    /** {@link #mapKeys} with the key function first, so a lambda can capture it and take the map per
     *  call. A nested boundary map — one inside a list or another map — is encoded by a single
     *  element encoder reused for every occurrence, which therefore has to hold the key function
     *  rather than receive it alongside each map. */
    public static <K, V> Map<String, V> mapKeysWith(Function<K, ?> keyFn,
                                                    Map<K, V> m) {
        return mapKeys(m, keyFn);
    }

    /** {@link #mapKeysWith(Function, Map)}, passing {@code checkpoint} as
     *  {@link #mapKeys(Map, Function, WorkCheckpoint)} does. */
    public static <K, V> Map<String, V> mapKeysWith(Function<K, ?> keyFn, Map<K, V> m,
                                                    WorkCheckpoint checkpoint) {
        return mapKeys(m, keyFn, checkpoint);
    }

    /** Key and value through {@code keyFn}/{@code valueFn} in one pass, for a crossing's
     *  canonicalization ({@code CanonicalizeAtCrossing}) — not {@link #mapKeysWith}, which the
     *  encoder also calls and which overwrites on a collision because the encoder's own keys are
     *  already known distinct before it renders them. A crossing's keys are not: a Java-supplied
     *  {@code Map} can hold two keys, canonically equivalent to each other, that were two entries
     *  before the invariant was established and would be one silently dropped entry after — the
     *  same shape of loss a derived decoder refuses outright as {@code duplicate_key}. This aborts
     *  the same way rather than choosing a survivor. Either function may be
     *  {@code Function.identity()} where that half of the crossing does not reach a {@code String}. */
    public static Map<Object, Object> canonicalizeWith(Map<Object, Object> m,
                                                        Function<Object, Object> keyFn,
                                                        Function<Object, Object> valueFn) {
        return canonicalizeWith(m, keyFn, valueFn, WorkCheckpoint.NONE);
    }

    /** {@link #canonicalizeWith(Map, Function, Function)},
     *  passing {@code checkpoint} once for each entry and comparing the canonical keys under it. */
    public static Map<Object, Object> canonicalizeWith(Map<Object, Object> m,
                                                        Function<Object, Object> keyFn,
                                                        Function<Object, Object> valueFn,
                                                        WorkCheckpoint checkpoint) {
        Map<Object, Object> canonicalToOriginal = new java.util.HashMap<>();
        PersistentHashMap.Builder<Object, Object> out = new PersistentHashMap.Builder<>(checkpoint);
        for (Map.Entry<Object, Object> e : m.entrySet()) {
            checkpoint.pass();
            Object canonicalKey = keyFn.apply(e.getKey());
            Object priorOriginal = canonicalToOriginal.putIfAbsent(canonicalKey, e.getKey());
            if (priorOriginal != null && !priorOriginal.equals(e.getKey())) {
                throw new ConstraintViolation("two distinct keys canonicalize to the same key"
                        + " crossing into the domain: " + priorOriginal + " and " + e.getKey());
            }
            out.set(canonicalKey, valueFn.apply(e.getValue()));
        }
        return out.build();
    }

    /** {@link #canonicalizeWith}, the map last: a nested {@code Map} — one inside a list, a set or
     *  an option — is canonicalized by a single element function reused for every occurrence, which
     *  therefore has to capture {@code keyFn}/{@code valueFn} and receive the map per call, the same
     *  reason {@link #mapKeysWith} takes its function first. */
    public static Map<Object, Object> canonicalizeWithCaptured(
            Function<Object, Object> keyFn,
            Function<Object, Object> valueFn, Map<Object, Object> m) {
        return canonicalizeWith(m, keyFn, valueFn);
    }

    /** {@link #canonicalizeWithCaptured(Function, Function,
     *  Map)}, passing {@code checkpoint} as {@link #canonicalizeWith} does. */
    public static Map<Object, Object> canonicalizeWithCaptured(
            Function<Object, Object> keyFn,
            Function<Object, Object> valueFn, Map<Object, Object> m,
            WorkCheckpoint checkpoint) {
        return canonicalizeWith(m, keyFn, valueFn, checkpoint);
    }
}
