package souther.runtime;

import org.jspecify.annotations.Nullable;

/** Option helpers the generated bytecode calls (spec §stdlib-option). {@code Option} is not
 *  surface-writable (spec §algebraic-types): a Souther body cannot rebuild a {@code Some}, so the transforming
 *  operation lives here in the kernel. {@code withDefault}, which only reads an option, needs no
 *  kernel — it is an ordinary self-hosted helper in {@code souther.option}. */
public final class Options {

    private Options() {}

    /** Maps the contained value through {@code f}, keeping {@code None} as {@code None}; {@code f}
     *  never sees a {@code None}. The step is a first-class function value, applied to the wrapped
     *  value and its result rewrapped in a fresh {@code Some}. */
    public static Option<Object> map(Fn f, Option<?> o) {
        return o instanceof Option.Some<?> s
                ? Option.some(f.apply(new Object[] {s.value()}))
                : Option.none();
    }

    /**
     * An optional written where there is no key to omit — a collection's member, a map's value —
     * which is {@code null} for an absent one and {@code inner}'s form for a present one
     * (spec {@code [#absence-is-written-as-null]}).
     *
     * <p>{@code inner} arrives as a {@link java.util.function.Function} rather than as the boundary
     * library's encoder, because the kernel does not know that library: representation is the
     * boundary's and the domain's types are Souther's (spec {@code [#separate-representation]}).
     * What is bound here is the encoder's own method, so the indirection costs a call and no
     * knowledge.
     */
    public static @Nullable Object encodedOrNull(java.util.function.Function<Object, Object> inner,
                                                 Option<?> o) {
        return o instanceof Option.Some<?> s ? inner.apply(s.value()) : null;
    }
}
