/**
 * The runtime the domain world of generated bytecode stands on. Nothing here is ever null: absence is
 * {@link souther.runtime.Option}, a failure is a case of the output union, and a collection holds
 * neither null keys nor null values. The package says so with {@code @NullMarked}, so a caller's
 * compiler knows it too — without it a Kotlin caller sees platform types, where a null check is
 * neither required nor possible. The few places that do admit a null are marked one by one.
 */
@NullMarked
package souther.runtime;

import org.jspecify.annotations.NullMarked;
