package souther.runtime;

import org.jspecify.annotations.Nullable;

import java.util.AbstractList;
import java.util.Arrays;
import java.util.Collection;
import java.util.Iterator;
import java.util.List;
import java.util.NoSuchElementException;
import java.util.RandomAccess;
import java.util.function.Consumer;

/**
 * An immutable indexed sequence backed by a bit-mapped vector trie (branching factor 32, the
 * Clojure/Scala layout). It is the persistent structure the generated bytecode's {@code List}
 * values grow into: {@code append} shares structure with the previous version and runs in O(1)
 * amortized, so a fold that builds a list by {@code acc ++ [x]} (which {@link Lists#concat} turns
 * into a single {@code append}) is O(n) instead of the O(n²) a whole-list copy would cost.
 *
 * <p>It implements {@link java.util.List} so it flows through codegen and the boundary unchanged
 * (the runtime helpers keep their {@code java.util.List} signatures and return one of these upcast).
 * Extending {@link AbstractList} supplies the immutable, mutator-throwing defaults and an
 * order-sensitive {@code hashCode}; {@link #get(int)}, {@link #iterator()} and {@link #equals}
 * override the hot paths so iteration and equality stay O(n) rather than O(n·log n).
 *
 * <p>Values are never null (a Souther collection models absence with {@code Option}, not a null
 * element), which callers such as {@link Lists} rely on. The trie's own arrays are another matter and
 * are typed {@code @Nullable Object[]}: a node is {@code WIDTH} wide with a null in every slot it has
 * not reached yet, which is the representation, not an element.
 *
 * <p>Bulk construction ({@link #from}, and {@link Lists#sort}/{@code sortBy}) fills one 32-slot tail
 * per block through the package-private {@link Builder}, which owns every node it touches.
 *
 * <p><b>The claimed tail.</b> A version's tail array is 32 wide with only the first
 * {@code cnt - tailoff()} slots in use, and successive appends write into the <em>same</em> array
 * rather than copying it — which is what keeps {@code append}'s constant factor at O(1) instead of
 * the O(32) an exactly-sized, re-copied tail costs (ADR-0060). A {@link Tail} hands out slot
 * {@code j} to whoever moves {@code claimed} from {@code j} to {@code j + 1}, so <b>each slot is
 * written at most once, ever</b>: a version holding {@code m} elements reads only {@code [0, m)},
 * and those were all written before it was constructed. A second append from that same version
 * loses the claim and copies instead, so branching keeps working.
 *
 * <p><b>Why the claim is confined to one thread rather than made atomic.</b> Final-field reachability
 * (JLS 17.5) is not enough on its own here: it covers writes performed <em>before</em> the freeze of
 * the object being read through, and a shared array outlives many freezes. Suppose two threads could
 * extend one array — T1 writes {@code a[0]} and freezes {@code V1}, T2 obtains {@code V1}, writes
 * {@code a[1]} and freezes {@code V2}. A reader of {@code V2} needs {@code a[0]}, but T1's write is
 * ordered before T2's freeze only if {@code V1} reached T2 with a happens-before edge. Publish it
 * through a race and there is none, and the guarantee is formally lost — invisibly, since no test
 * would show it.
 *
 * <p>One owner per array removes that case rather than betting against it. Every slot a version can
 * read was then written by the very thread that froze that version, so program order puts each write
 * before that freeze and JLS 17.5 covers the whole array, exactly as when every append allocated a
 * fresh one. The same guarantee runs in the read direction: a non-owner reads the prefix it copies
 * through the previous version's freeze, performed by the owner after writing it. An append from a
 * non-owning thread therefore copies once and owns the copy, which costs nothing on the fold path
 * (single-threaded) and keeps the hot path free of any atomic instruction.
 */
public final class PersistentVector<E> extends AbstractList<E> implements RandomAccess {

    private static final int BITS = 5;
    private static final int WIDTH = 1 << BITS;   // 32
    private static final int MASK = WIDTH - 1;    // 31

    /** Internal trie nodes are always {@code WIDTH} wide (nulls for absent children); a leaf that
     *  came from a full tail is a {@code WIDTH}-wide element array. */
    private static final @Nullable Object[] EMPTY_NODE = new @Nullable Object[WIDTH];

    /**
     * A tail array plus the claim that decides who may still extend it. The whole ownership rule
     * lives here; see the class javadoc for why it is a rule and not a lock.
     */
    private static final class Tail {
        /**
         * Final so JLS 17.5 reaches the elements through it — necessary but not sufficient on its
         * own. What makes the guarantee hold for a shared array is {@link #owner}: one writer means
         * every element a version can read was written by the thread that froze it. See the class
         * javadoc; changing either half without the other breaks the argument.
         */
        private final @Nullable Object[] a;
        /**
         * {@code Thread.threadId()} of the only thread that may extend {@link #a}; 0 = nobody.
         *
         * <p>This rests on thread ids not being reused. {@code Thread.threadId()} (Java 19+) is
         * documented as unique for the JVM's lifetime, unlike the deprecated {@code getId()} it
         * replaced. If one were ever reused, a new thread inheriting a dead thread's id would pass
         * the owner test on a tail it did not build and could re-claim a written slot, which is
         * silent corruption — so the guarantee is load-bearing, not incidental.
         */
        private final long owner;
        /** Slots handed out so far. Written only by {@link #owner}, and only upward. */
        private int claimed;

        private Tail(@Nullable Object[] a, long owner, int claimed) {
            this.a = a;
            this.owner = owner;
            this.claimed = claimed;
        }

        /**
         * Takes slot {@code used} for the caller, who may then write it.
         *
         * <p>Each test rejects a different way of not being the one extender: {@code owner} rejects
         * a sealed tail and another thread's; {@code claimed} rejects a version that has already
         * been extended, so a branch copies rather than overwriting its sibling's element; and
         * {@code a.length} is the bound the caller's store needs, which is why it stays here even
         * though every owned array is {@code WIDTH} wide today.
         */
        boolean tryClaim(int used) {
            if (owner != Thread.currentThread().threadId() || claimed != used || used >= a.length) {
                return false;
            }
            claimed = used + 1;
            return true;
        }

        /** Holds the first {@code used} elements of this tail, then {@code val}, in a fresh
         *  {@code WIDTH}-wide array the calling thread owns. The losing side of a claim. */
        Tail extendedCopy(int used, Object val) {
            @Nullable Object[] fresh = new @Nullable Object[WIDTH];
            System.arraycopy(a, 0, fresh, 0, used);
            fresh[used] = val;
            return new Tail(fresh, Thread.currentThread().threadId(), used + 1);
        }

        /** A tail nobody may extend. {@code claimed == a.length} leaves no slot to claim: the shared
         *  empty tail, a {@link Builder} handover at its exact length, a full tail becoming a leaf. */
        static Tail sealed(@Nullable Object[] a) {
            return new Tail(a, 0L, a.length);
        }
    }

    private static final Tail EMPTY_TAIL = Tail.sealed(new @Nullable Object[0]);

    public static final PersistentVector<?> EMPTY =
            new PersistentVector<>(0, BITS, EMPTY_NODE, EMPTY_TAIL);

    private final int cnt;
    private final int shift;
    private final @Nullable Object[] root;
    private final Tail tail;

    private PersistentVector(int cnt, int shift, @Nullable Object[] root, Tail tail) {
        this.cnt = cnt;
        this.shift = shift;
        this.root = root;
        this.tail = tail;
        // Every slot this version reads has been claimed, and no claim runs past the array.
        assert cnt - tailoff() <= tail.claimed && tail.claimed <= tail.a.length
                : "tail claim out of step with cnt=" + cnt;
    }

    @SuppressWarnings("unchecked")
    public static <E> PersistentVector<E> empty() {
        return (PersistentVector<E>) EMPTY;
    }

    /** A one-element vector. */
    public static <E> PersistentVector<E> ofSingle(E value) {
        return PersistentVector.<E>empty().append(value);
    }

    /** Wraps {@code src} as a PersistentVector, sharing when it already is one and copying only when
     *  it is some other {@code java.util.List}/{@code Collection} (a JDK list from a literal or the
     *  decode boundary). Empty yields the shared {@link #EMPTY}. */
    @SuppressWarnings("unchecked")
    public static <E> PersistentVector<E> from(Collection<? extends E> src) {
        if (src instanceof PersistentVector<?> pv) {
            return (PersistentVector<E>) pv;
        }
        if (src.isEmpty()) {
            return empty();
        }
        Builder<E> b = new Builder<>();
        for (E e : src) {
            b.add(e);
        }
        return b.build();
    }

    @Override
    public int size() {
        return cnt;
    }

    private int tailoff() {
        if (cnt < WIDTH) {
            return 0;
        }
        return ((cnt - 1) >>> BITS) << BITS;
    }

    /**
     * The leaf array holding element {@code i}. For an index in the tail the array returned may be
     * <em>longer</em> than the logical leaf, its later slots belonging to longer versions that share
     * it, so every caller must bound its read by {@code cnt} and never by the array's length. That
     * is the invariant a change here is most likely to break.
     */
    private @Nullable Object[] arrayFor(int i) {
        if (i < 0 || i >= cnt) {
            throw new IndexOutOfBoundsException("Index " + i + " out of bounds for length " + cnt);
        }
        if (i >= tailoff()) {
            return tail.a;
        }
        @Nullable Object[] node = root;
        for (int level = shift; level > 0; level -= BITS) {
            node = (@Nullable Object[]) node[(i >>> level) & MASK];
        }
        return node;
    }

    @Override
    @SuppressWarnings("unchecked")
    public E get(int i) {
        return (E) arrayFor(i)[i & MASK];
    }

    /** This vector with {@code val} appended (Clojure {@code conj}); O(1) amortized, sharing the
     *  unchanged structure with {@code this}. */
    public PersistentVector<E> append(E val) {
        int used = cnt - tailoff();
        if (used == WIDTH) {
            return appendSpilling(val);
        }
        // Claim the slot, then write it: no existing version reads it, and whoever lost the claim
        // never touches it, so the write is visible to nothing but the vector returned here.
        if (tail.tryClaim(used)) {
            tail.a[used] = val;
            return new PersistentVector<>(cnt + 1, shift, root, tail);
        }
        return new PersistentVector<>(cnt + 1, shift, root, tail.extendedCopy(used, val));
    }

    /** The tail is full: push it into the trie as a leaf and start a fresh one-element tail. Split
     *  out so {@link #append}'s claim path stays small enough for the JIT to inline. */
    private PersistentVector<E> appendSpilling(E val) {
        assert tail.a.length == WIDTH : "a full tail must be a WIDTH-wide leaf";
        @Nullable Object[] leaf = tail.a;
        @Nullable Object[] newRoot;
        int newShift = shift;
        if ((cnt >>> BITS) > (1 << shift)) {   // the trie is full: add a level above the root
            newRoot = new @Nullable Object[WIDTH];
            newRoot[0] = root;
            newRoot[1] = newPath(shift, leaf);
            newShift += BITS;
        } else {
            newRoot = pushTail(shift, root, leaf);
        }
        return new PersistentVector<>(cnt + 1, newShift, newRoot, EMPTY_TAIL.extendedCopy(0, val));
    }

    /** Copies the spine down to where the full tail becomes a new leaf, sharing every untouched
     *  sibling. {@code cnt} here is the size before the append (i.e. including the full tail). */
    private @Nullable Object[] pushTail(int level, @Nullable Object[] parent, @Nullable Object[] tailNode) {
        int subidx = ((cnt - 1) >>> level) & MASK;
        @Nullable Object[] ret = parent.clone();
        @Nullable Object[] nodeToInsert;
        if (level == BITS) {
            nodeToInsert = tailNode;
        } else {
            @Nullable Object[] child = (@Nullable Object[]) parent[subidx];
            nodeToInsert = child != null
                    ? pushTail(level - BITS, child, tailNode)
                    : newPath(level - BITS, tailNode);
        }
        ret[subidx] = nodeToInsert;
        return ret;
    }

    private static @Nullable Object[] newPath(int level, @Nullable Object[] node) {
        if (level == 0) {
            return node;
        }
        @Nullable Object[] ret = new @Nullable Object[WIDTH];
        ret[0] = newPath(level - BITS, node);
        return ret;
    }

    /** A chunked iterator: it walks each leaf array in order, so iteration (and the {@code equals}/
     *  {@code hashCode} and fold reads built on it) is O(1) per element, never O(log n). */
    @Override
    public Iterator<E> iterator() {
        return new Iterator<>() {
            private int i = 0;
            private int base = 0;
            private @Nullable Object[] leaf = cnt > 0 ? arrayFor(0) : EMPTY_TAIL.a;

            @Override
            public boolean hasNext() {
                return i < cnt;
            }

            @Override
            @SuppressWarnings("unchecked")
            public E next() {
                if (i >= cnt) {
                    throw new NoSuchElementException();
                }
                if (i - base == WIDTH) {
                    leaf = arrayFor(i);
                    base += WIDTH;
                }
                return (E) leaf[i++ & MASK];
            }
        };
    }

    @Override
    @SuppressWarnings("unchecked")
    public void forEach(Consumer<? super E> action) {
        for (int base = 0; base < cnt; base += WIDTH) {
            @Nullable Object[] leaf = arrayFor(base);
            int n = Math.min(WIDTH, cnt - base);
            for (int j = 0; j < n; j++) {
                action.accept((E) leaf[j]);
            }
        }
    }

    /** Order-sensitive list equality (the {@code List} contract), compared through the chunked
     *  iterator so a persistent-vector comparison stays O(n) — and cross-type against any other
     *  {@code List} (e.g. an {@code ArrayList} from a literal). */
    @Override
    public boolean equals(@Nullable Object o) {
        if (o == this) {
            return true;
        }
        if (!(o instanceof List<?> other)) {
            return false;
        }
        if (other.size() != cnt) {
            return false;
        }
        Iterator<E> a = iterator();
        Iterator<?> b = other.iterator();
        while (a.hasNext() && b.hasNext()) {
            E x = a.next();
            Object y = b.next();
            if (x == null ? y != null : !x.equals(y)) {
                return false;
            }
        }
        return !a.hasNext() && !b.hasNext();
    }

    @Override
    public int hashCode() {
        // The List-contract hash (AbstractList's formula), via the chunked iterator: O(n).
        int h = 1;
        for (int base = 0; base < cnt; base += WIDTH) {
            @Nullable Object[] leaf = arrayFor(base);
            int n = Math.min(WIDTH, cnt - base);
            for (int j = 0; j < n; j++) {
                Object e = leaf[j];
                h = 31 * h + (e == null ? 0 : e.hashCode());
            }
        }
        return h;
    }

    /**
     * A single-use, from-empty bulk builder for {@link #from} (and so for {@code Lists.sort}/
     * {@code sortBy} and the {@code Map}/{@code Set} {@code toList}/{@code keys}/{@code values}, which
     * all route through {@code from}). Every node it touches it created itself, so it mutates its own
     * tail and trie in place — filling one 32-slot tail array per block instead of re-copying a
     * growing tail on each element the way immutable {@link #append} would. That drops the per-element
     * constant from O(32) tail copies to O(1) while producing a structurally identical vector.
     */
    static final class Builder<E> {
        private int cnt = 0;
        private int shift = BITS;
        private @Nullable Object[] root = EMPTY_NODE;   // shared and untouched until the first spill into the trie
        private @Nullable Object[] tail = new @Nullable Object[WIDTH];
        private int tailLen = 0;

        Builder<E> add(E val) {
            if (tailLen == WIDTH) {
                spillTail();
                tail = new @Nullable Object[WIDTH];
                tailLen = 0;
            }
            tail[tailLen++] = val;
            cnt++;
            return this;
        }

        PersistentVector<E> build() {
            if (cnt == 0) {
                return empty();
            }
            // Sealed and at its exact length: a decoded or sorted list is long-lived and should not
            // carry a 32-wide array for appends that will never come (ADR-0060).
            @Nullable Object[] finalTail = tailLen == WIDTH ? tail : Arrays.copyOf(tail, tailLen);
            return new PersistentVector<>(cnt, shift, root, Tail.sealed(finalTail));
        }

        /** Pushes the now-full tail into the trie, mirroring {@link #append}'s spill but mutating the
         *  builder's own nodes. {@code cnt} is the element count including the full tail here. */
        private void spillTail() {
            if ((cnt >>> BITS) > (1 << shift)) {
                @Nullable Object[] newRoot = new @Nullable Object[WIDTH];
                newRoot[0] = root;
                newRoot[1] = newPath(shift, tail);
                root = newRoot;
                shift += BITS;
            } else {
                if (root == EMPTY_NODE) {
                    root = new @Nullable Object[WIDTH];   // own the root before mutating it
                }
                pushTailOwned(shift, root, tail);
            }
        }

        private void pushTailOwned(int level, @Nullable Object[] parent, @Nullable Object[] tailNode) {
            int subidx = ((cnt - 1) >>> level) & MASK;
            if (level == BITS) {
                parent[subidx] = tailNode;
                return;
            }
            @Nullable Object[] child = (@Nullable Object[]) parent[subidx];
            if (child == null) {
                parent[subidx] = newPath(level - BITS, tailNode);
            } else {
                pushTailOwned(level - BITS, child, tailNode);
            }
        }
    }
}
