package souther.runtime;

import java.util.AbstractList;
import java.util.Arrays;
import java.util.Collection;
import java.util.Iterator;
import java.util.List;
import java.util.NoSuchElementException;
import java.util.RandomAccess;
import java.util.function.Consumer;

/**
 * An immutable indexed sequence backed by a bit-mapped vector trie (branching factor 32, the
 * Clojure/Scala layout). It is the persistent structure the generated bytecode's {@code List}
 * values grow into: {@code append} shares structure with the previous version and runs in O(1)
 * amortized, so a fold that builds a list by {@code acc ++ [x]} (which {@link Lists#concat} turns
 * into a single {@code append}) is O(n) instead of the O(n²) a whole-list copy would cost.
 *
 * <p>It implements {@link java.util.List} so it flows through codegen and the boundary unchanged
 * (the runtime helpers keep their {@code java.util.List} signatures and return one of these upcast).
 * Extending {@link AbstractList} supplies the immutable, mutator-throwing defaults and an
 * order-sensitive {@code hashCode}; {@link #get(int)}, {@link #iterator()} and {@link #equals}
 * override the hot paths so iteration and equality stay O(n) rather than O(n·log n).
 *
 * <p>Values are never null (a Souther collection models absence with {@code Option}, not a null
 * element), which callers such as {@link Lists} rely on.
 *
 * <p>Bulk construction ({@link #from}, and {@link Lists#sort}/{@code sortBy}) is O(n) here through
 * repeated {@code append}; a transient (edit-token) builder would cut its constant factor and is a
 * later optimization, not needed for the asymptotics.
 */
public final class PersistentVector<E> extends AbstractList<E> implements RandomAccess {

    private static final int BITS = 5;
    private static final int WIDTH = 1 << BITS;   // 32
    private static final int MASK = WIDTH - 1;    // 31

    /** Internal trie nodes are always {@code WIDTH} wide (nulls for absent children); a leaf that
     *  came from a full tail is a {@code WIDTH}-wide element array. */
    private static final Object[] EMPTY_NODE = new Object[WIDTH];
    private static final Object[] EMPTY_TAIL = new Object[0];

    public static final PersistentVector<?> EMPTY =
            new PersistentVector<>(0, BITS, EMPTY_NODE, EMPTY_TAIL);

    private final int cnt;
    private final int shift;
    private final Object[] root;
    private final Object[] tail;

    private PersistentVector(int cnt, int shift, Object[] root, Object[] tail) {
        this.cnt = cnt;
        this.shift = shift;
        this.root = root;
        this.tail = tail;
    }

    @SuppressWarnings("unchecked")
    public static <E> PersistentVector<E> empty() {
        return (PersistentVector<E>) EMPTY;
    }

    /** A one-element vector. */
    public static <E> PersistentVector<E> ofSingle(E value) {
        return PersistentVector.<E>empty().append(value);
    }

    /** Wraps {@code src} as a PersistentVector, sharing when it already is one and copying only when
     *  it is some other {@code java.util.List}/{@code Collection} (a JDK list from a literal or the
     *  decode boundary). Empty yields the shared {@link #EMPTY}. */
    @SuppressWarnings("unchecked")
    public static <E> PersistentVector<E> from(Collection<? extends E> src) {
        if (src instanceof PersistentVector<?> pv) {
            return (PersistentVector<E>) pv;
        }
        if (src.isEmpty()) {
            return empty();
        }
        Builder<E> b = new Builder<>();
        for (E e : src) {
            b.add(e);
        }
        return b.build();
    }

    @Override
    public int size() {
        return cnt;
    }

    private int tailoff() {
        if (cnt < WIDTH) {
            return 0;
        }
        return ((cnt - 1) >>> BITS) << BITS;
    }

    private Object[] arrayFor(int i) {
        if (i < 0 || i >= cnt) {
            throw new IndexOutOfBoundsException("Index " + i + " out of bounds for length " + cnt);
        }
        if (i >= tailoff()) {
            return tail;
        }
        Object[] node = root;
        for (int level = shift; level > 0; level -= BITS) {
            node = (Object[]) node[(i >>> level) & MASK];
        }
        return node;
    }

    @Override
    @SuppressWarnings("unchecked")
    public E get(int i) {
        return (E) arrayFor(i)[i & MASK];
    }

    /** This vector with {@code val} appended (Clojure {@code conj}); O(1) amortized, sharing the
     *  unchanged structure with {@code this}. */
    public PersistentVector<E> append(E val) {
        // Room left in the tail: copy the tail (at most WIDTH long) and add the element.
        if (cnt - tailoff() < WIDTH) {
            Object[] newTail = new Object[tail.length + 1];
            System.arraycopy(tail, 0, newTail, 0, tail.length);
            newTail[tail.length] = val;
            return new PersistentVector<>(cnt + 1, shift, root, newTail);
        }
        // Tail is full: push it into the trie as a leaf, start a fresh one-element tail.
        Object[] newRoot;
        int newShift = shift;
        if ((cnt >>> BITS) > (1 << shift)) {   // the trie is full: add a level above the root
            newRoot = new Object[WIDTH];
            newRoot[0] = root;
            newRoot[1] = newPath(shift, tail);
            newShift += BITS;
        } else {
            newRoot = pushTail(shift, root, tail);
        }
        return new PersistentVector<>(cnt + 1, newShift, newRoot, new Object[]{val});
    }

    /** Copies the spine down to where the full tail becomes a new leaf, sharing every untouched
     *  sibling. {@code cnt} here is the size before the append (i.e. including the full tail). */
    private Object[] pushTail(int level, Object[] parent, Object[] tailNode) {
        int subidx = ((cnt - 1) >>> level) & MASK;
        Object[] ret = parent.clone();
        Object[] nodeToInsert;
        if (level == BITS) {
            nodeToInsert = tailNode;
        } else {
            Object[] child = (Object[]) parent[subidx];
            nodeToInsert = child != null
                    ? pushTail(level - BITS, child, tailNode)
                    : newPath(level - BITS, tailNode);
        }
        ret[subidx] = nodeToInsert;
        return ret;
    }

    private static Object[] newPath(int level, Object[] node) {
        if (level == 0) {
            return node;
        }
        Object[] ret = new Object[WIDTH];
        ret[0] = newPath(level - BITS, node);
        return ret;
    }

    /** A chunked iterator: it walks each leaf array in order, so iteration (and the {@code equals}/
     *  {@code hashCode} and fold reads built on it) is O(1) per element, never O(log n). */
    @Override
    public Iterator<E> iterator() {
        return new Iterator<>() {
            private int i = 0;
            private int base = 0;
            private Object[] leaf = cnt > 0 ? arrayFor(0) : EMPTY_TAIL;

            @Override
            public boolean hasNext() {
                return i < cnt;
            }

            @Override
            @SuppressWarnings("unchecked")
            public E next() {
                if (i >= cnt) {
                    throw new NoSuchElementException();
                }
                if (i - base == WIDTH) {
                    leaf = arrayFor(i);
                    base += WIDTH;
                }
                return (E) leaf[i++ & MASK];
            }
        };
    }

    @Override
    @SuppressWarnings("unchecked")
    public void forEach(Consumer<? super E> action) {
        for (int base = 0; base < cnt; base += WIDTH) {
            Object[] leaf = arrayFor(base);
            int n = Math.min(WIDTH, cnt - base);
            for (int j = 0; j < n; j++) {
                action.accept((E) leaf[j]);
            }
        }
    }

    /** Order-sensitive list equality (the {@code List} contract), compared through the chunked
     *  iterator so a persistent-vector comparison stays O(n) — and cross-type against any other
     *  {@code List} (e.g. an {@code ArrayList} from a literal). */
    @Override
    public boolean equals(Object o) {
        if (o == this) {
            return true;
        }
        if (!(o instanceof List<?> other)) {
            return false;
        }
        if (other.size() != cnt) {
            return false;
        }
        Iterator<E> a = iterator();
        Iterator<?> b = other.iterator();
        while (a.hasNext() && b.hasNext()) {
            E x = a.next();
            Object y = b.next();
            if (x == null ? y != null : !x.equals(y)) {
                return false;
            }
        }
        return !a.hasNext() && !b.hasNext();
    }

    @Override
    public int hashCode() {
        // The List-contract hash (AbstractList's formula), via the chunked iterator: O(n).
        int h = 1;
        for (int base = 0; base < cnt; base += WIDTH) {
            Object[] leaf = arrayFor(base);
            int n = Math.min(WIDTH, cnt - base);
            for (int j = 0; j < n; j++) {
                Object e = leaf[j];
                h = 31 * h + (e == null ? 0 : e.hashCode());
            }
        }
        return h;
    }

    /**
     * A single-use, from-empty bulk builder for {@link #from} (and so for {@code Lists.sort}/
     * {@code sortBy} and the {@code Map}/{@code Set} {@code toList}/{@code keys}/{@code values}, which
     * all route through {@code from}). Every node it touches it created itself, so it mutates its own
     * tail and trie in place — filling one 32-slot tail array per block instead of re-copying a
     * growing tail on each element the way immutable {@link #append} would. That drops the per-element
     * constant from O(32) tail copies to O(1) while producing a structurally identical vector.
     */
    static final class Builder<E> {
        private int cnt = 0;
        private int shift = BITS;
        private Object[] root = EMPTY_NODE;   // shared and untouched until the first spill into the trie
        private Object[] tail = new Object[WIDTH];
        private int tailLen = 0;

        Builder<E> add(E val) {
            if (tailLen == WIDTH) {
                spillTail();
                tail = new Object[WIDTH];
                tailLen = 0;
            }
            tail[tailLen++] = val;
            cnt++;
            return this;
        }

        PersistentVector<E> build() {
            if (cnt == 0) {
                return empty();
            }
            Object[] finalTail = tailLen == WIDTH ? tail : Arrays.copyOf(tail, tailLen);
            return new PersistentVector<>(cnt, shift, root, finalTail);
        }

        /** Pushes the now-full tail into the trie, mirroring {@link #append}'s spill but mutating the
         *  builder's own nodes. {@code cnt} is the element count including the full tail here. */
        private void spillTail() {
            if ((cnt >>> BITS) > (1 << shift)) {
                Object[] newRoot = new Object[WIDTH];
                newRoot[0] = root;
                newRoot[1] = newPath(shift, tail);
                root = newRoot;
                shift += BITS;
            } else {
                if (root == EMPTY_NODE) {
                    root = new Object[WIDTH];   // own the root before mutating it
                }
                pushTailOwned(shift, root, tail);
            }
        }

        private void pushTailOwned(int level, Object[] parent, Object[] tailNode) {
            int subidx = ((cnt - 1) >>> level) & MASK;
            if (level == BITS) {
                parent[subidx] = tailNode;
                return;
            }
            Object[] child = (Object[]) parent[subidx];
            if (child == null) {
                parent[subidx] = newPath(level - BITS, tailNode);
            } else {
                pushTailOwned(level - BITS, child, tailNode);
            }
        }
    }
}
