package souther.runtime;

import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.ConcurrentHashMap;
import java.util.regex.Pattern;

/**
 * String helpers the generated bytecode calls (spec §stdlib-string). These back the {@code souther.string}
 * intrinsics that a single JVM {@code String} method does not already cover.
 *
 * <p>Every length, index and range here counts Unicode code points, which is what the language
 * publishes; the UTF-16 code unit a JVM {@code String} stores is this class's business and reaches
 * no signature above it. The conversion is {@link String#codePointCount} on the way in and
 * {@link String#offsetByCodePoints} on the way back, so no result can hold half a surrogate pair.
 */
public final class Strings {

    /** Runs of whitespace, for {@link #words} — compiled once rather than per call. */
    private static final Pattern WHITESPACE = Pattern.compile("\\s+");

    private Strings() {}

    /** The number of code points, as the Int the language carries. Counting them is a walk, so this
     *  is O(n) where the UTF-16 unit count would be a field read — the price of a length that agrees
     *  with {@link #characters} and cannot be half a character. */
    public static long length(String s) {
        return s.codePointCount(0, s.length());
    }

    /** The UTF-16 offset of code point {@code index}, or an abort where the string has no such code
     *  point. Every index the language hands in comes through here, so an out-of-range one is
     *  reported the same way wherever it was written. */
    private static int offsetOf(String s, long index, String what) {
        if (index < 0 || index > length(s)) {
            throw new ConstraintViolation(what + " out of range: " + index);
        }
        return s.offsetByCodePoints(0, (int) index);
    }

    /** The code points of {@code s} from {@code fromInclusive} up to but not including
     *  {@code toExclusive}. Both are code-point indices, so a surrogate pair is never split. */
    public static String slice(String s, long fromInclusive, long toExclusive) {
        int from = offsetOf(s, fromInclusive, "String.slice fromInclusive");
        int to = offsetOf(s, toExclusive, "String.slice toExclusive");
        if (to < from) {
            throw new ConstraintViolation(
                    "String.slice toExclusive " + toExclusive + " is before fromInclusive "
                            + fromInclusive);
        }
        return s.substring(from, to);
    }

    /** Splits on a literal separator, keeping empty pieces (Elm {@code String.split} semantics):
     *  {@code split("a,,b", ",") == ["a", "", "b"]}. An empty separator yields the whole string. */
    public static List<String> split(String s, String sep) {
        if (sep.isEmpty()) {
            return List.of(s);
        }
        List<String> out = new ArrayList<>();
        int from = 0;
        while (true) {
            int at = s.indexOf(sep, from);
            if (at < 0) {
                out.add(s.substring(from));
                break;
            }
            out.add(s.substring(from, at));
            from = at + sep.length();
        }
        return List.copyOf(out);
    }

    /** Joins with a separator ({@code join(["a", "b"], "-") == "a-b"}). */
    public static String join(List<String> xs, String sep) {
        return String.join(sep, xs);
    }

    /** Joins a list of strings with no separator (Elm {@code String.concat}):
     *  {@code concat(["a", "b", "c"]) == "abc"}. This is {@code join(xs, "")}. */
    public static String concat(List<String> xs) {
        return join(xs, "");
    }

    /** Replaces every literal occurrence of {@code target} (Elm {@code String.replace}). An empty
     *  {@code target} leaves the string unchanged rather than splicing between every character. */
    public static String replace(String s, String target, String replacement) {
        if (target.isEmpty()) {
            return s;
        }
        return s.replace(target, replacement);
    }

    /** Renders an integer as its decimal string ({@code fromInt(42) == "42"}). */
    public static String fromInt(long n) {
        return Long.toString(n);
    }

    /** Splits on runs of whitespace, dropping empty pieces (Elm {@code String.words}):
     *  {@code words("  a  b ") == ["a", "b"]}. */
    public static List<String> words(String s) {
        List<String> out = new ArrayList<>();
        for (String w : WHITESPACE.split(s)) {
            if (!w.isEmpty()) {
                out.add(w);
            }
        }
        return List.copyOf(out);
    }

    /** Compiled patterns, cached by source so {@link #matches} does not recompile per call. The
     *  compiler requires {@code String.matches}'s pattern to be a literal, so the keys are the pattern
     *  literals of the programs loaded here — bounded by source, not by runtime input, and never
     *  evicted. */
    private static final ConcurrentHashMap<String, Pattern> PATTERNS = new ConcurrentHashMap<>();

    /** Whether the whole string matches the regex (anchored, like {@code Pattern.matches}). Backs
     *  {@code String.matches} for format-constrained values. The pattern is a compile-time-validated
     *  literal, so {@link Pattern#compile} here cannot fail. */
    public static boolean matches(String s, String pattern) {
        return PATTERNS.computeIfAbsent(pattern, Pattern::compile).matcher(s).matches();
    }

    /** The characters of {@code s}, one per Unicode code point
     *  ({@code characters("a12") == ["a", "1", "2"]}). Souther has no {@code Char}, so a character is
     *  a one-code-point {@code String}; this is what a {@code List.fold} over characters iterates. */
    public static List<String> characters(String s) {
        List<String> out = new ArrayList<>();
        s.codePoints().forEach(cp -> out.add(new String(Character.toChars(cp))));
        return List.copyOf(out);
    }

    /** The same split as {@link #characters}, as the code points themselves. Total: the empty string
     *  gives the empty list, so a caller wanting the first one takes it through {@code List.get} and
     *  reads the absence there rather than from a sentinel. */
    public static List<Long> codePoints(String s) {
        List<Long> out = new ArrayList<>();
        s.codePoints().forEach(cp -> out.add((long) cp));
        return List.copyOf(out);
    }

    /** Parses {@code s} as a decimal {@code Int}, or {@link NotANumber#INSTANCE} when it is not one
     *  (Elm {@code String.toInt}, with a named case in place of {@code Maybe}). Returns a boxed
     *  {@code Long} or the {@code NotANumber} singleton — the {@code Int | NotANumber} union. */
    public static Object toInt(String s) {
        try {
            return Long.parseLong(s);
        } catch (NumberFormatException _) {
            return NotANumber.INSTANCE;
        }
    }

    /** The characters of {@code s} in the opposite order (Elm {@code String.reverse}). A surrogate
     *  pair stays a pair, so a character outside the basic plane survives the turn. */
    public static String reverse(String s) {
        return new StringBuilder(s).reverse().toString();
    }

    /** {@code n} copies of {@code s} joined (Elm {@code String.repeat}); {@code n} of 0 or less gives
     *  the empty string. A count no JVM string could hold aborts rather than quietly producing fewer
     *  copies than were asked for — an out-of-range count is a model bug, not a business result, and
     *  gets the same treatment {@link IntMath} gives an overflow. */
    public static String repeat(String s, long n) {
        if (n <= 0 || s.isEmpty()) {
            return "";
        }
        if (n > Integer.MAX_VALUE) {
            throw new ConstraintViolation("String.repeat count out of range: " + n);
        }
        return s.repeat((int) n);
    }

    /** Breaks {@code s} into lines (Elm {@code String.lines}): {@code \r\n} is normalised to
     *  {@code \n} first, then the string is split on {@code \n} keeping empty pieces — so a trailing
     *  newline leaves an empty last line, as it does in Elm. */
    public static List<String> lines(String s) {
        return split(s.replace("\r\n", "\n"), "\n");
    }

    /** {@code s} widened on the left to {@code width} code points with copies of {@code pad}. A
     *  string already that wide is returned unchanged, and an empty {@code pad} fills nothing, so it
     *  is returned unchanged too. */
    public static String padLeft(String s, long width, String pad) {
        String fill = padding(s, width, pad);
        return fill.isEmpty() ? s : fill + s;
    }

    /** {@code s} widened on the right, the mirror of {@link #padLeft}. */
    public static String padRight(String s, long width, String pad) {
        String fill = padding(s, width, pad);
        return fill.isEmpty() ? s : s + fill;
    }

    /** The filler that brings {@code s} up to exactly {@code width} code points: {@code pad}
     *  repeated and then cut to what is still needed, so a multi-code-point {@code pad} does not
     *  overshoot. Empty when nothing is needed or {@code pad} is, and an abort when the width is one
     *  no JVM string could reach — as {@link #repeat} does. */
    private static String padding(String s, long width, String pad) {
        long missing = width - length(s);
        if (missing <= 0 || pad.isEmpty()) {
            return "";
        }
        if (missing > Integer.MAX_VALUE) {
            throw new ConstraintViolation("String.pad width out of range: " + width);
        }
        long perCopy = length(pad);
        StringBuilder out = new StringBuilder();
        for (long have = 0; have < missing; have += perCopy) {
            out.append(pad);
        }
        return slice(out.toString(), 0, missing);
    }

    /** Renders a {@code Decimal} in plain notation, never in exponent form, keeping the scale the
     *  value carries ({@code fromDecimal(new BigDecimal("1000.00")) == "1000.00"}). */
    public static String fromDecimal(java.math.BigDecimal d) {
        return d.toPlainString();
    }

    /** Parses {@code s} as a {@code Decimal}, or {@link NotANumber#INSTANCE} when it is not one — the
     *  sibling of {@link #toInt}, returning the {@code Decimal | NotANumber} union. */
    public static Object toDecimal(String s) {
        try {
            return new java.math.BigDecimal(s);
        } catch (NumberFormatException _) {
            return NotANumber.INSTANCE;
        }
    }
}
