package souther.runtime;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Comparator;
import java.util.List;
import java.util.PrimitiveIterator;
import java.util.concurrent.ConcurrentHashMap;
import java.util.regex.Pattern;
import org.jspecify.annotations.Nullable;
import souther.unicode.Normalization;
import souther.unicode.ScalarValues;

/**
 * String helpers the generated bytecode calls (spec §stdlib-string). These back the {@code souther.string}
 * intrinsics that a single JVM {@code String} method does not already cover.
 *
 * <p>A {@code String} is a sequence of Unicode scalar values (spec §string-code-points): every code
 * point but the surrogates. A {@code java.lang.String} can hold more than that — half of a surrogate
 * pair on its own — so text that arrives from outside is let in by {@link #admit} or
 * {@link #admitted}, and everything here may take it that the text it is handed holds no such half.
 *
 * <p>Every length, index and range here counts code points, which is what the language publishes;
 * the UTF-16 code unit a JVM {@code String} stores is this class's business and reaches no signature
 * above it. The conversion is {@link String#codePointCount} on the way in and
 * {@link String#offsetByCodePoints} on the way back, so no result holds half a surrogate pair where
 * its input held none.
 */
public final class Strings {

    private Strings() {}

    /**
     * Text arriving from outside, as the {@code String} it is: canonicalized to NFC, or null where it
     * is not a sequence of scalar values at all.
     *
     * <p>The one way text becomes a value, whichever door it came through. The doors differ in how
     * they say no — a derived decoder with an issue at the path, a crossing from Java by aborting
     * ({@link #admit}), a source literal with a diagnostic — and not in what they refuse, so each of
     * them asks this and reads the null its own way.
     *
     * <p>Refused and not repaired. Replacing half a pair with U+FFFD would make text that held one
     * and text that held U+FFFD itself one value, which is the loss a key collision is refused for.
     */
    public static @Nullable String admitted(String text) {
        return halfAPairAt(text) < 0 ? Normalization.nfc(text) : null;
    }

    /** {@link #admitted}, aborting where the text is not a sequence of scalar values: what a
     *  crossing from Java answers, where the host handed over something that is not text. */
    public static String admit(String text) {
        String admitted = admitted(text);
        if (admitted == null) {
            throw new ConstraintViolation("text crossing into the domain holds half of a surrogate"
                    + " pair at UTF-16 index " + halfAPairAt(text) + ", which is not a character");
        }
        return admitted;
    }

    /** Where {@code text} holds a surrogate that is not one half of a pair beside the other, or -1
     *  where it holds none. */
    private static int halfAPairAt(String text) {
        for (int at = 0; at < text.length(); at++) {
            char unit = text.charAt(at);
            if (Character.isHighSurrogate(unit) && at + 1 < text.length()
                    && Character.isLowSurrogate(text.charAt(at + 1))) {
                at++;
            } else if (Character.isSurrogate(unit)) {
                return at;
            }
        }
        return -1;
    }

    /**
     * The language's order on text, lexicographic over scalar values ({@link ScalarValues}), as
     * generated code reaches it. Every place in a program that orders two {@code String}s the way a
     * model's {@code <} does asks this — the operator, a newtype's {@code compareTo}, the sort family
     * and the order a boundary writes in. Not {@link String#compareTo}, which orders UTF-16 code
     * units.
     */
    public static int compare(String a, String b) {
        return ScalarValues.compare(a, b);
    }

    /** {@link #compare} as a comparator, for the sort family's overloads that take one. */
    public static Comparator<Object> ordering() {
        return ORDERING;
    }

    private static final Comparator<Object> ORDERING = (a, b) -> compare((String) a, (String) b);

    /** String whitespace (spec §string-whitespace): the fixed 25-code-point set {@code trim} and
     *  {@code words} both scan by. The set is enumerated rather than read off a platform table, so
     *  a Unicode update in the JVM does not silently change what a Souther program means. */
    private static boolean isWhitespace(int cp) {
        return switch (cp) {
            case 0x0009, 0x000A, 0x000B, 0x000C, 0x000D,
                 0x0020,
                 0x0085,
                 0x00A0,
                 0x1680,
                 0x2028, 0x2029,
                 0x202F,
                 0x205F,
                 0x3000 -> true;
            default -> cp >= 0x2000 && cp <= 0x200A;
        };
    }

    /** The number of code points, as the Int the language carries. Counting them is a walk, so this
     *  is O(n) where the UTF-16 unit count would be a field read — the price of a length that agrees
     *  with {@link #characters} and cannot be half a character. */
    public static long length(String s) {
        return ScalarValues.count(s);
    }

    /** The UTF-16 offset of code point {@code index}, or an abort where the string has no such code
     *  point. Every index the language hands in comes through here, so an out-of-range one is
     *  reported the same way wherever it was written. */
    private static int offsetOf(String s, long index, String what) {
        if (index < 0 || index > length(s)) {
            throw new ConstraintViolation(what + " out of range: " + index);
        }
        return s.offsetByCodePoints(0, (int) index);
    }

    /** The code points of {@code s} from {@code fromInclusive} up to but not including
     *  {@code toExclusive}. Both are code-point indices, so a surrogate pair is never split. */
    public static String slice(String s, long fromInclusive, long toExclusive) {
        int from = offsetOf(s, fromInclusive, "String.slice fromInclusive");
        int to = offsetOf(s, toExclusive, "String.slice toExclusive");
        if (to < from) {
            throw new ConstraintViolation(
                    "String.slice toExclusive " + toExclusive + " is before fromInclusive "
                            + fromInclusive);
        }
        return s.substring(from, to);
    }

    /** Splits on a literal separator, keeping empty pieces (Elm {@code String.split} semantics):
     *  {@code split("a,,b", ",") == ["a", "", "b"]}. An empty separator yields the whole string. */
    public static List<String> split(String s, String sep) {
        if (sep.isEmpty()) {
            return List.of(s);
        }
        List<String> out = new ArrayList<>();
        int from = 0;
        while (true) {
            int at = s.indexOf(sep, from);
            if (at < 0) {
                out.add(s.substring(from));
                break;
            }
            out.add(s.substring(from, at));
            from = at + sep.length();
        }
        return List.copyOf(out);
    }

    /** Joins two strings in their written order (Elm {@code String.append}; the {@code ++} operator
     *  is the common form). Canonicalized: {@code a} and {@code b} each arrive NFC, but NFC is not
     *  closed under concatenation — a base letter followed by a combining mark composes into one
     *  code point, not two — so the join has to canonicalize again at the seam. */
    public static String append(String a, String b) {
        return Normalization.nfc(a + b);
    }

    /** Joins with a separator ({@code join(["a", "b"], "-") == "a-b"}). Canonicalized for the same
     *  reason {@link #append} is: a seam {@code sep} introduces is exactly as capable of leaving NFC
     *  as one {@code append} makes. */
    public static String join(List<String> xs, String sep) {
        return Normalization.nfc(String.join(sep, xs));
    }

    /** Joins a list of strings with no separator (Elm {@code String.concat}):
     *  {@code concat(["a", "b", "c"]) == "abc"}. This is {@code join(xs, "")}, canonicalized there. */
    public static String concat(List<String> xs) {
        return join(xs, "");
    }

    /** Replaces every literal occurrence of {@code target} (Elm {@code String.replace}). An empty
     *  {@code target} leaves the string unchanged rather than splicing between every character.
     *  Canonicalized: a {@code replacement} introduces the same seam {@link #append} does. */
    public static String replace(String s, String target, String replacement) {
        if (target.isEmpty()) {
            return s;
        }
        return Normalization.nfc(s.replace(target, replacement));
    }

    /** Renders an integer as its decimal string ({@code fromInt(42) == "42"}). */
    public static String fromInt(long n) {
        return Long.toString(n);
    }

    /** Removes a maximal run of String whitespace (spec §string-whitespace) from each end,
     *  leaving the rest untouched: {@code trim("　a　") == "a"}. Scans code points, so a
     *  character outside the whitespace set — including one JDK's own {@code String.trim} would
     *  have stripped — stops the run rather than being crossed. */
    public static String trim(String s) {
        int start = 0;
        int end = s.length();
        while (start < end) {
            int cp = s.codePointAt(start);
            if (!isWhitespace(cp)) {
                break;
            }
            start += Character.charCount(cp);
        }
        while (end > start) {
            int cp = s.codePointBefore(end);
            if (!isWhitespace(cp)) {
                break;
            }
            end -= Character.charCount(cp);
        }
        return s.substring(start, end);
    }

    /** Splits on runs of String whitespace (spec §string-whitespace), dropping empty pieces (Elm
     *  {@code String.words}): {@code words("  a  b ") == ["a", "b"]}. The same predicate
     *  {@link #trim} uses, scanned by code point rather than by a regex class, so a run of
     *  whitespace this splits on is a run {@link #trim} would remove at either end. */
    public static List<String> words(String s) {
        List<String> out = new ArrayList<>();
        StringBuilder word = new StringBuilder();
        PrimitiveIterator.OfInt it = s.codePoints().iterator();
        while (it.hasNext()) {
            int cp = it.nextInt();
            if (isWhitespace(cp)) {
                if (!word.isEmpty()) {
                    out.add(word.toString());
                    word.setLength(0);
                }
            } else {
                word.appendCodePoint(cp);
            }
        }
        if (!word.isEmpty()) {
            out.add(word.toString());
        }
        return List.copyOf(out);
    }

    /** Compiled patterns, cached by source so {@link #matches} does not recompile per call. The
     *  compiler requires {@code String.matches}'s pattern to be a literal, so the keys are the pattern
     *  literals of the programs loaded here — bounded by source, not by runtime input, and never
     *  evicted. */
    private static final ConcurrentHashMap<String, Pattern> PATTERNS = new ConcurrentHashMap<>();

    /** Whether the whole string matches the regex (anchored, like {@code Pattern.matches}). Backs
     *  {@code String.matches} for format-constrained values. The pattern is a compile-time-validated
     *  literal, so {@link Pattern#compile} here cannot fail. */
    public static boolean matches(String s, String pattern) {
        return PATTERNS.computeIfAbsent(pattern, Pattern::compile).matcher(s).matches();
    }

    /** The characters of {@code s}, one per Unicode code point
     *  ({@code characters("a12") == ["a", "1", "2"]}). Souther has no {@code Char}, so a character is
     *  a one-code-point {@code String}; this is what a {@code List.fold} over characters iterates. */
    public static List<String> characters(String s) {
        List<String> out = new ArrayList<>();
        s.codePoints().forEach(cp -> out.add(new String(Character.toChars(cp))));
        return List.copyOf(out);
    }

    /** The same split as {@link #characters}, as the code points themselves. Total: the empty string
     *  gives the empty list, so a caller wanting the first one takes it through {@code List.get} and
     *  reads the absence there rather than from a sentinel. */
    public static List<Long> codePoints(String s) {
        List<Long> out = new ArrayList<>();
        s.codePoints().forEach(cp -> out.add((long) cp));
        return List.copyOf(out);
    }

    /** Parses {@code s} as a decimal {@code Int}, or {@link NotANumber#INSTANCE} when it is not one
     *  (Elm {@code String.toInt}, with a named case in place of {@code Maybe}). Returns a boxed
     *  {@code Long} or the {@code NotANumber} singleton — the {@code Int | NotANumber} union. */
    public static Object toInt(String s) {
        try {
            return Long.parseLong(s);
        } catch (NumberFormatException _) {
            return NotANumber.INSTANCE;
        }
    }

    /** The code points of {@code s} in the opposite order, canonicalized (Elm {@code String.reverse}).
     *  The exact code-point permutation is no longer a law this holds: reversing can put a combining
     *  mark right after a base character it now composes with, giving one code point where reversing
     *  the code points themselves would have given two. A caller that wants the exact permutation
     *  writes {@code String.codePoints(s) |> List.reverse} instead — a {@code List<Int>}, not a
     *  {@code String}, is under no canonical-form obligation. */
    public static String reverse(String s) {
        return Normalization.nfc(new StringBuilder(s).reverse().toString());
    }

    /** {@code n} copies of {@code s} joined (Elm {@code String.repeat}); {@code n} of 0 or less gives
     *  the empty string. A count no JVM string could hold aborts rather than quietly producing fewer
     *  copies than were asked for — an out-of-range count is a model bug, not a business result, and
     *  gets the same treatment {@link IntMath} gives an overflow. Canonicalized: the seam between one
     *  copy and the next is exactly {@link #append}'s seam, repeated. */
    public static String repeat(String s, long n) {
        if (n <= 0 || s.isEmpty()) {
            return "";
        }
        if (n > Integer.MAX_VALUE) {
            throw new ConstraintViolation("String.repeat count out of range: " + n);
        }
        return Normalization.nfc(s.repeat((int) n));
    }

    /** Breaks {@code s} into lines (Elm {@code String.lines}): {@code \r\n} is normalised to
     *  {@code \n} first, then the string is split on {@code \n} keeping empty pieces — so a trailing
     *  newline leaves an empty last line, as it does in Elm. */
    public static List<String> lines(String s) {
        return split(s.replace("\r\n", "\n"), "\n");
    }

    /** {@code s} widened on the left to {@code width} code points with copies of {@code pad}. A
     *  string already that wide is returned unchanged, and an empty {@code pad} fills nothing, so it
     *  is returned unchanged too. */
    public static String padLeft(String s, long width, String pad) {
        return pad(s, width, pad, true);
    }

    /** {@code s} widened on the right, the mirror of {@link #padLeft}. */
    public static String padRight(String s, long width, String pad) {
        return pad(s, width, pad, false);
    }

    /** Widens {@code s} to exactly {@code width} code points with copies of {@code pad} — on the
     *  left when {@code atStart}, on the right otherwise. Already wide enough is left alone.
     *
     * <p>The fill is {@code pad} repeated a whole number of times (at least enough to cover what is
     * needed), canonicalized once, and cut to the code points still needed from its own front (so a
     * multi-code-point {@code pad} does not overshoot) — then joined to {@code s} and canonicalized
     * once more at that seam.
     *
     * <p>The seam is why the fill's own length is not the last word: composing where copies of
     * {@code pad} meet each other, or where the fill meets {@code s}, can absorb a code point
     * neither side had on its own — a {@code pad} that is a bare combining mark can compose straight
     * into {@code s}'s first character. So on the rare occasion the join comes up short, one more
     * code point is asked for and the whole fill is rebuilt — never grown one copy of {@code pad} at
     * a time with a fresh canonicalization each time, which would canonicalize the same leading code
     * points as many times as there are copies of {@code pad} still to add. */
    private static String pad(String s, long width, String pad, boolean atStart) {
        if (pad.isEmpty() || length(s) >= width) {
            return s;
        }
        if (width > Integer.MAX_VALUE) {
            throw new ConstraintViolation("String.pad width out of range: " + width);
        }
        long padLength = length(pad);
        long need = width - length(s);
        while (true) {
            long copies = (need + padLength - 1) / padLength;
            String fill = Normalization.nfc(pad.repeat((int) copies));
            String trimmedFill = length(fill) > need ? slice(fill, 0, need) : fill;
            String joined = Normalization.nfc(atStart ? trimmedFill + s : s + trimmedFill);
            if (length(joined) >= width) {
                return joined;
            }
            need++;
        }
    }

    /** Renders a {@code Decimal} in plain notation, never in exponent form, keeping the scale the
     *  value carries ({@code fromDecimal(new BigDecimal("1000.00")) == "1000.00"}). */
    public static String fromDecimal(java.math.BigDecimal d) {
        return d.toPlainString();
    }

    /** Parses {@code s} as a {@code Decimal}, or {@link NotANumber#INSTANCE} when it is not one — the
     *  sibling of {@link #toInt}, returning the {@code Decimal | NotANumber} union. */
    public static Object toDecimal(String s) {
        try {
            return new java.math.BigDecimal(s);
        } catch (NumberFormatException _) {
            return NotANumber.INSTANCE;
        }
    }

    /** Unicode 18.0.0 default case conversion (spec §stdlib-string, ADR-0119), lowercased, with no
     *  locale or language tailoring: {@code lowercase("STRASSE") == "strasse"}. A Greek capital
     *  sigma becomes the context-dependent final form only at the end of a cased run —
     *  {@code lowercase("ΟΣ") == "ος"} but {@code lowercase("ΟΣΑ") == "οσα"} — which is the one
     *  condition Unicode's default algorithm carries that is context rather than locale.
     *  Canonicalized: case mapping is not closed under NFC either. */
    public static String lowercase(String s) {
        return Normalization.nfc(mapCase(s, true));
    }

    /** The uppercase half of {@link #lowercase}: the same untailored Unicode 18.0.0 full mapping, so
     *  one code point can widen to several ({@code uppercase("straße") == "STRASSE"}), and no locale
     *  narrows it back — Turkish {@code i} still becomes {@code I}, never {@code İ}. */
    public static String uppercase(String s) {
        return Normalization.nfc(mapCase(s, false));
    }

    private static String mapCase(String s, boolean lower) {
        int[] cps = s.codePoints().toArray();
        StringBuilder out = new StringBuilder(cps.length);
        for (int i = 0; i < cps.length; i++) {
            int cp = cps[i];
            if (lower) {
                int[] finalSigmaMapped = lookup(CaseTables.FINAL_SIGMA, cp);
                if (finalSigmaMapped != null && isFinalSigmaContext(cps, i)) {
                    for (int m : finalSigmaMapped) {
                        out.appendCodePoint(m);
                    }
                    continue;
                }
            }
            int[] mapped = lookup(lower ? CaseTables.LOWER : CaseTables.UPPER, cp);
            if (mapped == null) {
                out.appendCodePoint(cp);
            } else {
                for (int m : mapped) {
                    out.appendCodePoint(m);
                }
            }
        }
        return out.toString();
    }

    /** Unicode's {@code Final_Sigma} condition: immediately preceded, skipping {@code Case_Ignorable}
     *  code points, by a {@code Cased} one, and NOT immediately followed, skipping the same way, by
     *  another {@code Cased} one. Scanned over the whole string's code points rather than a window,
     *  since what "immediately" skips over is itself defined by the property, not by a fixed count. */
    private static boolean isFinalSigmaContext(int[] cps, int at) {
        boolean precededByCased = false;
        for (int j = at - 1; j >= 0; j--) {
            if (isCaseIgnorable(cps[j])) {
                continue;
            }
            precededByCased = isCased(cps[j]);
            break;
        }
        if (!precededByCased) {
            return false;
        }
        for (int j = at + 1; j < cps.length; j++) {
            if (isCaseIgnorable(cps[j])) {
                continue;
            }
            return !isCased(cps[j]);
        }
        return true;
    }

    private static int @Nullable [] lookup(CaseTables.Mapping table, int cp) {
        int index = Arrays.binarySearch(table.codePoints(), cp);
        return index >= 0 ? table.mapped()[index] : null;
    }

    private static boolean isCased(int cp) {
        return inRanges(CaseTables.CASED, cp);
    }

    private static boolean isCaseIgnorable(int cp) {
        return inRanges(CaseTables.CASE_IGNORABLE, cp);
    }

    private static boolean inRanges(int[][] startsAndEnds, int cp) {
        int[] starts = startsAndEnds[0];
        int[] ends = startsAndEnds[1];
        int index = Arrays.binarySearch(starts, cp);
        if (index < 0) {
            index = -index - 2;
        }
        return index >= 0 && cp <= ends[index];
    }
}
