package souther.runtime;

import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.ConcurrentHashMap;
import java.util.regex.Pattern;

/** String helpers the generated bytecode calls (spec 18.1). These back the {@code souther.string}
 *  intrinsics that a single JVM {@code String} method does not already cover. */
public final class Strings {

    /** Runs of whitespace, for {@link #words} — compiled once rather than per call. */
    private static final Pattern WHITESPACE = Pattern.compile("\\s+");

    private Strings() {}

    /** Splits on a literal separator, keeping empty pieces (Elm {@code String.split} semantics):
     *  {@code split("a,,b", ",") == ["a", "", "b"]}. An empty separator yields the whole string. */
    public static List<String> split(String s, String sep) {
        if (sep.isEmpty()) {
            return List.of(s);
        }
        List<String> out = new ArrayList<>();
        int from = 0;
        while (true) {
            int at = s.indexOf(sep, from);
            if (at < 0) {
                out.add(s.substring(from));
                break;
            }
            out.add(s.substring(from, at));
            from = at + sep.length();
        }
        return List.copyOf(out);
    }

    /** Joins with a separator ({@code join(["a", "b"], "-") == "a-b"}). */
    public static String join(List<String> xs, String sep) {
        return String.join(sep, xs);
    }

    /** Joins a list of strings with no separator (Elm {@code String.concat}):
     *  {@code concat(["a", "b", "c"]) == "abc"}. This is {@code join(xs, "")}. */
    public static String concat(List<String> xs) {
        return join(xs, "");
    }

    /** Replaces every literal occurrence of {@code target} (Elm {@code String.replace}). An empty
     *  {@code target} leaves the string unchanged rather than splicing between every character. */
    public static String replace(String s, String target, String replacement) {
        if (target.isEmpty()) {
            return s;
        }
        return s.replace(target, replacement);
    }

    /** Renders an integer as its decimal string ({@code fromInt(42) == "42"}). */
    public static String fromInt(long n) {
        return Long.toString(n);
    }

    /** Splits on runs of whitespace, dropping empty pieces (Elm {@code String.words}):
     *  {@code words("  a  b ") == ["a", "b"]}. */
    public static List<String> words(String s) {
        List<String> out = new ArrayList<>();
        for (String w : WHITESPACE.split(s)) {
            if (!w.isEmpty()) {
                out.add(w);
            }
        }
        return List.copyOf(out);
    }

    /** Compiled patterns, cached by source so {@link #matches} does not recompile per call. The
     *  compiler requires {@code String.matches}'s pattern to be a literal, so the keys are the pattern
     *  literals of the programs loaded here — bounded by source, not by runtime input, and never
     *  evicted. */
    private static final ConcurrentHashMap<String, Pattern> PATTERNS = new ConcurrentHashMap<>();

    /** Whether the whole string matches the regex (anchored, like {@code Pattern.matches}). Backs
     *  {@code String.matches} for format-constrained values. The pattern is a compile-time-validated
     *  literal, so {@link Pattern#compile} here cannot fail. */
    public static boolean matches(String s, String pattern) {
        return PATTERNS.computeIfAbsent(pattern, Pattern::compile).matcher(s).matches();
    }

    /** The characters of {@code s} as single-character strings, one per Unicode code point
     *  ({@code toChars("a12") == ["a", "1", "2"]}). Souther has no {@code Char}, so a character is a
     *  length-1 {@code String}; this is what a {@code List.fold} over characters iterates. */
    public static List<String> toChars(String s) {
        List<String> out = new ArrayList<>();
        s.codePoints().forEach(cp -> out.add(new String(Character.toChars(cp))));
        return List.copyOf(out);
    }

    /** The Unicode code point of the first character of {@code s} (Elm {@code Char.toCode} on a
     *  length-1 string), or {@code -1} for the empty string. A digit's value is {@code toCode(ch) -
     *  toCode("0")}. */
    public static long toCode(String s) {
        return s.isEmpty() ? -1 : s.codePointAt(0);
    }

    /** Parses {@code s} as a decimal {@code Int}, or {@link NotANumber#INSTANCE} when it is not one
     *  (Elm {@code String.toInt}, with a named case in place of {@code Maybe}). Returns a boxed
     *  {@code Long} or the {@code NotANumber} singleton — the {@code Int | NotANumber} union. */
    public static Object toInt(String s) {
        try {
            return Long.parseLong(s);
        } catch (NumberFormatException e) {
            return NotANumber.INSTANCE;
        }
    }
}
