package souther.runtime;

import java.time.DateTimeException;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.time.temporal.ChronoUnit;

/** Temporal helpers the generated bytecode calls: the calendar shifts, the whole-unit "between"
 *  operations ({@code Date.daysBetween}, {@code DateTime.minutesBetween}), reading a temporal's
 *  parts and building one from them, and the two predicates a derived decoder refines a temporal by.
 *  The part readers are here because {@code LocalDate} answers in {@code int} and a Souther
 *  {@code Int} is a {@code long}; the shifts because {@code java.time} refuses off the end of its
 *  range by throwing its own exceptions, which have no place at a Souther boundary. All arithmetic
 *  is on local values; the zone is the boundary's concern (spec {@code [#primitives]}). */
public final class Temporals {

    private Temporals() {}

    /**
     * Calendar arithmetic, each shift run off the end of what its temporal can hold reported the way
     * an {@code Int} overflow is (spec {@code [#jvm-abort]}).
     *
     * <p>These called {@code java.time} directly and needed no helper until it was asked what happens
     * at the end of the range. {@code LocalDate.plusYears} raises a {@code DateTimeException} past
     * year 999999999 and {@code plusDays} an {@code ArithmeticException} past what a day count holds,
     * and both went out to the boundary as themselves — a {@code java.time} class named in the
     * failure of a program that has no such type. Running out of range is the same kind of thing as
     * an {@code Int} overflow: not a business result, and not the infrastructure being unavailable
     * either (ADR-0029), so it aborts and says what it was doing.
     *
     * <p>Runs {@code shift} and turns either way {@code java.time} refuses into that abort.
     */
    private static <T> T aborting(java.util.function.Supplier<T> shift, String what) {
        try {
            return shift.get();
        } catch (DateTimeException | ArithmeticException _) {
            throw new ConstraintViolation(what + " is outside the range it can hold");
        }
    }

    public static LocalDate addDays(LocalDate d, long days) {
        return aborting(() -> d.plusDays(days), d + " + " + days + " days");
    }

    public static LocalDate addMonths(LocalDate d, long months) {
        return aborting(() -> d.plusMonths(months), d + " + " + months + " months");
    }

    public static LocalDate addYears(LocalDate d, long years) {
        return aborting(() -> d.plusYears(years), d + " + " + years + " years");
    }

    public static LocalDateTime addMinutes(LocalDateTime dt, long minutes) {
        return aborting(() -> dt.plusMinutes(minutes), dt + " + " + minutes + " minutes");
    }

    public static LocalDateTime addHours(LocalDateTime dt, long hours) {
        return aborting(() -> dt.plusHours(hours), dt + " + " + hours + " hours");
    }

    public static LocalDateTime addDateTimeDays(LocalDateTime dt, long days) {
        return aborting(() -> dt.plusDays(days), dt + " + " + days + " days");
    }

    /** Whole days from {@code from} to {@code to}, negative when {@code to} precedes {@code from}. */
    public static long daysBetween(LocalDate from, LocalDate to) {
        return ChronoUnit.DAYS.between(from, to);
    }

    /** Whole minutes from {@code from} to {@code to}, negative when {@code to} precedes {@code from}. */
    public static long minutesBetween(LocalDateTime from, LocalDateTime to) {
        return ChronoUnit.MINUTES.between(from, to);
    }

    /** The proleptic year. */
    public static long year(LocalDate d) {
        return d.getYear();
    }

    /** The month of the year, 1 (January) to 12 (December) — a number, as .NET's
     *  {@code DateTime.Month} is, because {@code Date.addMonths} already counts in months and a
     *  named month would have to be converted back to add one. */
    public static long month(LocalDate d) {
        return d.getMonthValue();
    }

    /** The day of the month, 1 to 31. */
    public static long day(LocalDate d) {
        return d.getDayOfMonth();
    }

    /**
     * The date {@code year}-{@code month}-{@code day} names, or {@link NotADate#INSTANCE} where they
     * name none — the returned {@code Date | NotADate}.
     *
     * <p>Both ways of naming none are the one case: a combination the calendar does not have
     * (February the 30th, month 13) and a year outside what a date can hold. {@code LocalDate.of}
     * refuses each with a {@code DateTimeException}, and a value handed in that does not fit an
     * {@code int} cannot be a field of a date either, so the narrowing is part of the same question.
     *
     * <p>Nothing is normalised. A caller that wanted the day after the 28th of February asks the
     * arithmetic for it; this one is asked whether three numbers name a day, and answers.
     */
    public static Object fromDateParts(long year, long month, long day) {
        try {
            return LocalDate.of(Math.toIntExact(year), Math.toIntExact(month), Math.toIntExact(day));
        } catch (DateTimeException | ArithmeticException _) {
            return NotADate.INSTANCE;
        }
    }

    /** The time of day {@code hour}:{@code minute}:{@code second} names, or {@link NotATime#INSTANCE}
     *  where they name none — hour 24, minute 60, the leap second. The sibling of
     *  {@link #fromDateParts}, and partial for the same reason. */
    public static Object fromTimeParts(long hour, long minute, long second) {
        try {
            return LocalTime.of(Math.toIntExact(hour), Math.toIntExact(minute), Math.toIntExact(second));
        } catch (DateTimeException | ArithmeticException _) {
            return NotATime.INSTANCE;
        }
    }

    /** The hour of the day, 0 to 23. */
    public static long hour(LocalTime t) {
        return t.getHour();
    }

    /** The minute of the hour, 0 to 59. */
    public static long minute(LocalTime t) {
        return t.getMinute();
    }

    /** The second of the minute, 0 to 59. A {@code Time} holds no fraction of one
     *  (spec {@code [#temporal-literal]}), so this is the whole of what is left to read. */
    public static long second(LocalTime t) {
        return t.getSecond();
    }

    /**
     * Whether a decoded temporal carries no fraction of a second — the predicate the generated
     * decoder refines a {@code Time} and a {@code DateTime} by.
     *
     * <p>Text arriving with one says something those two cannot hold, and the boundary reports that
     * rather than dropping it: a value quietly rounded reads downstream as the value that was sent,
     * and nothing later can tell that it was not. An {@code Instant} is the temporal that keeps a
     * sub-second reading, so it is not refined and answers true here.
     */
    public static boolean toTheSecond(Object temporal) {
        return switch (temporal) {
            case LocalTime t -> t.getNano() == 0;
            case LocalDateTime d -> d.getNano() == 0;
            default -> true;
        };
    }

    /**
     * Whether written text names a second that exists — the predicate the generated decoder refines
     * an {@code Instant}'s text by, before it is parsed.
     *
     * <p>A leap second has to be caught here and not after. {@code Instant.parse} takes
     * {@code 23:59:60} and answers {@code 23:59:59}, so by the time there is an {@code Instant} the
     * two are the same value and nothing downstream can tell that the text said the other one. That
     * is the substitution this type exists not to make: an {@code Instant} carries what an outside
     * timestamp said, and a moment the language cannot represent is refused rather than moved.
     *
     * <p>Only a leap second is refused (spec {@code [#a-leap-second-is-no-moment]}). An offset is a
     * different spelling of the same moment and is taken; text that is no instant at all answers true
     * here and is refused by the parse, which says so better than this could.
     */
    public static boolean notALeapSecond(Object text) {
        if (!(text instanceof String s)) {
            return true;
        }
        try {
            return !Boolean.TRUE.equals(DateTimeFormatter.ISO_INSTANT.parse(s)
                    .query(DateTimeFormatter.parsedLeapSecond()));
        } catch (DateTimeParseException _) {
            return true;
        }
    }
}
