package souther.runtime;

import org.jspecify.annotations.Nullable;

/**
 * Several values carried together through a computation (ADR-0036). A tuple has no external form, so
 * it is never a data field or a behavior's input or output; within a computation it is a value like
 * any other and compares by its elements, so two built separately from the same values are one
 * value. That is what lets a tuple be a {@code Set}'s element and a {@code Map}'s key, which is how
 * a composite uniqueness rule — one row per {@code (from, event)} — is written.
 *
 * <p>Its {@code equals} and {@code hashCode} are the language's directly rather than through
 * {@link ValueSemantics}: a tuple implements no JDK collection interface, so it is only ever
 * compared with another tuple and has no foreign implementation to keep a contract with.
 *
 * <p>A pair has a class of its own, and this is an interface rather than a base class so that its
 * constructor chains straight to {@code Object}'s. Every combinator that folds a tuple accumulator
 * folds a pair — {@code partition} carries {@code (kept, rest)}, {@code take} and {@code drop} and
 * {@code indexedMap} carry {@code (index, out)}, {@code distinct} carries {@code (seen, out)} — so
 * one is built per element of those walks, and the generated code names {@link Pair} outright and
 * reads its fields rather than calling {@link #get}. Wider tuples are rare and carry an array.
 *
 * <p>That construction is what a tuple costs. A pair is the same size as the two-element array it
 * replaced and allocates no more often — measured, the GC runs the same number of times — but
 * building it is a call where an array was an instruction, and an inlined call spends the caller's
 * inlining budget. In the walks above that budget is what {@code PersistentVector.append} was being
 * inlined on, and it no longer is: those six combinators cost about 9% more per element than an
 * array-carried tuple did. Nothing else moved. A value that answers what it is, is worth that;
 * without it a tuple compares by identity, and a rule written over one holds of nothing.
 *
 * <p>A tuple is immutable, which is what a Set element and a Map key require: one whose elements
 * could be written to afterwards would leave a container indexed by a hash it no longer has.
 * {@link #of} copies the array it is given, so a Java caller keeps nothing that can change it.
 * {@link #ofOwned} is what the generated bytecode calls, and takes ownership instead — it hands over
 * an array built one instruction earlier that nothing else holds.
 */
public sealed interface Tuple {

    /** A pair, the arity every fold-carried tuple has. */
    static Tuple of(Object first, Object second) {
        return new Pair(first, second);
    }

    /** A tuple over {@code elements}. The array is copied, so a caller that keeps its own reference
     *  cannot change what the tuple is afterwards — a tuple is a Set element and a Map key, and one
     *  whose elements could be written to would leave a container indexed by a hash it no longer
     *  has. Souther's own construction is {@link #ofOwned}, which does not copy. */
    static Tuple of(Object... elements) {
        return ofOwned(elements.clone());
    }

    /** A tuple over {@code elements}, taking ownership of the array rather than copying it. This is
     *  what the generated bytecode calls: it hands over an array built one instruction earlier that
     *  nothing else holds. A caller that keeps a reference to what it passes MUST NOT write to it
     *  afterwards, and {@link #of} is the form that asks nothing of the caller. */
    static Tuple ofOwned(Object... elements) {
        return elements.length == 2 ? new Pair(elements[0], elements[1]) : new Wide(elements);
    }

    Object get(int index);

    int size();

    /** Whether {@code a} and {@code b} are the same tuple; what each arm's {@code equals} answers. */
    static boolean same(Tuple a, @Nullable Object b) {
        if (a == b) {
            return true;
        }
        if (!(b instanceof Tuple other) || other.size() != a.size()) {
            return false;
        }
        for (int i = 0; i < a.size(); i++) {
            if (!Values.equal(a.get(i), other.get(i))) {
                return false;
            }
        }
        return true;
    }

    /** The hash that agrees with {@link #same}. */
    static int hashOf(Tuple t) {
        int h = 1;
        for (int i = 0; i < t.size(); i++) {
            h = 31 * h + Values.hash(t.get(i));
        }
        return h;
    }

    /** The surface form, {@code (a, b)}. */
    static String show(Tuple t) {
        StringBuilder sb = new StringBuilder("(");
        for (int i = 0; i < t.size(); i++) {
            if (i > 0) {
                sb.append(", ");
            }
            sb.append(t.get(i));
        }
        return sb.append(')').toString();
    }

    /** The pair a fold carries. Public and its fields with it: the generated bytecode types a
     *  two-element tuple as this and reads {@code first}/{@code second} outright, so the walk that
     *  builds one per element neither calls through {@link Tuple#get} nor indexes an array. */
    final class Pair implements Tuple {

        public final Object first;
        public final Object second;

        public Pair(Object first, Object second) {
            this.first = first;
            this.second = second;
        }

        @Override
        public Object get(int index) {
            return switch (index) {
                case 0 -> first;
                case 1 -> second;
                default -> throw new IndexOutOfBoundsException(index);
            };
        }

        @Override
        public int size() {
            return 2;
        }

        @Override
        public boolean equals(@Nullable Object o) {
            return same(this, o);
        }

        @Override
        public int hashCode() {
            return hashOf(this);
        }

        @Override
        public String toString() {
            return show(this);
        }
    }

    /** A tuple of three or more, which no combinator folds and a model writes by hand. */
    final class Wide implements Tuple {

        private final Object[] elements;

        Wide(Object[] elements) {
            this.elements = elements;
        }

        @Override
        public Object get(int index) {
            return elements[index];
        }

        @Override
        public int size() {
            return elements.length;
        }

        @Override
        public boolean equals(@Nullable Object o) {
            return same(this, o);
        }

        @Override
        public int hashCode() {
            return hashOf(this);
        }

        @Override
        public String toString() {
            return show(this);
        }
    }
}
