package souther.runtime;

import java.math.BigDecimal;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * Whether two Souther values are the same one, and the hash that agrees with it. This is the one
 * definition: a collection, a generated class and the generated bytecode all reach it rather than
 * writing the rule again.
 *
 * <p>Most values answer for themselves. A String, a Long, a Boolean, a LocalDate, a generated data
 * class — their own {@code equals} already is the language's equality, so this asks them. Two kinds
 * cannot. A {@code BigDecimal}'s {@code equals} calls 1.0 and 1.00 different, and the same amount
 * arrives with a different scale depending on whether it was read from JSON or from a DB column; the
 * rule that scale is not part of a Decimal's identity lives here. A container's {@code equals} asks
 * its elements theirs, so an amount inside one is compared by a rule that is not the language's.
 *
 * <p>A container is reached one of two ways. One Souther built implements {@link ValueSemantics} and
 * is asked directly. One that arrived otherwise — a list literal is a {@code List.copyOf}, a decoded
 * map is a {@code LinkedHashMap} — is walked here by the interface it implements. Both routes give
 * the same answer and the same hash; the first is there because it is the one taken in a loop, not
 * because the second is a special case.
 *
 * <p>Equality ignoring scale forces the hash to ignore it too. A value that compares equal and
 * hashes differently lands in another bucket and stops being findable by its own key — Groovy
 * changed {@code ==} and left {@code hashCode} alone, and that bug is still open.
 *
 * <p>The {@code BigDecimal} overloads are what the generated bytecode calls where both operands are
 * statically a Decimal. They share the body with the general form, so there is one rule, not two.
 *
 * <p>The arms are ordered, and {@code Long} and {@code String} lead because a Map is keyed by them
 * and a List holds them in the walks that decide how the runtime performs. An arm placed there is
 * one whose equality is then never inspected, so a carrier whose own equality is not the language's
 * — {@code BigDecimal} is the one there is — MUST NOT be moved ahead of its own arm.
 */
public final class Values {

    private Values() {}

    public static boolean equal(Object a, Object b) {
        if (a == b) {
            return true;
        }
        if (b == null) {
            return false;
        }
        return switch (a) {
            case null -> false;
            case Long l -> l.equals(b);
            case String s -> s.equals(b);
            case BigDecimal x -> b instanceof BigDecimal y && equal(x, y);
            case ValueSemantics s -> s.valueEquals(b);
            // a foreign container on the left and one of ours on the right: ours knows how to be
            // asked, so it is, rather than walking the foreign one against it
            case List<?> xs -> b instanceof ValueSemantics s ? s.valueEquals(xs)
                    : b instanceof List<?> ys && equalLists(xs, ys);
            case Set<?> xs -> b instanceof ValueSemantics s ? s.valueEquals(xs)
                    : b instanceof Set<?> ys && equalSets(xs, ys);
            case Map<?, ?> xs -> b instanceof ValueSemantics s ? s.valueEquals(xs)
                    : b instanceof Map<?, ?> ys && equalMaps(xs, ys);
            default -> a.equals(b);
        };
    }

    /** Two amounts are the same amount when they differ only in scale. */
    public static boolean equal(BigDecimal a, BigDecimal b) {
        return a == null ? b == null : b != null && a.compareTo(b) == 0;
    }

    public static int hash(Object v) {
        return switch (v) {
            case null -> 0;
            case Long l -> l.hashCode();
            case String s -> s.hashCode();
            case BigDecimal d -> hash(d);
            case ValueSemantics s -> s.valueHash();
            case List<?> xs -> {
                int h = 1;                 // the formula PersistentVector.valueHash uses, so a list
                for (Object e : xs) {      // lands in one bucket whichever implementation carries it
                    h = 31 * h + hash(e);
                }
                yield h;
            }
            case Set<?> xs -> {
                int h = 0;                 // summed: a set is unordered
                for (Object e : xs) {
                    h += hash(e);
                }
                yield h;
            }
            case Map<?, ?> m -> {
                int h = 0;
                for (Map.Entry<?, ?> e : m.entrySet()) {
                    h += hash(e.getKey()) ^ hash(e.getValue());
                }
                yield h;
            }
            default -> v.hashCode();
        };
    }

    /** The hash of an amount, taken after dropping the scale its equality ignores. */
    public static int hash(BigDecimal v) {
        return v == null ? 0 : v.stripTrailingZeros().hashCode();
    }

    /**
     * Whether a carrier's own {@code hashCode} is already the one {@link #hash} would give, decided
     * by the exact class so the check is a load and a compare.
     *
     * <p>It is here for the trie a Map is indexed by, which calls that {@code hashCode} from its own
     * site rather than through this class: routed through {@link #hash}, the one call there would see
     * every key type in the program and go megamorphic. The carriers are the same ones {@link #hash}
     * leads with, and for the same reason.
     */
    static boolean answersForItself(Class<?> carrier) {
        return carrier == Long.class || carrier == String.class;
    }

    private static boolean equalLists(List<?> a, List<?> b) {
        if (a.size() != b.size()) {
            return false;
        }
        Iterator<?> xs = a.iterator();
        Iterator<?> ys = b.iterator();
        while (xs.hasNext()) {
            if (!equal(xs.next(), ys.next())) {
                return false;
            }
        }
        return true;
    }

    /** A scan per element, because a foreign set is indexed by its elements' own hashes and cannot be
     *  asked where one of ours would be. One of ours answers through {@link ValueSemantics} and never
     *  reaches here. */
    private static boolean equalSets(Set<?> a, Set<?> b) {
        if (a.size() != b.size()) {
            return false;
        }
        for (Object x : a) {
            boolean found = false;
            for (Object y : b) {
                if (equal(x, y)) {
                    found = true;
                    break;
                }
            }
            if (!found) {
                return false;
            }
        }
        return true;
    }

    private static boolean equalMaps(Map<?, ?> a, Map<?, ?> b) {
        if (a.size() != b.size()) {
            return false;
        }
        for (Map.Entry<?, ?> e : a.entrySet()) {
            boolean found = false;
            for (Map.Entry<?, ?> f : b.entrySet()) {
                if (equal(e.getKey(), f.getKey())) {
                    if (!equal(e.getValue(), f.getValue())) {
                        return false;
                    }
                    found = true;
                    break;
                }
            }
            if (!found) {
                return false;
            }
        }
        return true;
    }
}
