package souther.runtime;

import java.math.BigDecimal;
import java.util.Objects;

/**
 * Whether two Souther values are the same one, and the hash that agrees with it. This is the one
 * definition: a collection, a generated class and the generated bytecode all reach it rather than
 * writing the rule again.
 *
 * <p>Most values answer for themselves. A String, a Long, a Boolean, a LocalDate, a generated data
 * class — their own {@code equals} already is the language's equality, so this asks them. Two kinds
 * cannot. A {@code BigDecimal}'s {@code equals} calls 1.0 and 1.00 different, and the same amount
 * arrives with a different scale depending on whether it was read from JSON or from a DB column; the
 * rule that scale is not part of a Decimal's identity lives here. A container that implements a JDK
 * collection interface owes that interface its {@code equals} and {@code hashCode}, so it carries
 * the language's semantics on {@link ValueSemantics} and this asks for them there.
 *
 * <p>Equality ignoring scale forces the hash to ignore it too. A value that compares equal and
 * hashes differently lands in another bucket and stops being findable by its own key — Groovy
 * changed {@code ==} and left {@code hashCode} alone, and that bug is still open.
 *
 * <p>The {@code BigDecimal} overloads are what the generated bytecode calls where both operands are
 * statically a Decimal. They share the body with the general form, so there is one rule, not two.
 */
public final class Values {

    private Values() {}

    public static boolean equal(Object a, Object b) {
        if (a instanceof ValueSemantics s) {
            return s.valueEquals(b);
        }
        if (b instanceof ValueSemantics s) {
            return s.valueEquals(a);
        }
        if (a instanceof BigDecimal x && b instanceof BigDecimal y) {
            return equal(x, y);
        }
        return Objects.equals(a, b);
    }

    /** Two amounts are the same amount when they differ only in scale. */
    public static boolean equal(BigDecimal a, BigDecimal b) {
        return a == null ? b == null : b != null && a.compareTo(b) == 0;
    }

    public static int hash(Object v) {
        if (v instanceof ValueSemantics s) {
            return s.valueHash();
        }
        if (v instanceof BigDecimal d) {
            return hash(d);
        }
        return Objects.hashCode(v);
    }

    /** The hash of an amount, taken after dropping the scale its equality ignores. */
    public static int hash(BigDecimal v) {
        return v == null ? 0 : v.stripTrailingZeros().hashCode();
    }
}
