package souther.compiler.meta;

import souther.compiler.check.BehaviorImplementation;
import souther.compiler.ast.Ast;
import souther.compiler.ast.Hir;
import souther.compiler.check.CarriedDefinitions;
import souther.compiler.check.Preserved;
import souther.compiler.check.ValueEntries;
import souther.compiler.check.Sig;
import souther.compiler.types.Type;
import souther.compiler.types.TypeReachName;
import souther.compiler.types.TypeSpelling;
import souther.compiler.types.TypeSymbols;
import souther.compiler.types.ValueName;
import souther.compiler.codegen.Backend;
import souther.compiler.codegen.Emissions;
import souther.compiler.jvm.GeneratedClass;
import souther.compiler.frontend.CstFrontend;

import java.lang.classfile.Annotation;
import java.lang.classfile.AnnotationElement;
import java.lang.classfile.AnnotationValue;
import java.lang.classfile.Attributes;
import java.lang.classfile.ClassFile;
import java.lang.classfile.ClassModel;
import java.lang.classfile.ClassTransform;
import java.lang.classfile.attribute.RuntimeInvisibleAnnotationsAttribute;
import java.lang.constant.ClassDesc;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

/**
 * Writes a module's declarations into the classes it generated, so another project can import the
 * module from a jar without its {@code .sou}.
 *
 * <p>Each definition goes on the class it produced — a {@code data} on the class of that name, a
 * behavior on its interface — as the source that declared it. What is left is module-level: the
 * name, the {@code exposing} list, the imports the declarations were written under, and an index of
 * which classes to read. That goes on a {@code $Module} class emitted for the purpose.
 *
 * <p>This runs over the generated bytes rather than inside the backend: nothing about how a class is
 * built depends on what is being said about it. Which class a name was emitted under is not decided
 * here — a {@link GeneratedClass} says which class carries what, and the emission registry it goes
 * through is the same one the backend filled, so a reader is
 * sent to the name that was emitted.
 */
public final class ModuleMetadata {

    private ModuleMetadata() {}

    private static final ClassDesc MODULE_ANN = ClassDesc.of("souther.runtime.meta.SoutherModule");
    private static final ClassDesc DATA_ANN = ClassDesc.of("souther.runtime.meta.SoutherData");
    private static final ClassDesc BEHAVIOR_ANN = ClassDesc.of("souther.runtime.meta.SoutherBehavior");

    /**
     * The compiler that produced a module, for the message that reports a
     * {@link Backend#BOUNDARY_VERSION} mismatch. It comes from the jar's manifest, which Maven fills
     * from the project version — the root pom is the one place the version is written, and a
     * constant here would be another place to forget. Running from class files there is no manifest,
     * and nothing decides anything by the value.
     */
    public static String compilerVersion() {
        String version = releasedVersion();
        return version == null ? "unreleased" : version;
    }

    /**
     * The version this compiler was released as, or null where it is running from class files and
     * there is no manifest to say.
     *
     * <p>Beside {@link #compilerVersion} rather than under it, because one caller has to tell the
     * two apart. A version written into a project's build file resolves an artifact, and the word
     * this compiler falls back to when it does not know resolves nothing — so {@code souther init}
     * asks the question that can be answered with "there is no version here" and refuses, rather
     * than writing a build file naming a release that was never cut.
     */
    public static String releasedVersion() {
        return ModuleMetadata.class.getPackage().getImplementationVersion();
    }

    /**
     * {@code out} with each definition's declaration written onto the class it generated, plus the
     * module's own {@code $Module}. {@code module} is the module as parsed, before anything derived
     * or inlined, so the invariants read as they were written. {@code sigs} supplies the signature
     * of a {@code >->} composition, which declares stages instead of one; {@code implementations}
     * says where each behavior's body comes from (spec §injected-behavior, §unwritten-behavior),
     * which is the compiler's rule to state and not a fact about any one class. {@code requirements}
     * is what each behavior constructed here requires injected, which a composition works out from
     * stages that are not carried.
     */
    public static void stamp(Emissions out, Ast.Module module, Hir.Module resolved,
                             CstFrontend.Slices slices, Map<String, Sig> sigs,
                             Map<String, BehaviorImplementation> implementations,
                             Map<String, List<ValueName.Behavior>> requirements,
                             TypeReachName.Naming naming, Preserved.SettledValues settledValues) {
        List<String> types = new ArrayList<>();
        for (Ast.Def def : module.defs()) {
            types.add(def.name());
            add(out, new GeneratedClass.Value(TypeSymbols.declared(def.declaredKey())),
                    Annotation.of(DATA_ANN,
                            AnnotationElement.ofString("value", slices.defs().get(def.name()))));
        }
        List<String> behaviors = new ArrayList<>();
        for (Ast.BehaviorDef b : module.behaviors()) {
            String signature = signatureOf(b, slices, sigs, naming);
            if (signature == null) {
                continue;
            }
            behaviors.add(b.name());
            PublishedSignature from = switch (b) {
                case Ast.SpecBehavior _ -> PublishedSignature.DECLARED;
                case Ast.PipeBehavior _ -> PublishedSignature.COMPOSED;
            };
            BehaviorImplementation implementation = implementations.get(b.name());
            List<ValueName.Behavior> required = requirements.get(b.name());
            if (required == null) {
                throw new IllegalStateException("`" + module.name() + "." + b.name()
                        + "` reached publication with no requirement set");
            }
            if (!implementation.admits(required)) {
                // What a reader of the class refuses to read, so it is not written.
                throw new IllegalStateException("`" + module.name() + "." + b.name() + "` is "
                        + implementation.written() + " and reached publication requiring "
                        + required);
            }
            add(out, new GeneratedClass.BehaviorInterface(module.name(), b.name()),
                    Annotation.of(BEHAVIOR_ANN,
                            AnnotationElement.ofString("signature", signature),
                            AnnotationElement.ofString("signatureFrom", from.written()),
                            AnnotationElement.ofString("implementation", implementation.written()),
                            strings("requirements", PublishedRequirements.written(required))));
        }
        out.put(new GeneratedClass.ModuleDeclarations(module.name()),
                Backend.moduleClass(module.name(), moduleAnnotation(module, resolved, slices, types,
                        behaviors, ValueAnswers.written(module.name(),
                                ValueEntries.publishedValues(resolved), settledValues),
                        PublishedLinkages.written(out.provides()),
                        PublishedLinkages.written(out.requires()),
                        PublishedCopies.written(out.copies().provides()),
                        PublishedCopies.written(out.copies().requires()))));
    }

    /**
     * What the importing module reads as this behavior's signature. A declared one is the
     * declaration as written. A composition declares its stages, not a signature, so the computed
     * one is written out — the stages are the module's own business and are not carried. The
     * parser asks for a name on every parameter, so the computed one is given names; they are
     * {@link PublishedSignature#COMPOSED}'s to drop, and a reader never sees them.
     *
     * <p>Null where the behavior has no signature to publish, and only there. A composition whose
     * stage names nothing computes none, and nothing is carried for it.
     */
    private static String signatureOf(Ast.BehaviorDef b, CstFrontend.Slices slices,
                                      Map<String, Sig> sigs, TypeReachName.Naming naming) {
        if (b instanceof Ast.SpecBehavior) {
            return slices.behaviors().get(b.name());
        }
        Sig sig = sigs.get(b.name());
        if (sig == null) {
            return null;
        }
        StringBuilder params = new StringBuilder();
        for (int i = 0; i < sig.inputTypes().size(); i++) {
            params.append(i == 0 ? "" : ", ").append("in").append(i).append(": ")
                    .append(computed(b.name(), sig.inputTypes().get(i), naming));
        }
        return "behavior " + b.name() + " : (" + params + ") -> "
                + computed(b.name(), sig.outputType(), naming);
    }

    /**
     * One type of a computed signature, written the way the module publishing it writes types.
     *
     * <p>What is published is source, read back by the same front end that read the module. So the
     * names in it are this module's names, asked of the module rather than taken off the type's own
     * spelling: an identity says which declaration it is, and never how the module that mentions it
     * writes it down — a bare name here, an alias there, the declaring module's name where the
     * module has neither. This is what {@link TypeReachName.Naming} exists to be asked, and this is
     * a writer of a reference it did not read.
     *
     * <p>A type this module cannot name at all does not reach here. What a computed signature is
     * made of is what its stages were declared with, and a declared signature carries neither the
     * language's own vocabulary (E1325) nor a type its module keeps to itself (E1611) — so by the
     * time a composition has one, every type in it is one the module has a word for. That is a
     * compilation this compiler failed to refuse rather than a program anyone can write, so it is
     * said as one: no code, no position, nothing for an author to do about it.
     */
    static String computed(String behavior, Type type, TypeReachName.Naming naming) {
        return switch (TypeSpelling.of(type, naming)) {
            case TypeSpelling.Spelled(String rendered) -> rendered;
            case TypeSpelling.Unnameable(var denotes) -> throw new IllegalStateException(
                    "`" + behavior + "` reached metadata publication with `" + denotes
                            + "`, which has no name in the module publishing it");
        };
    }

    /**
     * Adds {@code annotation} to {@code binaryName}'s class, keeping any already there. A class file
     * may carry only one {@code RuntimeInvisibleAnnotations} attribute, so an annotation joins the
     * existing one rather than a second attribute being appended — appending would emit a class the
     * verifier rejects, which is a worse way to find out than a compile error. Nothing generated
     * today carries an annotation of its own; this is what keeps that from mattering.
     */
    private static void add(Emissions classes, GeneratedClass carrier, Annotation annotation) {
        classes.rewrite(carrier, bytes -> {
            ClassFile cf = ClassFile.of();
            ClassModel model = cf.parse(bytes);
            List<Annotation> all = new ArrayList<>();
            model.findAttribute(Attributes.runtimeInvisibleAnnotations())
                    .ifPresent(a -> all.addAll(a.annotations()));
            all.add(annotation);
            return cf.transformClass(model, ClassTransform
                    .dropping(a -> a instanceof RuntimeInvisibleAnnotationsAttribute)
                    .andThen(ClassTransform.endHandler(
                            b -> b.with(RuntimeInvisibleAnnotationsAttribute.of(all)))));
        });
    }

    private static Annotation moduleAnnotation(Ast.Module module, Hir.Module resolved,
            CstFrontend.Slices slices,
                                               List<String> types, List<String> behaviors,
                                               List<String> valueAnswers,
                                               List<String> providedLinkages,
                                               List<String> requiredLinkages,
                                               List<String> providedCopies,
                                               List<String> requiredCopies) {
        return Annotation.of(MODULE_ANN,
                AnnotationElement.ofInt("compat", Backend.BOUNDARY_VERSION),
                AnnotationElement.ofString("compiler", compilerVersion()),
                AnnotationElement.ofString("name", module.name()),
                AnnotationElement.ofString("header", slices.header()),
                strings("imports", slices.imports()),
                strings("types", types),
                strings("behaviors", behaviors),
                strings("invariantHelpers", invariantHelpers(module, resolved, slices)),
                strings("valueAnswers", valueAnswers),
                strings("providedLinkages", providedLinkages),
                strings("requiredLinkages", requiredLinkages),
                strings("providedCopies", providedCopies),
                strings("requiredCopies", requiredCopies));
    }

    private static AnnotationElement strings(String name, List<String> values) {
        List<AnnotationValue> elements = new ArrayList<>();
        for (String value : values) {
            elements.add(AnnotationValue.ofString(value));
        }
        return AnnotationElement.of(name, AnnotationValue.ofArray(elements));
    }

    /**
     * The {@code let}s a reader of this module's declarations needs, as they were written: what the
     * module hands over ({@link CarriedDefinitions}). A value runs where it is declared and is not
     * executed from what is carried here.
     *
     * <p>What travels is the source as written, which the reader's compiler reads back. That makes
     * the meaning of a carried body part of what a jar promises, and it is {@link
     * Backend#BOUNDARY_VERSION} that the promise is recorded under.
     */
    private static List<String> invariantHelpers(Ast.Module module, Hir.Module resolved,
                                                 CstFrontend.Slices slices) {
        List<String> texts = new ArrayList<>();
        for (String name : CarriedDefinitions.of(resolved, module.published())) {
            texts.add(slices.fns().get(name));
        }
        return texts;
    }

}
