package souther.compiler.meta;

import souther.compiler.ast.Ast;
import souther.compiler.check.HelperInliner;
import souther.compiler.check.Sig;
import souther.compiler.types.Type;
import souther.compiler.types.TypeSymbols;
import souther.compiler.codegen.Backend;
import souther.compiler.codegen.Emissions;
import souther.compiler.jvm.GeneratedClass;
import souther.compiler.jvm.SoutherJvmAbi;
import souther.compiler.frontend.CstFrontend;

import java.lang.classfile.Annotation;
import java.lang.classfile.AnnotationElement;
import java.lang.classfile.AnnotationValue;
import java.lang.classfile.Attributes;
import java.lang.classfile.ClassFile;
import java.lang.classfile.ClassModel;
import java.lang.classfile.ClassTransform;
import java.lang.classfile.attribute.RuntimeInvisibleAnnotationsAttribute;
import java.lang.constant.ClassDesc;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * Writes a module's declarations into the classes it generated, so another project can import the
 * module from a jar without its {@code .sou}.
 *
 * <p>Each definition goes on the class it produced — a {@code data} on the class of that name, a
 * behavior on its interface — as the source that declared it. What is left is module-level: the
 * name, the {@code exposing} list, the imports the declarations were written under, and an index of
 * which classes to read. That goes on a {@code $Module} class emitted for the purpose.
 *
 * <p>This runs over the generated bytes rather than inside the backend: nothing about how a class is
 * built depends on what is being said about it. Which class a name was emitted under is not decided
 * here — a {@link GeneratedClass} says which class carries what, and the emission registry it goes
 * through is the same one the backend filled, so a reader is
 * sent to the name that was emitted.
 */
public final class ModuleMetadata {

    private ModuleMetadata() {}

    private static final ClassDesc MODULE_ANN = ClassDesc.of("souther.runtime.meta.SoutherModule");
    private static final ClassDesc DATA_ANN = ClassDesc.of("souther.runtime.meta.SoutherData");
    private static final ClassDesc BEHAVIOR_ANN = ClassDesc.of("souther.runtime.meta.SoutherBehavior");

    /**
     * The compiler that produced a module, for the message that reports a
     * {@link Backend#BOUNDARY_VERSION} mismatch. It comes from the jar's manifest, which Maven fills
     * from the project version — the root pom is the one place the version is written, and a
     * constant here would be another place to forget. Running from class files there is no manifest,
     * and nothing decides anything by the value.
     */
    public static String compilerVersion() {
        String version = ModuleMetadata.class.getPackage().getImplementationVersion();
        return version == null ? "unreleased" : version;
    }

    /**
     * {@code out} with each definition's declaration written onto the class it generated, plus the
     * module's own {@code $Module}. {@code module} is the module as parsed, before anything derived
     * or inlined, so the invariants read as they were written. {@code sigs} supplies the signature
     * of a {@code >->} composition, which declares stages instead of one; {@code injected} names the
     * behaviors this module leaves to be injected (spec §injected-behavior), which is the compiler's rule to state
     * and not a fact about any one class.
     */
    public static void stamp(Emissions out, Ast.Module module, CstFrontend.Slices slices,
                             Map<String, Sig> sigs, Set<String> injected) {
        List<String> types = new ArrayList<>();
        for (Ast.Def def : module.defs()) {
            types.add(def.name());
            add(out, new GeneratedClass.Value(TypeSymbols.declared(def.declaredKey())),
                    Annotation.of(DATA_ANN,
                            AnnotationElement.ofString("value", slices.defs().get(def.name()))));
        }
        List<String> behaviors = new ArrayList<>();
        for (Ast.BehaviorDef b : module.behaviors()) {
            String signature = signatureOf(b, slices, sigs);
            if (signature == null) {
                continue;
            }
            behaviors.add(b.name());
            add(out, new GeneratedClass.BehaviorInterface(module.name(), b.name()),
                    Annotation.of(BEHAVIOR_ANN,
                            AnnotationElement.ofString("signature", signature),
                            AnnotationElement.ofBoolean("injected", injected.contains(b.name()))));
        }
        out.put(new GeneratedClass.ModuleDeclarations(module.name()),
                Backend.moduleClass(module.name(), moduleAnnotation(module, slices, types, behaviors)));
    }

    /**
     * What the importing module reads as this behavior's signature. A declared one is the
     * declaration as written. A composition declares its stages, not a signature, so the computed
     * one is written out — the stages are the module's own business and are not carried.
     */
    private static String signatureOf(Ast.BehaviorDef b, CstFrontend.Slices slices,
                                      Map<String, Sig> sigs) {
        if (b instanceof Ast.SpecBehavior) {
            return slices.behaviors().get(b.name());
        }
        Sig sig = sigs.get(b.name());
        if (sig == null) {
            return null;
        }
        StringBuilder params = new StringBuilder();
        for (int i = 0; i < sig.inputTypes().size(); i++) {
            params.append(i == 0 ? "" : ", ").append("in").append(i).append(": ")
                    .append(Type.showQualified(sig.inputTypes().get(i)));
        }
        return "behavior " + b.name() + " : (" + params + ") -> " + Type.showQualified(sig.outputType());
    }

    /**
     * Adds {@code annotation} to {@code binaryName}'s class, keeping any already there. A class file
     * may carry only one {@code RuntimeInvisibleAnnotations} attribute, so an annotation joins the
     * existing one rather than a second attribute being appended — appending would emit a class the
     * verifier rejects, which is a worse way to find out than a compile error. Nothing generated
     * today carries an annotation of its own; this is what keeps that from mattering.
     */
    private static void add(Emissions classes, GeneratedClass carrier, Annotation annotation) {
        classes.rewrite(carrier, bytes -> {
            ClassFile cf = ClassFile.of();
            ClassModel model = cf.parse(bytes);
            List<Annotation> all = new ArrayList<>();
            model.findAttribute(Attributes.runtimeInvisibleAnnotations())
                    .ifPresent(a -> all.addAll(a.annotations()));
            all.add(annotation);
            return cf.transformClass(model, ClassTransform
                    .dropping(a -> a instanceof RuntimeInvisibleAnnotationsAttribute)
                    .andThen(ClassTransform.endHandler(
                            b -> b.with(RuntimeInvisibleAnnotationsAttribute.of(all)))));
        });
    }

    private static Annotation moduleAnnotation(Ast.Module module, CstFrontend.Slices slices,
                                               List<String> types, List<String> behaviors) {
        return Annotation.of(MODULE_ANN,
                AnnotationElement.ofInt("compat", Backend.BOUNDARY_VERSION),
                AnnotationElement.ofString("compiler", compilerVersion()),
                AnnotationElement.ofString("name", module.name()),
                AnnotationElement.ofString("header", slices.header()),
                strings("imports", slices.imports()),
                strings("types", types),
                strings("behaviors", behaviors),
                strings("invariantHelpers", invariantHelpers(module, slices)));
    }

    private static AnnotationElement strings(String name, List<String> values) {
        List<AnnotationValue> elements = new ArrayList<>();
        for (String value : values) {
            elements.add(AnnotationValue.ofString(value));
        }
        return AnnotationElement.of(name, AnnotationValue.ofArray(elements));
    }

    /**
     * The {@code let}s a reader of this module's declarations needs, as they were written: the
     * helpers its invariants call, and the definitions it publishes.
     *
     * <p>An invariant is part of what a type is, so it has to be readable where the type is imported,
     * and it cannot be read without the helpers it names. A published value or helper is the same: a
     * value is substituted where it is named and a helper expanded where it is called (ADR-0072), so
     * a reader needs the body, and the body's own workings with it. A {@code let} neither reaches is
     * not carried — this publishes what the declarations need, not the module's implementation.
     *
     * <p>What travels is the source as written, which the reader's compiler reads back. That makes
     * the meaning of a carried body part of what a jar promises, and it is {@link
     * Backend#BOUNDARY_VERSION} that the promise is recorded under.
     */
    private static List<String> invariantHelpers(Ast.Module module, CstFrontend.Slices slices) {
        Map<String, Ast.FnDef> own = new LinkedHashMap<>();
        for (Ast.FnDef fn : module.fns()) {
            own.put(fn.name(), fn);
        }
        Set<String> reached = new LinkedHashSet<>();
        for (Ast.Def def : module.defs()) {
            if (def instanceof Ast.Data d) {
                for (Ast.InvariantClause clause : d.invariants()) {
                    reach(clause.expr(), own, reached);
                }
            }
        }
        Set<String> exposed = new java.util.HashSet<>(module.exposing());
        // A behavior's body is not published — a reader has its signature and calls it — so a
        // behavior's own `let` is not carried whatever its shape.
        Set<String> behaviorNames = new LinkedHashSet<>();
        for (Ast.BehaviorDef b : module.behaviors()) {
            behaviorNames.add(b.name());
        }
        for (Ast.FnDef fn : own.values()) {
            if (HelperInliner.isHelperName(behaviorNames, fn.name())
                    && exposed.contains(fn.name()) && fn.body() instanceof Ast.FnBody.Written w) {
                reached.add(fn.name());
                reach(w.expr(), own, reached);
            }
        }
        List<String> texts = new ArrayList<>();
        for (String name : reached) {
            texts.add(slices.fns().get(name));
        }
        return texts;
    }

    /**
     * A helper is reached by being called and by being named — handing one to a combinator, as in
     * {@code all(positive, items)}, needs it just as much as calling it does.
     *
     * <p>One set does for both visited and reached: a helper is added the first time it is seen, and
     * nothing is ever taken out, so a second sighting stops the walk by itself.
     *
     */
    private static void reach(Ast.Expr e, Map<String, Ast.FnDef> own, Set<String> reached) {
        String named = switch (e) {
            case Ast.Apply call -> call.written();
            case Ast.Var var -> var.name();
            default -> null;
        };
        if (named != null && own.containsKey(named) && reached.add(named)) {
            // an `intrinsic` helper is a name with nothing to walk into
            if (own.get(named).body() instanceof Ast.FnBody.Written w) {
                reach(w.expr(), own, reached);
            }
        }
        Ast.forEachChild(e, c -> reach(c, own, reached));
    }
}
