package souther.compiler;

import souther.compiler.ast.Ast;
import souther.compiler.check.Type;
import souther.compiler.check.TypeChecker;
import souther.compiler.diag.CompileException;
import souther.compiler.diag.Diagnostic;
import souther.compiler.diag.Messages;
import souther.compiler.diag.SourcePos;

import net.unit8.raoh.Err;
import net.unit8.raoh.Ok;
import net.unit8.raoh.Result;
import net.unit8.raoh.decode.Decoder;
import net.unit8.raoh.decode.ObjectDecoders;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * Evaluates a module's {@code example}s at compile time and reports any mismatch as a compile error.
 * It mirrors {@link Runner}: it decodes each row's input expressions into the target
 * behavior's parameter types through their derived decoders, applies the behavior via reflection on
 * the just-generated bytecode ({@link MemoryClassLoader}), and compares the result against the
 * expected arm (a bare type name) or value (a construction/literal). A failing example fails the
 * build, exactly as a false constant invariant does in {@link Compiler#verifyConstConstructions}.
 *
 * <p>A behavior with a {@code let} body is evaluable; an injected or {@code >->} target is refused
 * ({@code E1902}). A {@code requires} dependency is satisfied by a fake supplied at the example: a
 * {@code with dep = value} on the row (a constant/value dependency) or a {@code fake dep | table}
 * declaration (an input-keyed function dependency). Each fake is a {@code Behavior} proxy passed to
 * the generated behavior's injecting constructor — it produces no run-time class. Inputs, expected
 * values, and fake entries are fixtures — literals, newtype constructions, and record constructions.
 */
public final class ExampleVerifier {

    /** Evaluates every example in {@code module}; returns one diagnostic per failing example row
     * (empty when all pass). Does not throw for a failed example — the caller aggregates.
     * {@code importedPackages} maps an imported type's bare name to its declaring module, so a
     * fixture of an imported type decodes against that module's package (a cross-module example). */
    public static List<Diagnostic> check(Ast.Module module, Map<String, Ast.Def> symbols,
                                         Map<String, TypeChecker.Sig> sigs,
                                         Map<String, String> importedPackages, Map<String, byte[]> classes) {
        if (module.examples().isEmpty()) {
            return List.of();
        }
        MemoryClassLoader loader = new MemoryClassLoader(classes, ExampleVerifier.class.getClassLoader());
        ExampleVerifier v = new ExampleVerifier(module, symbols, sigs, importedPackages, loader);
        List<Diagnostic> failures = new ArrayList<>();
        for (Ast.Example ex : module.examples()) {
            try {
                v.checkExample(ex, failures);
            } catch (LinkageError le) {
                // The runtime is not on this host's classpath (it is `provided`, like CTFE), so the
                // generated classes cannot be loaded to evaluate here; the build-time pass, where the
                // runtime is present, still checks this example.
            }
        }
        return failures;
    }

    /** Runs {@link #check} and, if any example failed, fails the build with an aggregated error. */
    public static void verify(Ast.Module module, Map<String, Ast.Def> symbols,
                              Map<String, TypeChecker.Sig> sigs,
                              Map<String, String> importedPackages, Map<String, byte[]> classes) {
        List<Diagnostic> failures = check(module, symbols, sigs, importedPackages, classes);
        if (failures.isEmpty()) {
            return;
        }
        // The diagnostic infrastructure carries one diagnostic per exception; report the first and
        // summarize the rest in its hint so a single build surfaces every failing example.
        Diagnostic first = failures.get(0);
        if (failures.size() == 1) {
            throw CompileException.of(first, legacyOf(first));
        }
        Diagnostic aggregate = Diagnostic.of(first.code(), "check.example.failed.more")
                .title("check.example.title")
                .at(first.region())
                .args(failures.size())
                .hint("check.example.failed.more.hint", failures.size() - 1)
                .diff(first.diff() == null ? "" : first.diff().actualType(),
                        first.diff() == null ? "" : first.diff().expectedType())
                .build();
        throw CompileException.of(aggregate, failures.size() + " examples do not hold; " + legacyOf(first));
    }

    /** A one-line message for a failing example, used where only the legacy string is shown (the LSP
     * surfaces this rather than the rendered catalog message). */
    private static String legacyOf(Diagnostic d) {
        if (d.diff() != null) {
            // JUnit order: the expected value (what the example asserts) first, then what the
            // behavior actually produced.
            return "example does not hold: expected " + d.diff().expectedType()
                    + " but was " + d.diff().actualType();
        }
        // A diff-less failure (an input fixture that could not be built, a missing fake, a
        // non-termination): render the diagnostic's own catalog message so the reason travels
        // through the annotation processor, rather than collapsing to a bare "example failed".
        if (d.messageKey() != null) {
            return Messages.get(d.messageKey(), Messages.defaultLocale(), d.args());
        }
        return "example failed";
    }

    private final Ast.Module module;
    private final Map<String, Ast.Def> symbols;
    private final Map<String, TypeChecker.Sig> sigs;
    private final Map<String, String> importedPackages;
    private final MemoryClassLoader loader;

    private ExampleVerifier(Ast.Module module, Map<String, Ast.Def> symbols,
                            Map<String, TypeChecker.Sig> sigs,
                            Map<String, String> importedPackages, MemoryClassLoader loader) {
        this.module = module;
        this.symbols = symbols;
        this.sigs = sigs;
        this.importedPackages = importedPackages;
        this.loader = loader;
    }

    // --- one example (a target and its rows) --------------------------------------------------

    private void checkExample(Ast.Example ex, List<Diagnostic> out) {
        String target = ex.target();
        Ast.SpecBehavior spec = runnableBehavior(target);
        if (spec == null) {
            out.add(notRunnable(ex));
            return;
        }
        TypeChecker.Sig sig = sigs.get(target);
        Set<String> outCases = outCases(sig.out());
        for (Ast.ExampleRow row : ex.rows()) {
            checkRow(target, spec, sig, outCases, row, out);
        }
    }

    /** The target as an evaluable behavior (a {@code let} body); its {@code requires} are satisfied
     * by fakes at the example (checked per row), or null when it has no in-language body. */
    private Ast.SpecBehavior runnableBehavior(String name) {
        for (Ast.BehaviorDef b : module.behaviors()) {
            if (b instanceof Ast.SpecBehavior spec && spec.name().equals(name) && hasFn(name)) {
                return spec;
            }
        }
        return null;
    }

    private boolean hasFn(String name) {
        return module.fns().stream().anyMatch(f -> f.name().equals(name));
    }

    /** The injected behavior named {@code name} in this module (a SpecBehavior with no {@code let}),
     * i.e. a valid target for a fake; null if not found or not injected. */
    private Ast.SpecBehavior injectedSpec(String name) {
        for (Ast.BehaviorDef b : module.behaviors()) {
            if (b instanceof Ast.SpecBehavior spec && spec.name().equals(name) && !hasFn(name)) {
                return spec;
            }
        }
        return null;
    }

    /** The diagnostic for a target that cannot be evaluated: unknown (E1901) or present but not a
     * runnable behavior (E1902), with the reason (injected / pipeline / requires). */
    private Diagnostic notRunnable(Ast.Example ex) {
        String name = ex.target();
        boolean known = false;
        String reason = null;
        for (Ast.BehaviorDef b : module.behaviors()) {
            if (!b.name().equals(name)) {
                continue;
            }
            known = true;
            if (b instanceof Ast.PipeBehavior) {
                reason = "it is a `>->` pipeline";
            } else if (b instanceof Ast.SpecBehavior && !hasFn(name)) {
                reason = "it is injected from Java (no `let`) — fake it, do not example it";
            }
        }
        boolean isHelper = module.fns().stream().anyMatch(f -> f.name().equals(name)
                && module.behaviors().stream().noneMatch(b -> b.name().equals(name)));
        if (isHelper) {
            known = true;
            reason = "a pure helper example is not evaluated yet";
        }
        if (!known) {
            return Diagnostic.of("E1901", "check.example.unknown").title("check.example.title")
                    .at(ex.pos()).args(name).build();
        }
        return Diagnostic.of("E1902", "check.example.notrunnable").title("check.example.title")
                .at(ex.pos()).args(name)
                .hint("check.example.notrunnable.hint", reason == null ? "it is not runnable" : reason)
                .build();
    }

    // --- one row ------------------------------------------------------------------------------

    private void checkRow(String target, Ast.SpecBehavior spec, TypeChecker.Sig sig,
                          Set<String> outCases, Ast.ExampleRow row, List<Diagnostic> out) {
        List<Type> ins = sig.ins();
        if (row.inputs().size() != ins.size()) {
            out.add(Diagnostic.of("E1903", "check.example.arity").title("check.example.title")
                    .at(row.pos()).args(target, ins.size(), row.inputs().size()).build());
            return;
        }
        Object[] args = new Object[ins.size()];
        for (int i = 0; i < ins.size(); i++) {
            try {
                Object raw = raw(row.inputs().get(i));
                args[i] = decode(ins.get(i), raw);
            } catch (FixtureException fe) {
                out.add(Diagnostic.of("E1903", "check.example.input").title("check.example.title")
                        .at(row.pos()).args(target, i + 1, fe.getMessage()).build());
                return;
            }
        }
        // validate the expected arm/value against the output cases before running
        String expectedArm = expectedArm(row.expected());
        if (expectedArm != null && !outCases.isEmpty() && !outCases.contains(expectedArm)) {
            out.add(Diagnostic.of("E1904", "check.example.arm").title("check.example.title")
                    .at(row.pos()).args(expectedArm, target)
                    .hint("check.example.arm.hint", String.join(", ", outCases)).build());
            return;
        }
        Object[] fakes = resolveFakes(spec, row, out);
        if (fakes == null) {
            return;   // a fake was missing/invalid; the diagnostic is already reported
        }
        Object result;
        try {
            result = invoke(spec, args, fakes);
        } catch (FakeMissException fm) {
            out.add(Diagnostic.of("E1909", "check.fake.miss").title("check.example.title")
                    .at(row.pos()).args(fm.getMessage()).build());
            return;
        } catch (AbortException ae) {
            out.add(mismatch(row, describeExpected(row.expected()), "aborted: " + ae.getMessage()));
            return;
        } catch (NonTerminationException nt) {
            out.add(Diagnostic.of("E1910", "check.example.nonterminating").title("check.example.title")
                    .at(row.pos()).args(nt.getMessage()).build());
            return;
        }
        if (!matches(row.expected(), result)) {
            out.add(mismatch(row, describeExpected(row.expected()), describeActual(result)));
        }
    }

    // --- fakes for a behavior's requires ------------------------------------------------------

    /** Builds a {@code Behavior} proxy for each of {@code spec}'s requires, in declared order; null
     * (with a diagnostic reported) when one is missing or invalid. */
    private Object[] resolveFakes(Ast.SpecBehavior spec, Ast.ExampleRow row, List<Diagnostic> out) {
        List<String> reqs = spec.requires();
        Object[] proxies = new Object[reqs.size()];
        for (int i = 0; i < reqs.size(); i++) {
            Object p = resolveFake(spec.name(), reqs.get(i), row, out);
            if (p == null) {
                return null;
            }
            proxies[i] = p;
        }
        return proxies;
    }

    private Object resolveFake(String target, String depName, Ast.ExampleRow row, List<Diagnostic> out) {
        Ast.SpecBehavior dep = injectedSpec(depName);
        if (dep == null) {
            out.add(fakeMissingDiag(target, depName, row, "`" + depName
                    + "` is not an injected behavior of this module"));
            return null;
        }
        Type outType = TypeChecker.successType(dep.ret(), symbols);
        // a value fake given inline on the row: `with dep = value`
        for (Ast.With w : row.withs()) {
            if (w.dep().equals(depName)) {
                try {
                    Object value = decode(fixtureType(w.value(), outType), raw(w.value()));
                    return fakeInstance(dep, a -> value, out);   // constant: ignores its inputs
                } catch (FixtureException fe) {
                    out.add(fakeMissingDiag(target, depName, row,
                            "the `with " + depName + "` value could not be built: " + fe.getMessage()));
                    return null;
                }
            }
        }
        // a function fake given as a `fake dep | table` declaration
        for (Ast.Fake fk : module.fakes()) {
            if (fk.target().equals(depName)) {
                return tableProxy(fk, dep, outType, out);
            }
        }
        out.add(fakeMissingDiag(target, depName, row, "add `with " + depName
                + " = ...` on the row, or a `fake " + depName + "` table"));
        return null;
    }

    private Diagnostic fakeMissingDiag(String target, String depName, Ast.ExampleRow row, String detail) {
        return Diagnostic.of("E1908", "check.fake.missing").title("check.example.title")
                .at(row.pos()).args(target, depName)
                .hint("check.fake.missing.hint", detail).build();
    }

    /** Precomputes a function fake's input→output table (decoded fixtures) as a tuple-keyed lookup, and
     * returns a fake instance ({@link #fakeInstance}) matching an actual input tuple by value equality,
     * falling back to the {@code _} default or a miss. Works for any arity: a 0/1-input dep's tuple has
     * 0/1 elements, a 2+-input dep's has one per parameter (issue #57). */
    private Object tableProxy(Ast.Fake fk, Ast.SpecBehavior dep, Type outType, List<Diagnostic> out) {
        List<Type> paramTypes = new ArrayList<>();
        for (Ast.Param p : dep.params()) {
            paramTypes.add(TypeChecker.successType(p.type(), symbols));
        }
        List<Object[]> entries = new ArrayList<>();   // {keyTuple, value}
        boolean[] hasDefault = {false};
        Object[] def = {null};
        try {
            for (Ast.FakeRow r : fk.rows()) {
                // A dependency that returns a sum has no single decoder; each row names one case,
                // so decode the row's output against that case's type (as an expected value is).
                Object value = decode(fixtureType(r.output(), outType), raw(r.output()));
                if (r.isDefault()) {
                    hasDefault[0] = true;
                    def[0] = value;
                } else {
                    if (r.inputs().size() != paramTypes.size()) {
                        out.add(Diagnostic.of("E1908", "check.fake.missing").title("check.example.title")
                                .at(r.pos()).args(fk.target(), fk.target())
                                .hint("check.fake.missing.hint", "a fake row has " + r.inputs().size()
                                        + " input(s) but `" + fk.target() + "` takes " + paramTypes.size())
                                .build());
                        return null;
                    }
                    Object[] key = new Object[paramTypes.size()];
                    for (int i = 0; i < paramTypes.size(); i++) {
                        key[i] = decode(paramTypes.get(i), raw(r.inputs().get(i)));
                    }
                    entries.add(new Object[] {key, value});
                }
            }
        } catch (FixtureException fe) {
            out.add(Diagnostic.of("E1908", "check.fake.missing").title("check.example.title")
                    .at(fk.pos()).args(fk.target(), fk.target())
                    .hint("check.fake.missing.hint", "a fake row could not be built: " + fe.getMessage())
                    .build());
            return null;
        }
        String depName = fk.target();
        int arity = paramTypes.size();
        java.util.function.Function<Object[], Object> body = a -> {
            // the Behavior contract passes one Object even for a 0-arg dep (a null); normalise to arity
            Object[] key = java.util.Arrays.copyOf(a, arity);
            for (Object[] e : entries) {
                if (java.util.Arrays.equals((Object[]) e[0], key)) {
                    return e[1];
                }
            }
            if (hasDefault[0]) {
                return def[0];
            }
            throw new FakeMissException("`" + depName + "` has no output for " + java.util.Arrays.toString(key));
        };
        return fakeInstance(dep, body, out);
    }

    /** Wraps a fake's {@code Object[] -> Object} body as the injected instance: a unary {@code Behavior}
     * proxy for a 0/1-input dependency, or a runtime-generated subclass of the standalone base for a
     * 2+-input one (whose typed {@code apply} the unary {@code Behavior} cannot stand in for; issue #57).
     * Both the table and the constant {@code with} fake route through here, so neither path assumes an
     * arity. */
    private Object fakeInstance(Ast.SpecBehavior dep, java.util.function.Function<Object[], Object> body,
                                List<Diagnostic> out) {
        if (dep.params().size() >= 2) {
            return multiArgFakeInstance(dep, body, out);
        }
        return behaviorProxy(body);
    }

    /** Generates (once) and instantiates a subclass of a multi-argument injected base whose typed
     * {@code apply} packs its arguments into an {@code Object[]} and delegates to {@code body}. */
    private Object multiArgFakeInstance(Ast.SpecBehavior dep,
                                        java.util.function.Function<Object[], Object> body,
                                        List<Diagnostic> out) {
        try {
            String baseName = module.name() + "." + behaviorClass(dep.name());
            Class<?> base = loader.loadClass(baseName);
            java.lang.reflect.Method apply = null;
            for (java.lang.reflect.Method m : base.getDeclaredMethods()) {
                if (m.getName().equals("apply") && java.lang.reflect.Modifier.isAbstract(m.getModifiers())) {
                    apply = m;
                }
            }
            if (apply == null) {
                throw new NoSuchMethodException("abstract apply on " + baseName);
            }
            String fakeName = baseName + "$Fake";
            java.lang.reflect.Method applyM = apply;
            Class<?> fakeClass = loader.define(fakeName, () -> fakeSubclassBytes(fakeName, base, applyM));
            return fakeClass.getConstructor(java.util.function.Function.class).newInstance(body);
        } catch (ReflectiveOperationException e) {
            out.add(Diagnostic.of("E1908", "check.fake.missing").title("check.example.title")
                    .at(dep.pos()).args(dep.name(), dep.name())
                    .hint("check.fake.missing.hint", "the multi-argument fake could not be built: " + e)
                    .build());
            return null;
        }
    }

    private byte[] fakeSubclassBytes(String fakeName, Class<?> base, java.lang.reflect.Method apply) {
        java.lang.constant.ClassDesc cdFake = java.lang.constant.ClassDesc.of(fakeName);
        java.lang.constant.ClassDesc cdBase = java.lang.constant.ClassDesc.of(base.getName());
        java.lang.constant.ClassDesc cdFunc =
                java.lang.constant.ClassDesc.of("java.util.function.Function");
        java.lang.constant.ClassDesc cdObject = java.lang.constant.ConstantDescs.CD_Object;
        java.lang.constant.ClassDesc[] paramDescs = new java.lang.constant.ClassDesc[apply.getParameterCount()];
        for (int i = 0; i < paramDescs.length; i++) {
            paramDescs[i] = apply.getParameterTypes()[i].describeConstable().orElseThrow();
        }
        java.lang.constant.ClassDesc retDesc = apply.getReturnType().describeConstable().orElseThrow();
        java.lang.constant.MethodTypeDesc applyDesc = java.lang.constant.MethodTypeDesc.of(retDesc, paramDescs);
        java.lang.constant.MethodTypeDesc voidCtor =
                java.lang.constant.MethodTypeDesc.of(java.lang.constant.ConstantDescs.CD_void);
        java.lang.constant.MethodTypeDesc funcApply =
                java.lang.constant.MethodTypeDesc.of(cdObject, cdObject);
        return java.lang.classfile.ClassFile.of().build(cdFake, cb -> {
            cb.withSuperclass(cdBase);
            cb.withFlags(java.lang.classfile.ClassFile.ACC_PUBLIC | java.lang.classfile.ClassFile.ACC_FINAL
                    | java.lang.classfile.ClassFile.ACC_SUPER);
            cb.withField("body", cdFunc, java.lang.classfile.ClassFile.ACC_PRIVATE
                    | java.lang.classfile.ClassFile.ACC_FINAL);
            cb.withMethodBody("<init>",
                    java.lang.constant.MethodTypeDesc.of(java.lang.constant.ConstantDescs.CD_void, cdFunc),
                    java.lang.classfile.ClassFile.ACC_PUBLIC, code -> {
                        code.aload(0);
                        code.invokespecial(cdBase, "<init>", voidCtor);
                        code.aload(0);
                        code.aload(1);
                        code.putfield(cdFake, "body", cdFunc);
                        code.return_();
                    });
            cb.withMethodBody("apply", applyDesc, java.lang.classfile.ClassFile.ACC_PUBLIC, code -> {
                code.aload(0);
                code.getfield(cdFake, "body", cdFunc);
                code.loadConstant(paramDescs.length);
                code.anewarray(cdObject);
                for (int i = 0; i < paramDescs.length; i++) {
                    code.dup();
                    code.loadConstant(i);
                    code.aload(i + 1);   // every apply param is a reference (Int boxes to Long, etc.)
                    code.aastore();
                }
                code.invokeinterface(cdFunc, "apply", funcApply);
                if (!retDesc.equals(cdObject)) {
                    code.checkcast(retDesc);
                }
                code.areturn();
            });
        });
    }

    /** A {@code Behavior} proxy whose {@code apply} runs {@code body}. Reflective so the runtime
     * (souther-runtime, `provided`) may be absent, in which case the LinkageError is caught upstream. */
    private Object behaviorProxy(java.util.function.Function<Object[], Object> body) {
        Class<?> iface;
        try {
            iface = loader.loadClass("souther.runtime.Behavior");
        } catch (ClassNotFoundException e) {
            throw new NoClassDefFoundError("souther.runtime.Behavior");
        }
        return java.lang.reflect.Proxy.newProxyInstance(loader, new Class<?>[] {iface}, (proxy, method, a) -> {
            if (method.getName().equals("apply")) {
                return body.apply(a == null ? new Object[0] : a);
            }
            return switch (method.getName()) {
                case "toString" -> "fake";
                case "hashCode" -> System.identityHashCode(proxy);
                case "equals" -> proxy == (a != null && a.length > 0 ? a[0] : null);
                default -> null;
            };
        });
    }

    private Diagnostic mismatch(Ast.ExampleRow row, String expected, String actual) {
        // Underline the expected result (the part the row asserts), not the whole row, so the marker
        // lands on something meaningful rather than a single column at the row's start.
        SourcePos pos = row.expected() != null ? row.expected().pos() : row.pos();
        int width = Math.max(1, expected.length());
        Diagnostic.Builder b = Diagnostic.of("E1905", "check.example.mismatch")
                .title("check.example.title")
                .at(pos, width)
                .diff(actual, expected);
        if (row.description() != null) {
            b.hint("check.example.mismatch.hint", row.description());
        }
        return b.build();
    }

    // --- comparison ---------------------------------------------------------------------------

    /** Whether {@code result} matches the row's expected: a bare {@link Ast.Var} asserts only the
     * arm (the concrete case class); anything else asserts the whole value by structural equality. */
    private boolean matches(Ast.Expr expected, Object result) {
        if (expected instanceof Ast.Var v) {
            return simpleName(result).equals(v.name());
        }
        Object expectedValue = buildExpected(expected);
        return expectedValue != null && expectedValue.equals(result);
    }

    /** The expected value built the same way as an input, so structural equality compares like with
     * like: a construction/newtype decodes through its type's decoder; a literal is its raw value. */
    private Object buildExpected(Ast.Expr expected) {
        try {
            if (expected instanceof Ast.NewData nd) {
                return decode(Type.ref(nd.typeName()), raw(expected));
            }
            if (expected instanceof Ast.Call c && isNewtype(c.fn())) {
                return decode(Type.ref(c.fn()), raw(expected));
            }
            return raw(expected);   // a literal expected value
        } catch (FixtureException fe) {
            return null;
        }
    }

    /** The arm name an expected asserts: a bare type name, or a construction's/newtype's type name. */
    private String expectedArm(Ast.Expr expected) {
        if (expected instanceof Ast.Var v) {
            return v.name();
        }
        if (expected instanceof Ast.NewData nd) {
            return nd.typeName();
        }
        if (expected instanceof Ast.Call c && isNewtype(c.fn())) {
            return c.fn();
        }
        return null;   // a literal expected (a primitive output)
    }

    /** The concrete type a fixture construction asserts — the case named by a record/newtype/unit
     * expression — or {@code declared} for a literal. A sum-returning dependency's fake row names one
     * case, so its output decodes against that case, not the declared sum (which has no decoder). */
    private Type fixtureType(Ast.Expr e, Type declared) {
        String arm = expectedArm(e);
        return arm != null ? Type.ref(arm) : declared;
    }

    /** The written expectation, rendered as it was written: a bare arm stays the arm name, anything
     * else is its neutral form under that arm ({@code Out { n = 7 }}). */
    private String describeExpected(Ast.Expr expected) {
        String arm = expectedArm(expected);
        if (expected instanceof Ast.Var) {
            return arm;   // a bare arm asserts only the case, so there is no value to show
        }
        // Render it through the same encoder the actual goes through, so the two sides are written
        // in one notation and can be read against each other; the fixture's own neutral form (which
        // still holds e.g. a LocalDate where the encoder writes its ISO text) is the fallback.
        Object built = buildExpected(expected);
        Object neutral = built == null || arm == null ? rawOrNull(expected) : encodedOrNull(built, arm);
        if (neutral == null) {
            neutral = rawOrNull(expected);
        }
        if (neutral == null) {
            return arm != null ? arm : "?";
        }
        return arm != null ? show(arm, neutral) : showValue(neutral);
    }

    /** What actually came out, in the same notation: the case name plus the value the derived encoder
     * writes, so the two sides of a mismatch can be read against each other. A value with no encoder
     * (or one that fails to encode) falls back to its case name alone. */
    private String describeActual(Object result) {
        String name = simpleName(result);
        if (name.isEmpty()) {
            return String.valueOf(result);
        }
        Object encoded = encodedOrNull(result, name);
        if (encoded != null) {
            return show(name, encoded);
        }
        return isScalar(result) ? showValue(result) : name;
    }

    /** Whether a value is a neutral scalar, so it can be shown as written rather than by class name. */
    private static boolean isScalar(Object v) {
        return v instanceof String || v instanceof Long || v instanceof Boolean
                || v instanceof BigDecimal || v instanceof java.time.LocalDate
                || v instanceof java.time.LocalDateTime;
    }

    /** {@code result} through its class's derived {@code encoder()}, or null when it has none. */
    private Object encodedOrNull(Object result, String name) {
        try {
            String pkg = importedPackages.getOrDefault(name, module.name());
            Class<?> c = loader.loadClass(pkg + "." + name);
            Object encoder = c.getMethod("encoder").invoke(null);
            return net.unit8.raoh.encode.Encoder.class.getMethod("encode", Object.class)
                    .invoke(encoder, result);
        } catch (ReflectiveOperationException | RuntimeException e) {
            return null;
        }
    }

    /** A case name with its neutral value: a record's fields in braces, a newtype's value in parens,
     * a unit case as the bare name. */
    private String show(String name, Object neutral) {
        if (neutral instanceof Map<?, ?> fields) {
            if (fields.isEmpty()) {
                return name;
            }
            StringBuilder sb = new StringBuilder(name).append(" { ");
            boolean first = true;
            for (Map.Entry<?, ?> e : fields.entrySet()) {
                if (!first) {
                    sb.append(", ");
                }
                first = false;
                sb.append(e.getKey()).append(" = ").append(showValue(e.getValue()));
            }
            return sb.append(" }").toString();
        }
        return name + "(" + showValue(neutral) + ")";
    }

    /** A neutral value in the notation a fixture is written in: a quoted string, a list in brackets,
     * a map as its list of pairs, a date as {@code Date("...")}. */
    private String showValue(Object v) {
        if (v == null) {
            return "None";
        }
        if (v instanceof String s) {
            return "\"" + s + "\"";
        }
        if (v instanceof java.time.LocalDate || v instanceof java.time.LocalDateTime) {
            return (v instanceof java.time.LocalDate ? "Date(\"" : "DateTime(\"") + v + "\")";
        }
        if (v instanceof Map<?, ?> m) {
            List<String> entries = new ArrayList<>();
            for (Map.Entry<?, ?> e : m.entrySet()) {
                entries.add("(" + showValue(e.getKey()) + ", " + showValue(e.getValue()) + ")");
            }
            return entries.isEmpty() ? "[]" : "[ " + String.join(", ", entries) + " ]";
        }
        if (v instanceof Iterable<?> it) {
            List<String> elements = new ArrayList<>();
            for (Object e : it) {
                elements.add(showValue(e));
            }
            return elements.isEmpty() ? "[]" : "[ " + String.join(", ", elements) + " ]";
        }
        return String.valueOf(v);
    }

    private Object rawOrNull(Ast.Expr e) {
        try {
            return raw(e);
        } catch (FixtureException fe) {
            return null;
        }
    }

    private static String simpleName(Object o) {
        if (o == null) {
            return "null";
        }
        String n = o.getClass().getName();
        int dot = n.lastIndexOf('.');
        return dot < 0 ? n : n.substring(dot + 1);
    }

    private Set<String> outCases(Type out) {
        if (out instanceof Type.Union u) {
            return u.members();
        }
        if (out instanceof Type.Ref r) {
            return Set.of(r.name());
        }
        return Set.of();
    }

    // --- raw evaluation of a fixture expression -----------------------------------------------

    /** Turns a fixture expression into its neutral (decoder-input) form: a literal to a boxed value,
     * a newtype construction to its inner value, a record construction to a field map. */
    private Object raw(Ast.Expr e) {
        return switch (e) {
            case Ast.IntLit i -> i.value();
            case Ast.DecimalLit d -> d.value();
            case Ast.StringLit s -> s.value();
            case Ast.BoolLit b -> b.value();
            case Ast.Neg n -> negate(raw(n.operand()));
            case Ast.Binary bin -> fold(bin);
            case Ast.Call c -> newtypeInner(c);
            case Ast.Var v -> unitInput(v.name());
            case Ast.NewData nd -> record(nd);
            case Ast.ListLit l -> {
                List<Object> out = new ArrayList<>();
                for (Ast.Expr el : l.elements()) {
                    out.add(raw(el));
                }
                yield out;
            }
            // a `(key, value)` pair: only a `Map` field's entries are written this way, and `shaped`
            // collects them into the map the decoder reads (a tuple is not a data field type itself).
            case Ast.Tuple t -> {
                List<Object> out = new ArrayList<>();
                for (Ast.Expr el : t.elements()) {
                    out.add(raw(el));
                }
                yield out;
            }
            default -> throw new FixtureException("an example fixture must be a literal or a construction");
        };
    }

    /** A bare name in a fixture is only meaningful as a unit case (no fields) or the built-in {@code
     * None}; a unit's decoder ignores the input, so an empty map stands in, and {@code None} maps to
     * a null, which the optional decoder reads as the absent optional (spec 8, absent/null -> None),
     * the same as omitting a `T?` field — mirroring how a `let` body writes an empty optional. */
    private Object unitInput(String name) {
        if (name.equals("None")) {
            return null;
        }
        if (symbols.get(name) instanceof Ast.UnitData) {
            Map<String, Object> unit = new LinkedHashMap<>();
            tagged(name, unit);   // a unit case of a sum still needs the tag its decoder reads
            return unit;
        }
        throw new FixtureException("`" + name + "` is not a value a fixture can name");
    }

    private Object newtypeInner(Ast.Call c) {
        if (c.fn().equals("Date") || c.fn().equals("DateTime")) {
            // a written date: the decoders take the parsed temporal, not its text (a Date field's
            // neutral form is a LocalDate), so the fixture hands over the same value the checker read
            if (c.args().size() != 1 || !(c.args().get(0) instanceof Ast.StringLit lit)) {
                throw new FixtureException("`" + c.fn() + "` takes one written string");
            }
            return TypeChecker.parseTemporal(c.fn(), lit.value(), c.pos());
        }
        if (!isNewtype(c.fn())) {
            throw new FixtureException("`" + c.fn() + "` is not a newtype; a fixture cannot call it");
        }
        if (c.args().size() != 1) {
            throw new FixtureException("`" + c.fn() + "` takes one argument");
        }
        // a newtype over a temporal (`data 貸出日 = Date`) wraps the parsed value, so its written
        // string is read here as it would be for a bare `Date("...")`
        String base = newtypeBase(c.fn());
        if (("Date".equals(base) || "DateTime".equals(base))
                && c.args().get(0) instanceof Ast.StringLit lit) {
            return TypeChecker.parseTemporal(base, lit.value(), c.pos());
        }
        return raw(c.args().get(0));
    }

    private Object record(Ast.NewData nd) {
        if (!nd.spreads().isEmpty()) {
            throw new FixtureException("a `...spread` cannot be used in an example fixture");
        }
        Map<String, Ast.TypeRef> declared = fieldTypes(nd.typeName());
        Map<String, Object> map = new LinkedHashMap<>();
        for (Ast.FieldInit fi : nd.inits()) {
            Object v = shaped(raw(fi.value()), declared.get(fi.name()));
            // `None` on a `T?` field yields a null; leave the key out so the optional decoder reads
            // it as absent (spec 8, absent -> None), the same neutral form as omitting the field.
            if (v == null) {
                continue;
            }
            map.put(fi.name(), v);
        }
        tagged(nd.typeName(), map);
        return map;
    }

    /**
     * Writes the discriminator a sum's decoder reads, when the constructed data is a case of one.
     * A fixture names the case it means — `予算枠 = 未定予算`, or a whole `プロジェクト依頼 { … }` where
     * the parameter is the sum `依頼` — the same way the domain writes a construction, while the
     * decoder that reads it wants a tag on a key. Where the case is read as itself rather than
     * through its sum, the tag is a field the decoder does not look at.
     */
    private void tagged(String caseName, Map<String, Object> map) {
        for (Ast.Def def : symbols.values()) {
            if (!(def instanceof Ast.SumData sum) || sum.decoder().isEmpty()) {
                continue;
            }
            for (Ast.Variant variant : sum.decoder().get().variants()) {
                if (variant.caseType().equals(caseName)) {
                    map.put(sum.decoder().get().key(), variant.tag());
                    return;
                }
            }
        }
    }

    /** A data's fields by name, following the `...includes` it composes in (spec §data). */
    private Map<String, Ast.TypeRef> fieldTypes(String typeName) {
        Map<String, Ast.TypeRef> out = new LinkedHashMap<>();
        if (symbols.get(typeName) instanceof Ast.Data d) {
            for (String inc : d.includes()) {
                out.putAll(fieldTypes(inc));
            }
            for (Ast.Field f : d.fields()) {
                out.put(f.name(), f.type());
            }
        }
        return out;
    }

    /** Gives a fixture value the neutral shape its declared type decodes from. A {@code Map} field is
     * written as a list of {@code (key, value)} pairs — Elm's {@code Dict.fromList}, and the same
     * list literal a {@code Set} field takes — while the decoder wants a map, so the pairs are
     * collected here. Everything else passes through; a {@code List} field written as a list stays
     * one, since the declared type, not the literal, decides. */
    private Object shaped(Object v, Ast.TypeRef type) {
        if (type == null || v == null) {
            return v;
        }
        if ("Map".equals(type.name()) && v instanceof List<?> entries) {
            Ast.TypeRef value = type.arg();
            Map<Object, Object> m = new LinkedHashMap<>();
            for (Object entry : entries) {
                if (!(entry instanceof List<?> pair) || pair.size() != 2) {
                    throw new FixtureException("a `Map` fixture is a list of (key, value) pairs,"
                            + " e.g. [ (\"apple\", 3) ]");
                }
                m.put(pair.get(0), shaped(pair.get(1), value));
            }
            return m;
        }
        if (("List".equals(type.name()) || "Set".equals(type.name())) && v instanceof List<?> elements) {
            List<Object> out = new ArrayList<>(elements.size());
            for (Object e : elements) {
                out.add(shaped(e, type.arg()));
            }
            return out;
        }
        return v;
    }

    private boolean isNewtype(String name) {
        return symbols.get(name) instanceof Ast.Data d && d.newtype();
    }

    /** The type a newtype wraps ({@code Date} for {@code data 貸出日 = Date}), or null. */
    private String newtypeBase(String name) {
        return symbols.get(name) instanceof Ast.Data d && d.newtype() && d.fields().size() == 1
                ? d.fields().get(0).type().name()
                : null;
    }

    private static Object negate(Object v) {
        if (v instanceof Long l) {
            return -l;
        }
        if (v instanceof BigDecimal d) {
            return d.negate();
        }
        throw new FixtureException("only a number can be negated in a fixture");
    }

    private Object fold(Ast.Binary b) {
        Object l = raw(b.left());
        Object r = raw(b.right());
        if (l instanceof Long x && r instanceof Long y) {
            return switch (b.op()) {
                case ADD -> x + y;
                case SUB -> x - y;
                case MUL -> x * y;
                default -> throw new FixtureException("unsupported arithmetic in a fixture");
            };
        }
        if (l instanceof BigDecimal x && r instanceof BigDecimal y) {
            return switch (b.op()) {
                case ADD -> x.add(y);
                case SUB -> x.subtract(y);
                case MUL -> x.multiply(y);
                default -> throw new FixtureException("unsupported arithmetic in a fixture");
            };
        }
        throw new FixtureException("a fixture can only combine numbers of the same kind");
    }

    // --- decode a raw value into the parameter/expected type ----------------------------------

    private Object decode(Type type, Object raw) {
        Decoder<Object, ?> decoder = decoderFor(type);
        Result<?> result = decoder.decode(raw, net.unit8.raoh.Path.ROOT);
        if (result instanceof Ok<?> ok) {
            return ok.value();
        }
        String detail = ((Err<?>) result).issues().asList().stream()
                .map(net.unit8.raoh.Issue::message)
                .collect(java.util.stream.Collectors.joining("; "));
        throw new FixtureException(detail);
    }

    @SuppressWarnings("unchecked")
    private Decoder<Object, ?> decoderFor(Type type) {
        if (type instanceof Type.Prim prim) {
            return switch (prim) {
                case STRING -> ObjectDecoders.string();
                case INT -> ObjectDecoders.long_();
                case BOOL -> ObjectDecoders.bool();
                case DECIMAL -> ObjectDecoders.decimal();
                case DATE -> ObjectDecoders.date();
                case DATETIME -> ObjectDecoders.dateTime();
                case RAW -> throw new FixtureException("the Raw type cannot be an example input");
            };
        }
        if (type instanceof Type.Ref ref) {
            // An imported type's decoder lives in its declaring module's package, not this one's.
            String pkg = importedPackages.getOrDefault(ref.name(), module.name());
            try {
                Class<?> c = loader.loadClass(pkg + "." + ref.name());
                return (Decoder<Object, ?>) c.getMethod("decoder").invoke(null);
            } catch (ReflectiveOperationException e) {
                throw new FixtureException("no decoder for `" + ref.name() + "`");
            }
        }
        throw new FixtureException("`" + Type.show(type) + "` is not supported as an example value yet");
    }

    // --- invoke the behavior ------------------------------------------------------------------

    /** Wall-clock budget for evaluating one example row. A total behavior finishes in well under this;
     * a `partial` recursion that does not terminate hits it, so the compiler is bounded, never hung.
     * Overridable with the `souther.example.timeout.ms` system property for an unusually slow example. */
    private static final long EXAMPLE_TIMEOUT_MS = readTimeoutMs();

    private static long readTimeoutMs() {
        String override = System.getProperty("souther.example.timeout.ms");
        if (override == null) {
            return 2000L;
        }
        try {
            long ms = Long.parseLong(override.trim());
            return ms > 0 ? ms : 2000L;
        } catch (NumberFormatException e) {
            return 2000L;
        }
    }

    /**
     * Evaluates the behavior on a daemon worker thread with a timeout. Recursion is total by default,
     * so most code cannot loop; a `partial` recursion that does not terminate is the only risk, and
     * this bounds it — on timeout the row is reported (E1910). A non-terminating recursion that
     * overflows the stack instead of tail-looping is reported the same way (a non-termination, not a
     * generic failure). The worker is interrupted best-effort; a pure compute loop has no interrupt
     * point, so a deterministic step budget is the deferred complete fix.
     */
    private Object invoke(Ast.SpecBehavior spec, Object[] args, Object[] fakes) {
        java.util.concurrent.FutureTask<Object> task =
                new java.util.concurrent.FutureTask<>(() -> invokeNow(spec, args, fakes));
        Thread worker = new Thread(task, "souther-example-eval");
        worker.setDaemon(true);
        worker.start();
        try {
            return task.get(EXAMPLE_TIMEOUT_MS, java.util.concurrent.TimeUnit.MILLISECONDS);
        } catch (java.util.concurrent.TimeoutException te) {
            task.cancel(true);   // best-effort: marks the task cancelled and interrupts the worker
            throw new NonTerminationException("did not finish within " + EXAMPLE_TIMEOUT_MS + "ms");
        } catch (java.util.concurrent.ExecutionException ee) {
            Throwable cause = ee.getCause();
            if (cause instanceof FakeMissException fm) {
                throw fm;
            }
            if (cause instanceof NonTerminationException nt) {
                throw nt;   // a stack-overflowing `partial` recursion (invokeNow classified it)
            }
            if (cause instanceof AbortException ae) {
                throw ae;
            }
            throw new AbortException(cause == null ? "aborted" : String.valueOf(cause.getMessage()));
        } catch (InterruptedException ie) {
            Thread.currentThread().interrupt();
            throw new AbortException("interrupted");
        }
    }

    private Object invokeNow(Ast.SpecBehavior spec, Object[] args, Object[] fakes) {
        // The public name is now an interface; the fields, constructor and erased apply live on its
        // $Impl (spec 19.8). Instantiate and call apply on the $Impl.
        String className = module.name() + "." + behaviorClass(spec.name()) + "$Impl";
        try {
            Class<?> c = loader.loadClass(className);
            Object instance;
            if (spec.requires().isEmpty()) {
                instance = c.getConstructor().newInstance();
            } else {
                // the injecting constructor takes one param per requires: the unary Behavior for a
                // single-input dep (a Proxy), or the dep's own base class for a multi-input dep (a
                // generated subclass) — issue #57. The fake's runtime type tells the two apart.
                Class<?> behaviorIface = loader.loadClass("souther.runtime.Behavior");
                Class<?>[] ctorParams = new Class<?>[fakes.length];
                for (int i = 0; i < fakes.length; i++) {
                    ctorParams[i] = behaviorIface.isInstance(fakes[i])
                            ? behaviorIface
                            : fakes[i].getClass().getSuperclass();
                }
                instance = c.getConstructor(ctorParams).newInstance(fakes);
            }
            Class<?>[] paramTypes = new Class<?>[args.length];
            java.util.Arrays.fill(paramTypes, Object.class);
            return c.getMethod("apply", paramTypes).invoke(instance, args);
        } catch (java.lang.reflect.InvocationTargetException ite) {
            Throwable cause = ite.getCause();
            if (cause instanceof FakeMissException fm) {
                throw fm;   // a fake did not cover an input — reported as its own diagnostic
            }
            if (cause instanceof StackOverflowError) {
                // a non-tail `partial` recursion that does not terminate — a non-termination, not a
                // failed example (a tail-looping one is caught by the timeout instead)
                throw new NonTerminationException("recursion overflowed the stack");
            }
            throw new AbortException(cause == null ? "aborted" : String.valueOf(cause.getMessage()));
        } catch (ReflectiveOperationException e) {
            throw new AbortException(String.valueOf(e.getMessage()));
        }
    }

    private static String behaviorClass(String name) {
        return Character.toUpperCase(name.charAt(0)) + name.substring(1);
    }

    /** A fixture that cannot be built (an unsupported form, or an invariant a fixture value breaks). */
    private static final class FixtureException extends RuntimeException {
        FixtureException(String message) {
            super(message);
        }
    }

    /** The behavior aborted while evaluating a row (e.g. an invariant violation) — a failed example. */
    private static final class AbortException extends RuntimeException {
        AbortException(String message) {
            super(message);
        }
    }

    /** Evaluating a row did not finish within the budget — a `partial` recursion it reaches may not
     * terminate. Reported as its own diagnostic rather than hanging the compiler. */
    private static final class NonTerminationException extends RuntimeException {
        NonTerminationException(String message) {
            super(message);
        }
    }

    /** A fake table had no output for an input the behavior asked for (and no {@code _} default). */
    private static final class FakeMissException extends RuntimeException {
        FakeMissException(String message) {
            super(message);
        }
    }
}
