package souther.compiler;

import souther.compiler.check.BehaviorRequirement;
import souther.compiler.check.Symbols;
import souther.compiler.ast.Ast;
import souther.compiler.check.Sig;
import souther.compiler.types.Type;
import souther.compiler.types.TypeName;
import souther.compiler.check.TypeOps;
import souther.compiler.coverage.Probe;
import souther.compiler.diag.Diagnostic;
import souther.compiler.diag.Messages;
import souther.compiler.diag.SourcePos;
import souther.compiler.diag.SourceRef;
import souther.compiler.observe.Disposition;
import souther.compiler.observe.FailurePhase;
import souther.compiler.observe.Incompleteness;
import souther.compiler.observe.ObservedValue;
import souther.compiler.observe.RowOutcome;
import souther.compiler.observe.Stage;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * Evaluates a module's {@code example}s at compile time and reports any mismatch as a compile error.
 * It mirrors {@link Runner}: it decodes each row's input expressions into the target
 * behavior's parameter types through their derived decoders, applies the behavior via reflection on
 * the just-generated bytecode ({@link MemoryClassLoader}), and compares the result against the
 * expected arm (a bare type name) or value (a construction/literal). A failing example fails the
 * build, exactly as a construction whose constant argument breaks its invariant does.
 *
 * <p>A behavior with a {@code let} body and a {@code >->} composition are evaluable; an injected
 * target is refused ({@code E1902}) — you fake one, you do not example it. A composition is applied
 * as the class its module emits, so the stages run in order and a case that leaves the main line is
 * what the row sees, with no second implementation of what {@code >->} means.
 * A {@code depends on} dependency is satisfied by a fake supplied at the example: a
 * {@code with dep = value} on the row (a constant/value dependency) or a {@code fake dep | table}
 * declaration (an input-keyed function dependency). Each fake is a {@code Behavior} proxy passed to
 * the generated behavior's injecting constructor — it produces no run-time class. Inputs, expected
 * values, and fake entries are fixtures — literals, newtype constructions, record constructions, and
 * helpers applied to those (ADR-0077).
 *
 * <p>Two things a row needs are not here, because they are not about what an example means:
 * {@link FixtureReader} reads what a fixture states as the value it states — through
 * {@link NeutralForm} for the form a decoder reads and {@link HelperInvoker} for a helper run as the
 * method its module emits — and {@link RowEvaluation} owns the state one row builds up while it is
 * evaluated.
 */
public final class ExampleVerifier {

    /**
     * Evaluates every example in {@code module}; returns one diagnostic per failing example row
     * (empty when all pass). Does not throw for a failed example — the caller aggregates. A fixture
     * of an imported type decodes against its declaring module's package, which its
     * {@link TypeName} names (a cross-module example).
     *
     * <p>Classes this compile did not generate resolve under {@code parent} — where an example calls
     * into a module that was compiled by another project, that is the loader its classes come from.
     *
     * <p>{@code requirements} says what each behavior takes injected and in what order: the fakes a
     * row supplies are passed to the injecting constructor in that order, which is the same answer
     * the emitter built that constructor from.
     *
     * <p>{@code values} are the values a row may name beyond this module's own: the ones its imports
     * bring in, each already closed over the module that published it (ADR-0074).
     */
    public static Observations check(Ast.Module module, Symbols symbols, Map<String, Sig> sigs,
                                     Map<String, byte[]> classes,
                                     Map<String, List<BehaviorRequirement>> requirements,
                                     ClassLoader parent, Map<String, Ast.FnDef> values,
                                     String sourceId, long budgetMs) {
        if (module.examples().isEmpty()) {
            return Observations.NONE;
        }
        MemoryClassLoader loader = new MemoryClassLoader(classes, parent);
        ExampleVerifier v = new ExampleVerifier(module, symbols, sigs, requirements, loader, values,
                budgetMs);
        v.sourceId = sourceId;
        List<Diagnostic> failures = new ArrayList<>();
        List<RowOutcome> rows = new ArrayList<>();
        List<Incompleteness> incompleteness = new ArrayList<>();
        for (Ast.Example ex : module.examples()) {
            try {
                v.checkExample(ex, failures, rows);
            } catch (LinkageError _) {
                // The runtime is not on this host's classpath (it is `provided`, like CTFE), so the
                // generated classes cannot be loaded to evaluate here; the build-time pass, where the
                // runtime is present, still checks this example. Nothing was observed, and a measure
                // that read the empty result as "no row covers this" would report a gap nobody left.
                incompleteness.add(Incompleteness.at(Incompleteness.Code.RUNTIME_ABSENT,
                        Incompleteness.Scope.BEHAVIOR, ex.target(),
                        new SourceRef(sourceId, ex.pos())));
            }
        }
        // A row that could not be decided is read here rather than restated at each place it happens,
        // so what a measure sees and what stopped it can never disagree.
        for (RowOutcome outcome : rows) {
            if (outcome.disposition() == Disposition.INCOMPLETE) {
                incompleteness.add(new Incompleteness(Incompleteness.Code.ROW_TIMED_OUT,
                        Incompleteness.Scope.BEHAVIOR, outcome.target(),
                        java.util.Optional.of(outcome.at())));
            }
        }
        return new Observations(failures, rows, incompleteness);
    }

    // --- two statements about one behavior -----------------------------------------------------

    /**
     * Every input for which two of this module's written statements about one behavior answer
     * differently.
     *
     * <p>{@code module} is the whole module — every row and every fake, whichever source wrote it. A
     * fake and the rows it disagrees with need not be in one file, so neither side can be found from
     * one source's share of them. {@code exampleOrigins} and {@code fakeOrigins} say which source each
     * came from, in the order {@code module} holds them.
     *
     * <p>No behavior is applied. What a fake answers for an input is decided by the rule the fake
     * itself dispatches with ({@link #standingIn}) — the same rule, not a second reading of it — and
     * the two answers are compared as the written values they are built into.
     */
    public static Readings disagreements(Ast.Module module, Symbols symbols,
                                         Map<String, Sig> sigs, Map<String, byte[]> classes,
                                         Map<String, List<BehaviorRequirement>> requirements,
                                         ClassLoader parent, Map<String, Ast.FnDef> values,
                                         List<String> exampleOrigins,
                                         List<String> fakeOrigins, long budgetMs) {
        if (module.examples().isEmpty()
                || exampleOrigins.size() != module.examples().size()
                || fakeOrigins.size() != module.fakes().size()) {
            return Readings.NONE;
        }
        // Which behaviors have both a stand-in and rows of their own, read off the text. Two written
        // statements are what this is about, and where there are not two there is nothing to build:
        // a module whose faked behaviors are exampled nowhere — which is most of them, since a fake is
        // written so that some *other* behavior's rows can run — is settled here, before a class is
        // loaded or a worker is started.
        Set<String> contested = contested(module, sigs);
        if (contested.isEmpty()) {
            return Readings.NONE;
        }
        ExampleVerifier v = new ExampleVerifier(module, symbols, sigs, requirements,
                new MemoryClassLoader(classes, parent), values, budgetMs);
        return v.collectDisagreements(exampleOrigins, fakeOrigins, contested);
    }

    /**
     * What building this module's fake tables says about the ones {@code sourceId} wrote, each built
     * once.
     *
     * <p>Because they are written, not because something reads them. A table is built to stand in for
     * a behavior ({@link #resolveFake}) and to be read against the rows recorded for it ({@link
     * #againstFake}), and a module can write one that neither of those reaches: nothing in it depends
     * on the faked behavior, and no row records what that behavior owes. The table still states what
     * it states, and what is wrong with it is wrong wherever it is read from.
     *
     * <p>The one place it is said, so a build and a row cannot come to two answers about one table.
     * A row that applies a fake it could not build says nothing about the table any more — it does not
     * run, and the error at the fake is what the compile fails on — which also ends the same table
     * being reported once per row that reaches it.
     *
     * <p>The tables that answer, which is what the other two readers build: the first one written for
     * a dependency. A second written for the same name stands in for nothing and is read by nobody,
     * so building it here would hold a table to something no reader of it would ever ask.
     *
     * <p>{@code fakeOrigins} says which source wrote each of {@code module.fakes()}, in that order —
     * every fake, since which one answers for a dependency is a fact about the module and not about
     * one of its files. Where it does not line up with them, every table that answers is built here:
     * a report in the wrong file is a report, and the reason to know the file is to place it, while
     * nothing else would say what is wrong with the table at all.
     */
    public static List<Diagnostic> fakeTables(Ast.Module module, Symbols symbols,
                                              Map<String, Sig> sigs, Map<String, byte[]> classes,
                                              Map<String, List<BehaviorRequirement>> requirements,
                                              ClassLoader parent, Map<String, Ast.FnDef> values,
                                              List<String> fakeOrigins, String sourceId,
                                              long budgetMs) {
        if (module.fakes().isEmpty()) {
            return List.of();
        }
        boolean placed = fakeOrigins.size() == module.fakes().size();
        ExampleVerifier v = new ExampleVerifier(module, symbols, sigs, requirements,
                new MemoryClassLoader(classes, parent), values, budgetMs);
        v.sourceId = sourceId;
        List<Diagnostic> said = new ArrayList<>();
        Set<String> answering = new LinkedHashSet<>();
        for (int i = 0; i < module.fakes().size(); i++) {
            Ast.Fake fk = module.fakes().get(i);
            if (!answering.add(fk.target())) {
                continue;   // a second table for one dependency answers nothing, here as anywhere
            }
            if (placed && !fakeOrigins.get(i).equals(sourceId)) {
                continue;   // written in another source, and built by that source's own reading
            }
            Sig sig = sigs.get(fk.target());
            if (sig == null) {
                continue;   // a fake for no behavior of this module; its target is its own question
            }
            // Within a budget of its own, for the reason a row and a reading each have one: a row of
            // the table applies helpers, and a `partial` one may not stop. Nothing before this change
            // built the table of a fake nothing reads, so this is the first thing that would run it.
            Read<List<Diagnostic>> read = v.within(reader -> {
                List<Diagnostic> wrong = new ArrayList<>();
                reader.standins(fk, sig.ins(), sig.out(), wrong);
                return wrong;
            }, "the `fake " + fk.target() + "` table");
            switch (read) {
                case Read.Got(List<Diagnostic> wrong) -> said.addAll(wrong);
                case Read.TimedOut(long ranOutOf) -> said.add(uncheckedFake(fk, ranOutOf));
                // Not about this fake: the runtime is `provided`, so a host without it builds no value
                // at all and every fake in every module would say the same thing. Where the rows are
                // evaluated that is recorded once, as an incompleteness.
                case Read.RuntimeAbsent() -> { }
            }
        }
        return List.copyOf(said);
    }

    /**
     * What one reading came to: the statement, or the reason there is no statement.
     *
     * <p>The reason is answered rather than dropped because the two reasons are held against
     * different things. A statement that did not finish is about this module, and where nothing else
     * builds what it was reading it is this reading's to say; a host with no runtime is about the
     * host, and says the same thing about every fake and every row in every module compiled on it.
     * A reader that got only "nothing was read" would have to pick one of those, and each caller
     * would pick for itself.
     */
    private sealed interface Read<T> {

        /** What the reading answered. Null where the statement is written in a form that states
         * nothing — an input that will not build, an expectation that cannot be read. */
        record Got<T>(T value) implements Read<T> {}

        /** The reading ran out of its budget, and the budget it ran out of: what a report has to
         * name is what the wait was actually held to, not what a second reader of the setting
         * makes of it later. */
        record TimedOut<T>(long budgetMs) implements Read<T> {}

        /** This host has no runtime to build a value against. */
        record RuntimeAbsent<T>() implements Read<T> {}

        /** What was read, or null — for a caller that has nothing of its own to say about why
         * there is nothing. Both reasons come out the same here on purpose: the reading that did
         * not happen is reported by whoever else reads the same statement. */
        default T orNull() {
            return this instanceof Got(T value) ? value : null;
        }
    }

    /**
     * One statement, read within its own share of the budget.
     *
     * <p>Per statement rather than per module. Building a fixture runs the helpers it applies
     * (ADR-0077), and a `partial` one may not stop — so a budget covering the whole reading is one a
     * single slow row can spend, and spending it would drop every other statement's reading with it:
     * a plain contradiction elsewhere in the module would go unsaid because of a row it has nothing
     * to do with. It is what {@link #checkRow} already does for a row it evaluates, and this reads
     * strictly fewer statements than that evaluates rows.
     *
     * <p>What did not finish states nothing. Who says so is the caller's, and differs: a row and a
     * {@code with} written on one are evaluated elsewhere and report it there (E1910), while a fake
     * table is built here and, where no row depends on the behavior it stands in for, nowhere else.
     */
    private <T> Read<T> within(java.util.function.Function<ExampleVerifier, T> read,
                               String what) {
        // On its own reader. A worker that runs out of budget is asked to stop and cannot be made to
        // — a fixture reaches no interrupt point — so it may still be inside `expandedValue`, holding
        // a binding or a half-walked expansion. Nothing it can still write to is read by the
        // statement after it, which is why {@link RowEvaluation} does the same for a row.
        ExampleVerifier reader = new ExampleVerifier(module, symbols, sigs, requirements, loader,
                values, budgetMs);
        reader.sourceId = sourceId;
        java.util.concurrent.FutureTask<T> task =
                new java.util.concurrent.FutureTask<>(() -> read.apply(reader));
        Thread worker = new Thread(task, "souther-reading");
        worker.setDaemon(true);
        worker.start();
        try {
            return new Read.Got<>(
                    task.get(budgetMs, java.util.concurrent.TimeUnit.MILLISECONDS));
        } catch (java.util.concurrent.TimeoutException _) {
            task.cancel(true);
            return new Read.TimedOut<>(budgetMs);
        } catch (java.util.concurrent.ExecutionException ee) {
            task.cancel(true);
            Throwable cause = ee.getCause();
            // One thing ends a reading without the model or this code being at fault: a host with no
            // runtime to build a value against, since the runtime is `provided` (as it is for CTFE).
            if (runtimeAbsent(cause)) {
                return new Read.RuntimeAbsent<>();
            }
            // Anything else is this code being wrong. An empty reading says the statements agree, so
            // answering with one would leave a broken compiler reporting every model consistent, and
            // only a test that reached the broken shape would ever say otherwise.
            if (cause instanceof RuntimeException runtime) {
                throw runtime;
            }
            if (cause instanceof Error error) {
                throw error;
            }
            throw new IllegalStateException(cause);
        } catch (InterruptedException _) {
            task.cancel(true);
            Thread.currentThread().interrupt();
            throw new java.util.concurrent.CancellationException("interrupted while reading " + what);
        }
    }

    /**
     * Whether {@code cause} is this host having no runtime rather than anything being wrong.
     *
     * <p>The runtime is {@code provided}, so a build that compiles Souther without it on the class
     * path can generate the classes and not load them. That is the one {@link LinkageError} that says
     * nothing about the model or about this code — the rest of the family says a class was generated
     * or loaded wrong ({@code VerifyError}, {@code ClassFormatError}, {@code NoSuchMethodError}), and
     * reading those as "no runtime" would let a broken back end report every model consistent.
     */
    private static boolean runtimeAbsent(Throwable cause) {
        return cause instanceof NoClassDefFoundError missing
                && missing.getMessage() != null
                && missing.getMessage().replace('/', '.').startsWith("souther.runtime.");
    }

    /** The behaviors this module both stands in for — the target of a {@code fake}, the dependency a
     * {@code with} that takes no input answers for ({@link #againstWiths}) — and records rows of. */
    private static Set<String> contested(Ast.Module module, Map<String, Sig> sigs) {
        Set<String> stoodIn = new LinkedHashSet<>();
        for (Ast.Fake fk : module.fakes()) {
            stoodIn.add(fk.target());
        }
        for (Ast.Example ex : module.examples()) {
            for (Ast.ExampleRow row : ex.rows()) {
                for (Ast.With w : row.withs()) {
                    Sig depSig = sigs.get(w.dep());
                    if (depSig != null && depSig.ins().isEmpty()) {
                        stoodIn.add(w.dep());
                    }
                }
            }
        }
        Set<String> both = new LinkedHashSet<>();
        for (Ast.Example ex : module.examples()) {
            if (stoodIn.contains(ex.target())) {
                both.add(ex.target());
            }
        }
        return both;
    }

    /** One recorded row, read as far as it can be without running it. What it says is left as written
     * — rendering it builds the fixture a second time, and only a row that turns out to disagree is
     * ever shown. */
    private record RecordedRow(SourceRef at, Ast.Expr expected, Object[] arguments, Asserted answer) {}

    private Readings collectDisagreements(List<String> exampleOrigins,
                                          List<String> fakeOrigins, Set<String> contested) {
        Map<String, List<RecordedRow>> recorded = new LinkedHashMap<>();
        for (int i = 0; i < module.examples().size(); i++) {
            Ast.Example ex = module.examples().get(i);
            if (contested.contains(ex.target())) {
                readRecorded(ex, exampleOrigins.get(i), recorded);
            }
        }
        if (recorded.isEmpty()) {
            return Readings.NONE;
        }
        List<Disagreement> found = new ArrayList<>();
        List<TimedOutFake> timedOut = new ArrayList<>();
        // The first table for a dependency is the one that answers ({@link #resolveFake}); a second
        // one written for the same name never stands in for anything, so it states nothing to
        // disagree with. What that second table is, is its own question.
        Set<String> answering = new LinkedHashSet<>();
        for (int j = 0; j < module.fakes().size(); j++) {
            Ast.Fake fk = module.fakes().get(j);
            if (answering.add(fk.target())) {
                againstFake(fk, fakeOrigins.get(j), recorded, found, timedOut);
            }
        }
        for (int i = 0; i < module.examples().size(); i++) {
            againstWiths(module.examples().get(i), exampleOrigins.get(i), recorded, found);
        }
        return new Readings(found, timedOut);
    }

    /**
     * The rows of one example, as much of each as is comparable.
     *
     * <p>A row is read here the way the evaluator reads it: its arity against the signature, its
     * inputs built against their parameter types, and its expectation against the output's cases and
     * then built. A row that fails any of those states nothing — each is reported as the arity, input,
     * arm or fixture error it is where the row is evaluated — and a row read otherwise here than there
     * would be held to a stand-in on an assertion the model itself refuses.
     */
    private void readRecorded(Ast.Example ex, String origin, Map<String, List<RecordedRow>> into) {
        Sig sig = sigs.get(ex.target());
        if (sig == null) {
            return;
        }
        Set<TypeName> cases = outCases(sig.out());
        for (Ast.ExampleRow row : ex.rows()) {
            if (row.inputs().size() != sig.ins().size()) {
                continue;
            }
            Read<RecordedRow> read = within(reader -> {
                Object[] arguments = reader.builtOrNull(row.inputs(), sig.ins());
                if (arguments == null) {
                    return null;
                }
                Asserted answer = reader.readExpected(row.expected(), sig.out(), cases);
                return answer instanceof Asserted.Unreadable ? null
                        : new RecordedRow(new SourceRef(origin, row.expected().pos()),
                                row.expected(), arguments, answer);
            }, "a row of `" + ex.target() + "`");
            // A reading that did not finish is not said here, whichever reason ended it. The same row
            // is evaluated where the example is checked, which builds these fixtures and then runs the
            // behavior on top of them, so a fixture that overruns this overruns that too and is E1910
            // there, at the row.
            RecordedRow got = read.orNull();
            if (got == null) {
                continue;
            }
            into.computeIfAbsent(ex.target(), _ -> new ArrayList<>()).add(got);
        }
    }

    /** One fake against the rows recorded for the behavior it stands in for. */
    private void againstFake(Ast.Fake fk, String origin, Map<String, List<RecordedRow>> recorded,
                             List<Disagreement> found, List<TimedOutFake> timedOut) {
        List<RecordedRow> rows = recorded.get(fk.target());
        Sig sig = sigs.get(fk.target());
        if (rows == null || sig == null) {
            return;
        }
        // The whole table, built the one way the proxy builds it.
        Read<Standins> read = within(
                reader -> reader.standins(fk, sig.ins(), sig.out(), new ArrayList<>()),
                "the `fake " + fk.target() + "` table");
        // A switch, so that a fourth reason for a reading to end has to decide what a fake does about
        // it rather than falling in with one of these.
        switch (read) {
            // Said here, because here is where it can be. The other place a table is built is
            // `resolveFake`, which runs while a row of a behavior that *depends on* this one is
            // evaluated — and a fake nothing depends on has no such row, so an overrun that went
            // unsaid here would leave "the two agree" as the answer to a comparison never made.
            // The caret goes on the target, which is what `fk.pos()` is.
            case Read.TimedOut(long budgetMs) -> {
                timedOut.add(new TimedOutFake(fk.target(), new SourceRef(origin, fk.pos()),
                        fk.target().length(), budgetMs));
                return;
            }
            // Not about this fake. The runtime is `provided`, so a host without it builds no value at
            // all, and every fake and every row in the module would say the same thing; what was not
            // read for that reason is recorded once, where the rows are evaluated. Defensive: with no
            // runtime no recorded row builds either, and a reading with no rows read never reaches a
            // fake — so nothing arrives here today.
            case Read.RuntimeAbsent() -> {
                return;
            }
            case Read.Got(Standins _) -> { }
        }
        // The whole table or nothing: a table with a row that will not build answers nothing here,
        // and what is wrong with it is reported where the fake is written ({@link #fakeTables}).
        Standins table = read.orNull();
        if (table == null) {
            return;
        }
        for (RecordedRow row : rows) {
            Standin answering = standingIn(table, row.arguments());
            if (answering == null) {
                continue;   // the table answers nothing for this input; E1909's where it is used
            }
            Asserted stood = new Asserted.Whole(answering.answer());
            if (differs(row.answer(), stood)) {
                // The output, not the row: what disagrees is the answer, and the marker lands on it
                // the way a row's does on its expected.
                found.add(new Disagreement(fk.target(),
                        said(row.at(), row.expected(), row.answer()),
                        said(new SourceRef(origin, answering.row().output().pos()),
                                answering.row().output(), stood),
                        false));
            }
        }
    }

    /**
     * The {@code with}s on the rows of one example, against the rows recorded for the dependency each
     * stands in for — where the dependency takes no input, and there only.
     *
     * <p>A {@code with} is a fixture bound to the run of the row it is written on, not a statement
     * about the dependency. It answers whatever it is asked, but that is a fact about the function it
     * installs, not about which of the dependency's inputs it was written for: what reaches the
     * dependency is whatever the parent behavior computes and passes — a normalised field, one of two
     * branches, one of several calls — and none of that is readable from the {@code with}. Held
     * against every recorded row, it would drop the parent row's own input and read a row-local
     * assumption as a claim about all of them, so two rows faking two different answers for two
     * different orders would be reported as contradicting each other while both are right.
     *
     * <p>A dependency that takes nothing has one input, {@code ()}, so a {@code with} for it and a row
     * recorded for it are about the same call, and the comparison is the same one a {@code fake} row
     * gets. A fake row states its own inputs, which is why it needs no such condition: the recorded
     * input picks the row that answers it ({@link #standingIn}), with nothing evaluated in between.
     *
     * <p>A {@code with} takes precedence over a {@code fake} table while the row carrying it runs
     * (see {@link #resolveFake}). That is dispatch, and it is not brought here: the table is still a
     * statement about the same behavior, written for every other row and every other run, and a
     * {@code with} beside it does not settle what it states.
     */
    private void againstWiths(Ast.Example ex, String origin, Map<String, List<RecordedRow>> recorded,
                              List<Disagreement> found) {
        for (Ast.ExampleRow row : ex.rows()) {
            for (Ast.With w : row.withs()) {
                List<RecordedRow> rows = recorded.get(w.dep());
                Sig depSig = sigs.get(w.dep());
                if (rows == null || depSig == null || !depSig.ins().isEmpty()) {
                    continue;
                }
                // As with a recorded row: a `with` is written on a row, and that row is evaluated
                // where the example is checked, installing this same value. What did not finish here
                // did not finish there, and there is where it is said (E1910).
                Asserted constant = within(
                        reader -> reader.readStandIn(w.value(), depSig.out(), outCases(depSig.out())),
                        "a `with " + w.dep() + "`").orNull();
                if (constant == null || constant instanceof Asserted.Unreadable) {
                    continue;
                }
                for (RecordedRow recordedRow : rows) {
                    if (differs(recordedRow.answer(), constant)) {
                        found.add(new Disagreement(w.dep(),
                                said(recordedRow.at(), recordedRow.expected(), recordedRow.answer()),
                                said(new SourceRef(origin, w.value().pos()), w.value(), constant),
                                true));
                    }
                }
            }
        }
    }

    /**
     * One statement, with what it answers rendered — done here, where a disagreement is known, so a
     * row that agrees never pays for a description nobody reads.
     *
     * <p>The marker is measured off the written expression and not off the rendering. The rendering is
     * the value the encoder writes, which is a different length from the text it was written as — a
     * date is its ISO form, a qualified case name is its short one — so a marker measured from it
     * underlines the wrong columns and can run past the end of the line.
     */
    private Statement said(SourceRef at, Ast.Expr written, Asserted asserted) {
        return new Statement(at, souther.compiler.check.Elaborator.width(written), shown(asserted));
    }

    /** What an assertion says, from what was already read. Rendering from the text again would build
     * the fixture a second time — running whatever helpers it applies, outside the budget the first
     * reading was held to — and could show a value other than the one that was compared. */
    private String shown(Asserted asserted) {
        return switch (asserted) {
            case Asserted.CaseOnly only -> only.name().name();
            case Asserted.Whole whole -> describeActual(whole.fixture().value());
            case Asserted.Unreadable _ ->
                    throw new IllegalStateException("nothing was read, so nothing disagreed");
        };
    }

    /** The written inputs decoded against {@code types}, or null where one would not build — that is
     * <em>E1903</em>'s to say where the row is evaluated, and a row whose inputs are not values names
     * no input to hold a stand-in against. */
    private Object[] builtOrNull(List<Ast.Expr> written, List<Type> types) {
        Object[] values = new Object[types.size()];
        for (int i = 0; i < types.size(); i++) {
            try {
                values[i] = built(written.get(i), types.get(i));
            } catch (FixtureException | NonTerminationException _) {
                return null;
            }
        }
        return values;
    }

    /**
     * Whether a value composed elsewhere can be built at this module's boundary.
     *
     * <p>The question a generator cannot answer for itself. Which values a type admits together is the
     * derived decoder's business — an invariant relating two fields refuses a pair that each field
     * would have accepted alone — so the only way to know is to put the value through the decoder that
     * a row's own fixture goes through.
     */
    @FunctionalInterface
    public interface Construction {

        /** Empty where the value builds; why it did not, otherwise. Throws {@link LinkageError} where
         * the runtime is absent, which is not a fact about the value. */
        java.util.Optional<String> refuse(Type type, Ast.Expr fixture);
    }

    /** A way to build values against this module's generated classes, without any rows to run. */
    public static Construction constructing(Ast.Module module, Symbols symbols,
                                            Map<String, Sig> sigs, Map<String, byte[]> classes,
                                            Map<String, List<BehaviorRequirement>> requirements,
                                            ClassLoader parent, Map<String, Ast.FnDef> values) {
        // No rows, so no worker is started and the budget is never read; the default stands in for a
        // value this reader has no use for.
        ExampleVerifier v = new ExampleVerifier(module, symbols, sigs, requirements,
                new MemoryClassLoader(classes, parent), values, DEFAULT_BUDGET_MS);
        return v.fixtures::refuse;
    }

    /**
     * What evaluating a source's rows turned up: the diagnostics it reports, the observation each row
     * left, and what stopped it from observing.
     *
     * <p>Not named {@code Result} because {@code net.unit8.raoh.Result} is what a decoder answers with
     * here, and a nested type of that name would take the spelling away from it.
     */
    public record Observations(List<Diagnostic> failures, List<RowOutcome> rows,
                               List<Incompleteness> incompleteness) {

        public static final Observations NONE = new Observations(List.of(), List.of(), List.of());

        public Observations {
            failures = List.copyOf(failures);
            rows = List.copyOf(rows);
            incompleteness = List.copyOf(incompleteness);
        }
    }

    /**
     * One written statement about what a behavior answers, and where it is written.
     *
     * <p>{@code answer} is rendered here rather than at the report, because reading it needs the
     * decoders and the module's classes and the report has neither.
     */
    public record Statement(SourceRef at, int width, String answer) {}

    /**
     * One input for which two written statements about a behavior answer differently.
     *
     * <p>Neither side is derived from the other: the recorded row says what the behavior will owe, the
     * stand-in says what it answers while some other behavior's row runs. Which is right is not
     * readable here — a model being migrated onto may run against a stand-in while the real answer is
     * still being harvested, and that is written the way a mistake is. So both are named and neither
     * is ranked.
     *
     * <p>Independent of which source is being reported: one disagreement is projected onto both of the
     * sources its two statements are written in.
     *
     * @param viaWith whether the stand-in is a {@code with} rather than a {@code fake} row — the
     *                report names the form the author wrote, so it has to be told which one it is
     */
    public record Disagreement(String behavior, Statement recorded, Statement standIn,
                               boolean viaWith) {}

    /**
     * A fake whose table did not finish being built within the budget, so what it states and what the
     * rows recorded for the behavior state were never compared.
     *
     * <p>Carries what it takes to report it. The position and its width are measured here, where the
     * text is, the way a {@link Statement}'s are; the budget is the one the wait was actually held to,
     * rather than a second reading of the setting taken later, which a budget that stops being one
     * number for the whole compile would make wrong with nothing to say so.
     *
     * @param at where the fake names the behavior it stands in for, which is what the report marks
     */
    public record TimedOutFake(String target, SourceRef at, int width, long budgetMs) {}

    /**
     * What reading a module's written statements against each other came to.
     *
     * <p>Both lists, because a reading that did not finish and a reading that found nothing are
     * different answers and an empty list of disagreements is what the second one looks like. Which
     * of the two a compile got can otherwise turn on machine load, between a build and the next
     * keystroke in the editor.
     */
    public record Readings(List<Disagreement> disagreements, List<TimedOutFake> timedOut) {

        public static final Readings NONE = new Readings(List.of(), List.of());

        public Readings {
            disagreements = List.copyOf(disagreements);
            timedOut = List.copyOf(timedOut);
        }
    }

    /** The one-line form for a set of failures gathered across modules: the count, then the first
     * one's reason, matching what a single module's aggregate says. */
    public static String legacySummary(List<Diagnostic> failures) {
        Diagnostic first = failures.get(0);
        return failures.size() == 1
                ? legacyOf(first)
                : failures.size() + " examples do not hold; " + legacyOf(first);
    }

    /** A one-line message for a failing example, used where only the legacy string is shown (the LSP
     * surfaces this rather than the rendered catalog message). */
    private static String legacyOf(Diagnostic d) {
        if (d.diff() != null) {
            // JUnit order: the expected value (what the example asserts) first, then what the
            // behavior actually produced.
            return "example does not hold: expected " + d.diff().expectedType()
                    + " but was " + d.diff().actualType();
        }
        // A diff-less failure (an input fixture that could not be built, a missing fake, a
        // non-termination): render the diagnostic's own catalog message so the reason travels
        // through the annotation processor, rather than collapsing to a bare "example failed".
        if (d.messageKey() != null) {
            return Messages.get(d.messageKey(), Messages.defaultLocale(), d.args());
        }
        return "example failed";
    }

    private final Ast.Module module;
    private final Symbols symbols;
    private final Map<String, Sig> sigs;
    /** What each behavior of this module takes injected, in the order its constructor takes it. */
    private final Map<String, List<BehaviorRequirement>> requirements;
    private final MemoryClassLoader loader;
    /** The values a row may name: this module's own, and the ones its imports bring in. */
    private final Map<String, Ast.FnDef> values;
    /** Reads what a fixture states as the value it states. One evaluation's, because what it builds
     * up while it reads — which values it is expanding, which helper it is in — is one row's. */
    private final FixtureReader fixtures;
    /** Which source the rows being evaluated are written in. A module's rows come from its own source
     * and from any number of attached {@code examples for} files, and a position alone stops saying
     * which once they are gathered under the module's name. */
    private String sourceId;
    /** Wall-clock budget for one thing built and run on a worker of its own: an example row evaluated
     * ({@link #checkRow}), or one written statement read to compare it against another ({@link
     * #within}). Carried rather than looked up, so a reader started by another reader is held to the
     * same budget its caller was, and two compiles in one JVM need not agree on it. */
    private final long budgetMs;

    private ExampleVerifier(Ast.Module module, Symbols symbols, Map<String, Sig> sigs,
                            Map<String, List<BehaviorRequirement>> requirements,
                            MemoryClassLoader loader, Map<String, Ast.FnDef> values,
                            long budgetMs) {
        this.module = module;
        this.symbols = symbols;
        this.sigs = sigs;
        this.requirements = requirements;
        this.loader = loader;
        this.values = values;
        this.budgetMs = budgetMs;
        this.fixtures = new FixtureReader(module, symbols, values, loader);
    }

    // --- what a fixture states, read by {@link FixtureReader} ----------------------------------
    //
    // One reader per evaluation, reached through the field above. Each of these is the call that
    // was an instance method of this class before the reader was its own; the callers still read
    // as they did, and which of them have to hold the *same* reader is the next question.

    private Object built(Ast.Expr written, Type type) {
        return fixtures.built(written, type);
    }

    private FixtureReader.BuiltFixture buildFixture(Ast.Expr written, Type outType) {
        return fixtures.buildFixture(written, outType);
    }

    private Object builtExpected(Ast.Expr expected, Type outType) {
        return fixtures.builtExpected(expected, outType);
    }

    private String caseOnly(Ast.Expr expected) {
        return fixtures.caseOnly(expected);
    }

    private TypeName constructedCase(Ast.Expr e) {
        return fixtures.constructedCase(e);
    }

    private String expectedArm(Ast.Expr expected) {
        return fixtures.expectedArm(expected);
    }

    private String describeExpected(Ast.Expr expected, Type outType) {
        return fixtures.describeExpected(expected, outType);
    }

    private String describeActual(Object result) {
        return fixtures.describeActual(result);
    }

    private ObservedValue observed(Object decoded) {
        return fixtures.observed(decoded);
    }

    // --- one example (a target and its rows) --------------------------------------------------

    private void checkExample(Ast.Example ex, List<Diagnostic> out, List<RowOutcome> rows) {
        ExampleTarget target = targetOf(ex.target());
        if (target == null) {
            out.add(notRunnable(ex));
            return;
        }
        Sig sig = sigs.get(target.name());
        if (sig == null) {
            throw new IllegalStateException("`" + target.name() + "` is evaluable but has no signature");
        }
        Set<TypeName> outCases = outCases(sig.out());
        for (Ast.ExampleRow row : ex.rows()) {
            checkRow(target, sig, outCases, row, out, rows);
        }
    }

    /**
     * What a row runs: the behavior's name, and what it takes injected in the order its constructor
     * takes it.
     *
     * <p>Which kind of behavior it is does not survive to here. A row applies the class the module
     * emitted, and that class is reached the same way whichever way the behavior was written — the
     * name says which, and the requirements say what to hand it.
     */
    private record ExampleTarget(String name, List<BehaviorRequirement> requirements,
                                 boolean pending) {}

    /**
     * The behavior a row is about, and whether there is anything to run it against.
     *
     * <p>A behavior with a {@code let} body and a {@code >->} composition are applied; an injected one
     * has no body yet, so its rows are <em>recorded</em> rather than evaluated (spec
     * {@code example-pending}). That is not a lesser state: a model being migrated onto is injected
     * everywhere at the start, and the rows harvested from the system it replaces are what says what
     * each behavior owes. They are checked as far as they can be — every fixture is built, so a value
     * that breaks an invariant is found the day it is written — and evaluation begins by itself the
     * moment a {@code let} arrives.
     *
     * <p>Null when this module declares no behavior of that name; what to say about that is
     * {@link #notRunnable}'s.
     *
     * <p>A composition is run by applying the class its module emits, the same class normal execution
     * applies. Its stages with a body are constructed by it and handed the fields they need, so what
     * a row has to supply are the injected behaviors the stages reach — which is what its requirement
     * list holds, in the order its constructor takes them.
     */
    private ExampleTarget targetOf(String name) {
        for (Ast.BehaviorDef b : module.behaviors()) {
            if (!b.name().equals(name)) {
                continue;
            }
            return new ExampleTarget(name, requirements.getOrDefault(name, List.of()),
                    isPending(module, name));
        }
        return null;
    }

    /**
     * Whether a behavior of {@code module} has no implementation to run — an injected one (spec
     * {@code injected-behavior}).
     *
     * <p>Asked here by the row evaluation and by the adequacy report, which decides what it can measure
     * from the same answer. Two statements of it would let a report say a behavior is implemented while
     * its rows are being recorded rather than run.
     */
    public static boolean isPending(Ast.Module module, String name) {
        for (Ast.BehaviorDef b : module.behaviors()) {
            if (b.name().equals(name)) {
                return b instanceof Ast.SpecBehavior && !hasFn(module, name);
            }
        }
        return false;
    }

    private boolean hasFn(String name) {
        return hasFn(module, name);
    }

    private static boolean hasFn(Ast.Module module, String name) {
        return module.fns().stream().anyMatch(f -> f.name().equals(name));
    }

    /** The injected behavior named {@code name} in this module (a SpecBehavior with no {@code let}),
     * i.e. a valid target for a fake; null if not found or not injected. */
    private Ast.SpecBehavior injectedSpec(String name) {
        for (Ast.BehaviorDef b : module.behaviors()) {
            if (b instanceof Ast.SpecBehavior spec && spec.name().equals(name) && !hasFn(name)) {
                return spec;
            }
        }
        return null;
    }

    /**
     * The diagnostic for a target this module declares no behavior for: a name it does not know
     * ({@code E1901}), or a helper {@code let} of that name ({@code E1902}).
     *
     * <p>Only reached when {@link #targetOf} found no behavior, so being injected is not one of the
     * reasons any more: an injected behavior is a behavior, and its rows are recorded. What is left
     * for {@code E1902} is a target that is not a behavior at all.
     */
    private Diagnostic notRunnable(Ast.Example ex) {
        String name = ex.target();
        boolean isHelper = module.fns().stream().anyMatch(f -> f.name().equals(name));
        if (!isHelper) {
            return Diagnostic.of("E1901", "check.example.unknown").title("check.example.title")
                    .at(ex.pos()).args(name).build();
        }
        return Diagnostic.of("E1902", "check.example.notrunnable").title("check.example.title")
                .at(ex.pos()).args(name)
                .hint("check.example.notrunnable.hint",
                        "it is a helper `let`, and this module declares no behavior of that name")
                .build();
    }

    // --- one row ------------------------------------------------------------------------------

    /**
     * One row's evaluation, and the state it builds up while it runs: its own diagnostics, and the
     * helper it is currently inside.
     *
     * <p>A row that does not finish leaves its worker running — a pure computation reaches no interrupt
     * point, so cancelling it is a request and not a stop. So nothing that worker can still write to is
     * read by the rows after it: the evaluation has its own {@link ExampleVerifier}, so the state a
     * fixture builds up (which values it is expanding, which helper it is in) belongs to this row, and
     * the diagnostics it produces are its own list, handed to the caller only when it finishes. A late
     * result is dropped rather than landing among another row's.
     */
    private static final class RowEvaluation implements java.util.concurrent.Callable<List<Diagnostic>> {

        private final ExampleVerifier evaluation;
        private final ExampleTarget target;
        private final Sig sig;
        private final Set<TypeName> outCases;
        private final Ast.ExampleRow row;
        private final RowState state = new RowState();

        RowEvaluation(ExampleVerifier of, ExampleTarget target, Sig sig,
                      Set<TypeName> outCases, Ast.ExampleRow row) {
            this.evaluation = new ExampleVerifier(of.module, of.symbols, of.sigs, of.requirements,
                    of.loader, of.values, of.budgetMs);
            this.evaluation.sourceId = of.sourceId;
            this.target = target;
            this.sig = sig;
            this.outCases = outCases;
            this.row = row;
        }

        /**
         * The row, and the arms it went through on the way.
         *
         * <p>The collecting is started and stopped here because a row is a thread: this worker runs
         * this row's body and nothing else, so what the probe saw on it is what this row reached. A row
         * that does not finish never gets here to read it, and the set goes with the thread's state —
         * which is what stops the next row on a reused worker from starting where this one left off.
         */
        @Override
        public List<Diagnostic> call() {
            List<Diagnostic> mine = new ArrayList<>();
            Probe.begin();
            try {
                evaluation.checkRowNow(target, sig, outCases, row, mine, state);
                state.hits = Probe.taken();
            } finally {
                Probe.end();
            }
            return mine;
        }

        /** The helper this row is inside, for the budget to name when the row does not finish. */
        String helper() {
            return evaluation.fixtures.runningHelper();
        }
    }

    /**
     * What a row's evaluation reached and saw.
     *
     * <p>{@link #stage} is written by the row's worker and read by the caller when the row runs out of
     * time — the one field read across that boundary, so it is the one field that is volatile. Whether
     * the row stopped in a fixture's helper or inside the behavior is exactly that difference, and a
     * timeout that cannot say which reports the same thing for two different problems.
     *
     * <p>Everything else is written by the worker and read only after it has finished, which the future
     * establishes: a row that does not finish has its state dropped rather than read.
     */
    private static final class RowState {
        private volatile Stage stage = Stage.NONE;
        private Disposition disposition = Disposition.FAILED;
        private FailurePhase failurePhase = FailurePhase.NONE;
        private TypeName expectedArm;
        private TypeName resultArm;
        private final List<TypeName> inputCases = new ArrayList<>();
        private final List<ObservedValue> inputs = new ArrayList<>();
        /** The arms this row went through, where the classes it ran were generated to say. Empty
         * otherwise, and empty for a row that did not finish — a set read from a row still running
         * would be some of the arms rather than the arms. */
        private Set<Integer> hits = Set.of();

        /** Records where the row stopped, and that it did. */
        void failed(FailurePhase phase) {
            this.disposition = Disposition.FAILED;
            this.failurePhase = phase;
        }

        /** Records that the row could not be decided — an absence of evidence, not a failure. */
        void incomplete(FailurePhase phase) {
            this.disposition = Disposition.INCOMPLETE;
            this.failurePhase = phase;
        }
    }

    /** What the row turned out to be, from the state its worker left. */
    private RowOutcome outcomeOf(ExampleTarget target, Ast.ExampleRow row, RowState state) {
        return new RowOutcome(new SourceRef(sourceId, row.pos()), target.name(), row.description(),
                state.stage, state.disposition, state.failurePhase, state.expectedArm, state.resultArm,
                state.inputCases, state.inputs, state.hits);
    }

    /**
     * One row, evaluated within the budget: building its fixtures, running the helpers they apply,
     * applying the behavior and comparing the result are one evaluation, so a row cannot buy more time
     * by applying more helpers (ADR-0077). Only this thread adds to {@code out} — see
     * {@link RowEvaluation} for why the row's own worker must not.
     */
    private void checkRow(ExampleTarget target, Sig sig, Set<TypeName> outCases, Ast.ExampleRow row,
                          List<Diagnostic> out, List<RowOutcome> rows) {
        RowEvaluation evaluation = new RowEvaluation(this, target, sig, outCases, row);
        java.util.concurrent.FutureTask<List<Diagnostic>> task =
                new java.util.concurrent.FutureTask<>(evaluation);
        Thread worker = new Thread(task, "souther-example-eval");
        worker.setDaemon(true);
        worker.start();
        try {
            out.addAll(task.get(budgetMs, java.util.concurrent.TimeUnit.MILLISECONDS));
            rows.add(outcomeOf(target, row, evaluation.state));
        } catch (java.util.concurrent.TimeoutException _) {
            // Read what the row was doing before cancelling: the interrupt may let the worker leave the
            // helper it is in, and then the reason would depend on which thread got there first.
            String helper = evaluation.helper();
            // Only the stage, which the worker publishes: the rest of its state is still being written.
            // How far it got is the difference between a fixture's helper that will not stop and a
            // behavior that will not stop, which is what the author has to know.
            Stage reached = evaluation.state.stage;
            task.cancel(true);   // best-effort: marks the task cancelled and interrupts the worker
            out.add(Diagnostic.of("E1910", "check.example.nonterminating").title("check.example.title")
                    .at(row.pos()).args("did not finish within " + budgetMs + "ms"
                            + (helper == null ? "" : " while calling `" + helper + "`")).build());
            rows.add(new RowOutcome(new SourceRef(sourceId, row.pos()), target.name(),
                    row.description(), reached, Disposition.INCOMPLETE, FailurePhase.TIMEOUT,
                    null, null, List.of(), List.of(), Set.of()));
        } catch (java.util.concurrent.ExecutionException ee) {
            Throwable cause = ee.getCause();
            if (cause instanceof NonTerminationException nt) {
                out.add(Diagnostic.of("E1910", "check.example.nonterminating")
                        .title("check.example.title").at(row.pos()).args(nt.getMessage()).build());
                evaluation.state.incomplete(FailurePhase.TIMEOUT);
                rows.add(outcomeOf(target, row, evaluation.state));
                return;
            }
            if (cause instanceof RuntimeException re) {
                throw re;
            }
            throw new IllegalStateException(cause);
        } catch (InterruptedException e) {
            // Whoever is compiling asked to stop. Nothing is known about this row — no result was
            // produced and no comparison was made — so this is not a failing example, and reporting it
            // as one would put a diagnostic on a model that may be correct.
            task.cancel(true);
            Thread.currentThread().interrupt();
            throw new java.util.concurrent.CancellationException(
                    "interrupted while evaluating an example of `" + target.name() + "`");
        }
    }

    private void checkRowNow(ExampleTarget target, Sig sig, Set<TypeName> outCases,
                             Ast.ExampleRow row, List<Diagnostic> out, RowState state) {
        List<Type> ins = sig.ins();
        if (row.inputs().size() != ins.size()) {
            out.add(Diagnostic.of("E1903", "check.example.arity").title("check.example.title")
                    .at(row.pos()).args(target.name(), ins.size(), row.inputs().size()).build());
            state.failed(FailurePhase.INPUT_FIXTURE);
            return;
        }
        Object[] args = new Object[ins.size()];
        for (int i = 0; i < ins.size(); i++) {
            try {
                args[i] = built(row.inputs().get(i), ins.get(i));
            } catch (FixtureException fe) {
                out.add(Diagnostic.of("E1903", "check.example.input").title("check.example.title")
                        .at(row.pos()).args(target.name(), i + 1, fe.getMessage()).build());
                state.failed(FailurePhase.INPUT_FIXTURE);
                return;
            }
            state.inputCases.add(caseWritten(row.inputs().get(i)));
            state.inputs.add(observed(args[i]));
        }
        // validate the expected arm/value against the output cases before running. Which case the row
        // asserts is read through what it names, so a row may name a value where it may name a case.
        // Only where that answers is there an arm to hold against the target's: a helper answers with a
        // case nothing here can read off the text, and reporting that as an arm the target cannot produce
        // refused a row whose expectation was right (issue #214).
        TypeName named = constructedCase(row.expected());
        state.expectedArm = named;
        if (named != null && !outCases.isEmpty() && !outCases.contains(named)) {
            String expectedArm = expectedArm(row.expected());
            List<String> names = new ArrayList<>();
            for (TypeName c : outCases) {
                names.add(c.name());
            }
            out.add(Diagnostic.of("E1904", "check.example.arm").title("check.example.title")
                    .at(row.pos()).args(expectedArm != null ? expectedArm : named.name(), target.name())
                    .hint("check.example.arm.hint", String.join(", ", names)).build());
            state.failed(FailurePhase.EXPECTED_FIXTURE);
            return;
        }
        // Build the expected value before running: a row whose expectation cannot be built states no
        // expectation, and comparing a result against a value nothing built reported a mismatch
        // against an empty expected value — a wrong answer for a row that was right.
        Object expectedValue;
        try {
            expectedValue = caseOnly(row.expected()) != null ? null
                    : builtExpected(row.expected(), sig.out());
        } catch (FixtureException fe) {
            out.add(Diagnostic.of("E1903", "check.example.expected").title("check.example.title")
                    .at(row.pos()).args(target.name(), fe.getMessage()).build());
            state.failed(FailurePhase.EXPECTED_FIXTURE);
            return;
        }
        state.stage = Stage.FIXTURES_VALIDATED;
        if (target.pending()) {
            // Everything a row can be held to without a body has been: its arity, its inputs against
            // their types and invariants, and its expectation against the output's cases. What is left
            // needs something to run, and there is nothing yet. A fake is not it — a fake stands in for
            // a dependency while some *other* behavior's row runs, and this row is about this behavior.
            state.disposition = Disposition.PENDING;
            state.failurePhase = FailurePhase.NONE;
            return;
        }
        Object[] fakes = resolveFakes(target, row, out);
        if (fakes == null) {
            state.failed(FailurePhase.FAKE_RESOLUTION);
            return;   // a fake was missing/invalid; the diagnostic is already reported
        }
        Object result;
        state.stage = Stage.INVOKED;
        try {
            result = invoke(target, args, fakes);
        } catch (FakeMissException fm) {
            out.add(Diagnostic.of("E1909", "check.fake.miss").title("check.example.title")
                    .at(row.pos()).args(fm.getMessage()).build());
            state.failed(FailurePhase.FAKE_RESOLUTION);
            return;
        } catch (UnreachableException ue) {
            out.add(Diagnostic.of("E1911", "check.example.unreachable").title("check.example.title")
                    .at(row.pos()).args(ue.getMessage())
                    .hint("check.example.unreachable.hint").build());
            state.failed(FailurePhase.INVOCATION);
            return;
        } catch (AbortException ae) {
            out.add(mismatch(row, describeExpected(row.expected(), sig.out()), "aborted: " + ae.getMessage()));
            state.failed(FailurePhase.INVOCATION);
            return;
        } catch (NonTerminationException nt) {
            out.add(Diagnostic.of("E1910", "check.example.nonterminating").title("check.example.title")
                    .at(row.pos()).args(nt.getMessage()).build());
            state.incomplete(FailurePhase.TIMEOUT);
            return;
        }
        result = projected(result, sig.out());
        state.resultArm = symbols.resolve(NeutralForm.simpleName(result));
        state.stage = Stage.COMPARED;
        if (!matches(row.expected(), result, expectedValue)) {
            out.add(mismatch(row, describeExpected(row.expected(), sig.out()), describeActual(result)));
            state.failed(FailurePhase.COMPARISON);
            return;
        }
        state.disposition = Disposition.HELD;
        state.failurePhase = FailurePhase.NONE;
    }

    /** The case an input fixture constructs, or null where its text does not say. A form this cannot
     * read is not a reason to lose the row: the measure that reads it says it could not classify. */
    private TypeName caseWritten(Ast.Expr fixture) {
        try {
            return constructedCase(fixture);
        } catch (RuntimeException _) {
            return null;
        }
    }

    /**
     * The Souther value behind a behavior's answer. A member this module declared is the answer
     * itself; a primitive or an imported type reached the union through a bridge case (spec 19.8),
     * and a row writes the value, not the bridge case — which is a name this source does not have.
     * The same projection a Souther caller does, done on the loaded classes.
     */
    private Object projected(Object result, Type out) {
        if (result == null || !(out instanceof Type.Union)) {
            return result;
        }
        for (TypeName member : TypeOps.leafCases(out, symbols)) {
            if (!member.isPrimitive() && member.module().equals(module.name())) {
                continue;
            }
            if (result.getClass().getName().equals(module.name() + "." + member.name() + "Case")) {
                try {
                    return result.getClass().getMethod("value").invoke(result);
                } catch (ReflectiveOperationException e) {
                    throw new IllegalStateException("a bridge case with no `value`: " + result.getClass(), e);
                }
            }
        }
        return result;
    }

    // --- fakes for what a behavior depends on ---------------------------------------------------

    /** Builds a {@code Behavior} proxy for each of the target's requirements, in the order its
     * constructor takes them; null (with a diagnostic reported) when one is missing or invalid. */
    private Object[] resolveFakes(ExampleTarget target, Ast.ExampleRow row, List<Diagnostic> out) {
        List<BehaviorRequirement> reqs = target.requirements();
        Object[] proxies = new Object[reqs.size()];
        for (int i = 0; i < reqs.size(); i++) {
            Object p = resolveFake(target.name(), reqs.get(i), row, out);
            if (p == null) {
                return null;
            }
            proxies[i] = p;
        }
        return proxies;
    }

    private Object resolveFake(String target, BehaviorRequirement req, Ast.ExampleRow row,
                               List<Diagnostic> out) {
        String depName = req.dependency();
        Ast.SpecBehavior dep = injectedSpec(depName);
        if (dep == null) {
            out.add(fakeMissingDiag(target, req, row, "`" + depName
                    + "` is not an injected behavior of this module"));
            return null;
        }
        Type outType = TypeOps.successType(dep.ret(), symbols);
        // a value fake given inline on the row: `with dep = value`
        for (Ast.With w : row.withs()) {
            if (w.dep().equals(depName)) {
                try {
                    Object value = buildFixture(w.value(), outType).value();
                    return fakeInstance(dep, a -> value, out);   // constant: ignores its inputs
                } catch (FixtureException fe) {
                    // The row does supply a fake. What failed is building its value, which is a
                    // different problem from a dependency nothing stands in for.
                    out.add(Diagnostic.of("E1908", "check.fake.value").title("check.example.title")
                            .at(w.value().pos()).args(depName, fe.getMessage()).build());
                    return null;
                }
            }
        }
        // a function fake given as a `fake dep | table` declaration
        for (Ast.Fake fk : module.fakes()) {
            if (fk.target().equals(depName)) {
                return tableProxy(fk, dep, outType, out);
            }
        }
        out.add(fakeMissingDiag(target, req, row, "add `with " + depName
                + " = ...` on the row, or a `fake " + depName + "` table"));
        return null;
    }

    /**
     * A dependency nothing stands in for. Where the target is not the definition that asked for it —
     * a composition takes the requirements of its stages — the stage that wants it is named, so the
     * author is not left to walk the composition to find out which one.
     */
    private Diagnostic fakeMissingDiag(String target, BehaviorRequirement req, Ast.ExampleRow row,
                                       String detail) {
        List<String> stages = new ArrayList<>();
        for (String requester : req.requiredBy()) {
            if (!requester.equals(target)) {
                stages.add("`" + requester + "`");
            }
        }
        Diagnostic.Builder d = stages.isEmpty()
                ? Diagnostic.of("E1908", "check.fake.missing").args(target, req.dependency())
                : Diagnostic.of("E1908", "check.fake.missing.through")
                        .args(target, req.dependency(), String.join(", ", stages));
        return d.title("check.example.title").at(row.pos())
                .hint("check.fake.missing.hint", detail).build();
    }

    /** Precomputes a function fake's input→output table (decoded fixtures) as a tuple-keyed lookup, and
     * returns a fake instance ({@link #fakeInstance}) matching an actual input tuple by value equality,
     * falling back to the {@code _} default or a miss. Works for any arity: a 0/1-input dep's tuple has
     * 0/1 elements, a 2+-input dep's has one per parameter (issue #57). */
    private Object tableProxy(Ast.Fake fk, Ast.SpecBehavior dep, Type outType, List<Diagnostic> out) {
        List<Type> paramTypes = new ArrayList<>();
        for (Ast.Param p : dep.params()) {
            paramTypes.add(TypeOps.successType(p.type(), symbols));
        }
        // What is wrong with the table is said where the fake is written ({@link #fakeTables}), and
        // said once. Here it is a row that cannot run: this row and every other row reaching the same
        // fake would each repeat the one thing wrong with the one table they all read.
        Standins table = standins(fk, paramTypes, outType, new ArrayList<>());
        if (table == null) {
            return null;
        }
        String depName = fk.target();
        int arity = paramTypes.size();
        java.util.function.Function<Object[], Object> body = a -> {
            Object[] key = java.util.Arrays.copyOf(a, arity);
            Standin answering = standingIn(table, key);
            if (answering == null) {
                throw new FakeMissException("`" + depName + "` has no output for "
                        + java.util.Arrays.toString(key));
            }
            return answering.answer().value();
        };
        return fakeInstance(dep, body, out);
    }

    /**
     * A fake's table, decoded — the one form both the proxy and the consistency check read.
     *
     * <p>The whole table, not the part a reader happens to need. The rule that picks a row is
     * order-sensitive, so a check that re-derived it would be free to pick another; and a table is
     * valid or it is not, so a check that built only the row it was asking about would report what a
     * fake answers for a table the proxy refuses to build at all. What the report says a fake answers
     * has to be what the fake answers.
     */
    private record Standins(List<Standin> explicit, Standin fallback) {}

    /** One row of a fake's table: the arguments it states — none, for the {@code _} row — and the
     * answer it was built into. */
    private record Standin(Object[] arguments, Ast.FakeRow row, FixtureReader.BuiltFixture answer) {}

    /**
     * {@code fk}'s table, decoded against {@code ins} and {@code outType}; null (with a diagnostic
     * reported) where a row states the wrong number of inputs, or any part of any row will not
     * build — one bad row is a table the fake cannot stand in with.
     *
     * <p>Shape first, then values. A row whose input count is wrong is wrong however its output
     * builds, and building the output first would run whatever helpers it applies before saying so —
     * so a table with an arity slip and a slow or non-terminating output reported the second problem
     * instead of the first, or ran out of time before reporting either.
     */
    private Standins standins(Ast.Fake fk, List<Type> ins, Type outType, List<Diagnostic> out) {
        for (Ast.FakeRow r : fk.rows()) {
            if (!r.isDefault() && r.inputs().size() != ins.size()) {
                out.add(unbuildableFake(r.pos(), fk.target(), "a row has " + r.inputs().size()
                        + " input(s) where the dependency takes " + ins.size()));
                return null;
            }
        }
        List<Standin> explicit = new ArrayList<>();
        Standin fallback = null;
        try {
            for (Ast.FakeRow r : fk.rows()) {
                // A dependency that returns a sum has no single decoder; each row names one case,
                // so decode the row's output against that case's type (as an expected value is).
                FixtureReader.BuiltFixture answer = buildFixture(r.output(), outType);
                if (r.isDefault()) {
                    fallback = new Standin(null, r, answer);
                    continue;
                }
                Object[] arguments = new Object[ins.size()];
                for (int i = 0; i < ins.size(); i++) {
                    arguments[i] = built(r.inputs().get(i), ins.get(i));
                }
                explicit.add(new Standin(arguments, r, answer));
            }
        } catch (FixtureException fe) {
            out.add(unbuildableFake(fk.pos(), fk.target(), fe.getMessage()));
            return null;
        } catch (NonTerminationException nt) {
            out.add(unbuildableFake(fk.pos(), fk.target(), nt.getMessage()));
            return null;
        }
        return new Standins(explicit, fallback);
    }

    /**
     * Which row of {@code table} answers {@code arguments}: the first explicit row stating them, and
     * otherwise the {@code _} row. Null where the table answers nothing, which is <em>E1909</em>'s to
     * say where the fake is used.
     */
    private static Standin standingIn(Standins table, Object[] arguments) {
        for (Standin s : table.explicit()) {
            // by value equality (spec 22), which is the language's: a row written 1.0m is the
            // row a call arriving with 1m wants. Arrays.equals would ask the arguments' own.
            if (sameArguments(s.arguments(), arguments)) {
                return s;
            }
        }
        return table.fallback();
    }

    /** Whether a fake's row states the arguments a call arrived with, each by the language's
     * equality. A multi-input dependency is matched as a tuple (spec 22), so this walks them. */
    private static boolean sameArguments(Object[] row, Object[] key) {
        if (row.length != key.length) {
            return false;
        }
        for (int i = 0; i < row.length; i++) {
            if (!souther.runtime.Values.equal(row[i], key[i])) {
                return false;
            }
        }
        return true;
    }

    /** Wraps a fake's {@code Object[] -> Object} body as the injected instance: a unary {@code Behavior}
     * proxy for a single-input dependency, or a runtime-generated subclass of the standalone base for
     * one taking any other count (whose typed {@code apply} the unary {@code Behavior} cannot stand in
     * for; issue #57). Both the table and the constant {@code with} fake route through here, so neither
     * path assumes an arity. */
    private Object fakeInstance(Ast.SpecBehavior dep, java.util.function.Function<Object[], Object> body,
                                List<Diagnostic> out) {
        if (dep.params().size() != 1) {
            return standaloneFakeInstance(dep, body, out);
        }
        return behaviorProxy(body);
    }

    /** Generates (once) and instantiates a subclass of a standalone injected base whose typed
     * {@code apply} packs its arguments into an {@code Object[]} and delegates to {@code body}. */
    private Object standaloneFakeInstance(Ast.SpecBehavior dep,
                                          java.util.function.Function<Object[], Object> body,
                                          List<Diagnostic> out) {
        try {
            String baseName = module.name() + "." + behaviorClass(dep.name());
            Class<?> base = loader.loadClass(baseName);
            java.lang.reflect.Method apply = null;
            for (java.lang.reflect.Method m : base.getDeclaredMethods()) {
                if (m.getName().equals("apply") && java.lang.reflect.Modifier.isAbstract(m.getModifiers())) {
                    apply = m;
                }
            }
            if (apply == null) {
                throw new NoSuchMethodException("abstract apply on " + baseName);
            }
            String fakeName = baseName + "$Fake";
            java.lang.reflect.Method applyM = apply;
            Class<?> fakeClass = loader.define(fakeName, () -> fakeSubclassBytes(fakeName, base, applyM));
            return fakeClass.getConstructor(java.util.function.Function.class).newInstance(body);
        } catch (ReflectiveOperationException e) {
            out.add(unbuildableFake(dep.pos(), dep.name(),
                    "its base subclass could not be built: " + e));
            return null;
        }
    }

    /**
     * A fake that was supplied and could not be built. A dependency nothing stands in for is a different
     * problem, and saying this as that named the dependency as its own requester and reported a fake as
     * missing where one was written (issue #206).
     */
    private static Diagnostic unbuildableFake(SourcePos pos, String dependency, String reason) {
        return Diagnostic.of("E1908", "check.fake.unbuildable").title("check.example.title")
                .at(pos).args(dependency, reason).build();
    }

    /**
     * A fake whose table did not finish being built, so nothing it states was checked.
     *
     * <p>A warning, where a table that will not build is an error: waiting says that this table was
     * not read, not that it is wrong, and which of the two it is cannot be told from having waited.
     * The budget is the one this wait was held to rather than the setting read back later, and it is
     * written out rather than passed as a number, which a locale would group into a budget nobody set.
     */
    private static Diagnostic uncheckedFake(Ast.Fake fk, long budgetMs) {
        return Diagnostic.of("E1921", "check.fake.unchecked").warning().title("check.example.title")
                .at(fk.pos(), fk.target().length())
                .args(fk.target(), Long.toString(budgetMs))
                .hint("check.fake.unchecked.hint", fk.target()).build();
    }

    private byte[] fakeSubclassBytes(String fakeName, Class<?> base, java.lang.reflect.Method apply) {
        java.lang.constant.ClassDesc cdFake = java.lang.constant.ClassDesc.of(fakeName);
        java.lang.constant.ClassDesc cdBase = java.lang.constant.ClassDesc.of(base.getName());
        java.lang.constant.ClassDesc cdFunc =
                java.lang.constant.ClassDesc.of("java.util.function.Function");
        java.lang.constant.ClassDesc cdObject = java.lang.constant.ConstantDescs.CD_Object;
        java.lang.constant.ClassDesc[] paramDescs = new java.lang.constant.ClassDesc[apply.getParameterCount()];
        for (int i = 0; i < paramDescs.length; i++) {
            paramDescs[i] = apply.getParameterTypes()[i].describeConstable().orElseThrow();
        }
        java.lang.constant.ClassDesc retDesc = apply.getReturnType().describeConstable().orElseThrow();
        java.lang.constant.MethodTypeDesc applyDesc = java.lang.constant.MethodTypeDesc.of(retDesc, paramDescs);
        java.lang.constant.MethodTypeDesc voidCtor =
                java.lang.constant.MethodTypeDesc.of(java.lang.constant.ConstantDescs.CD_void);
        java.lang.constant.MethodTypeDesc funcApply =
                java.lang.constant.MethodTypeDesc.of(cdObject, cdObject);
        return java.lang.classfile.ClassFile.of().build(cdFake, cb -> {
            cb.withSuperclass(cdBase);
            cb.withFlags(java.lang.classfile.ClassFile.ACC_PUBLIC | java.lang.classfile.ClassFile.ACC_FINAL
                    | java.lang.classfile.ClassFile.ACC_SUPER);
            cb.withField("body", cdFunc, java.lang.classfile.ClassFile.ACC_PRIVATE
                    | java.lang.classfile.ClassFile.ACC_FINAL);
            cb.withMethodBody("<init>",
                    java.lang.constant.MethodTypeDesc.of(java.lang.constant.ConstantDescs.CD_void, cdFunc),
                    java.lang.classfile.ClassFile.ACC_PUBLIC, code -> {
                        code.aload(0);
                        code.invokespecial(cdBase, "<init>", voidCtor);
                        code.aload(0);
                        code.aload(1);
                        code.putfield(cdFake, "body", cdFunc);
                        code.return_();
                    });
            cb.withMethodBody("apply", applyDesc, java.lang.classfile.ClassFile.ACC_PUBLIC, code -> {
                code.aload(0);
                code.getfield(cdFake, "body", cdFunc);
                code.loadConstant(paramDescs.length);
                code.anewarray(cdObject);
                for (int i = 0; i < paramDescs.length; i++) {
                    code.dup();
                    code.loadConstant(i);
                    code.aload(i + 1);   // every apply param is a reference (Int boxes to Long, etc.)
                    code.aastore();
                }
                code.invokeinterface(cdFunc, "apply", funcApply);
                if (!retDesc.equals(cdObject)) {
                    code.checkcast(retDesc);
                }
                code.areturn();
            });
        });
    }

    /** A {@code Behavior} proxy whose {@code apply} runs {@code body}. Reflective so the runtime
     * (souther-runtime, `provided`) may be absent, in which case the LinkageError is caught upstream. */
    private Object behaviorProxy(java.util.function.Function<Object[], Object> body) {
        Class<?> iface;
        try {
            iface = loader.loadClass("souther.runtime.Behavior");
        } catch (ClassNotFoundException _) {
            throw new NoClassDefFoundError("souther.runtime.Behavior");
        }
        return java.lang.reflect.Proxy.newProxyInstance(loader, new Class<?>[] {iface}, (proxy, method, a) -> {
            if (method.getName().equals("apply")) {
                return body.apply(a == null ? new Object[0] : a);
            }
            return switch (method.getName()) {
                case "toString" -> "fake";
                case "hashCode" -> System.identityHashCode(proxy);
                case "equals" -> proxy == (a != null && a.length > 0 ? a[0] : null);
                default -> null;
            };
        });
    }

    private Diagnostic mismatch(Ast.ExampleRow row, String expected, String actual) {
        // Underline the expected result (the part the row asserts), not the whole row, so the marker
        // lands on something meaningful rather than a single column at the row's start.
        SourcePos pos = row.expected() != null ? row.expected().pos() : row.pos();
        int width = Math.max(1, expected.length());
        Diagnostic.Builder b = Diagnostic.of("E1905", "check.example.mismatch")
                .title("check.example.title")
                .at(pos, width)
                .diff(actual, expected);
        if (row.description() != null) {
            b.hint("check.example.mismatch.hint", row.description());
        }
        return b.build();
    }

    // --- comparison ---------------------------------------------------------------------------

    /**
     * A written answer, in the form two of them can be compared.
     *
     * <p>A row may assert the case and nothing under it, or the whole value, and the two sides of a
     * comparison need not have been written the same way — so what is compared is read off each side
     * once, here, rather than at every place two answers meet.
     */
    /**
     * What someone wrote down as an answer, at the grain they wrote it.
     *
     * <p>Apart from {@link FixtureReader.BuiltFixture} because the two are different things. A value is built or it
     * is not; an assertion may deliberately say less than a value — a row naming a case and nothing
     * under it says only that — and only a recorded row may. Reading a stand-in as an assertion let a
     * {@code with} that cannot be built at all be compared as though it named a case.
     */
    sealed interface Asserted {

        /** The case, and nothing under it: a bare name denoting one. */
        record CaseOnly(TypeName name) implements Asserted {}

        /** The whole value. */
        record Whole(FixtureReader.BuiltFixture fixture) implements Asserted {}

        /** Nothing that can be read: a fixture that did not build or did not finish, or an
         * expectation naming a case the behavior cannot answer with. What is wrong with it is
         * reported where the row is evaluated; here it states nothing to be held against. */
        record Unreadable() implements Asserted {}
    }

    /**
     * What a stand-in stands in with: the whole value, always. Unreadable where it will not build,
     * which is where it stands in for nothing at all — that is reported where the fake is resolved.
     */
    private Asserted readStandIn(Ast.Expr written, Type outType, Set<TypeName> cases) {
        if (written == null || refusedCase(written, cases)) {
            return new Asserted.Unreadable();
        }
        try {
            return new Asserted.Whole(buildFixture(written, outType));
        } catch (FixtureException | NonTerminationException _) {
            return new Asserted.Unreadable();
        }
    }

    /**
     * What a recorded row asserts: the case alone where it named one and nothing under it, and the
     * whole value otherwise.
     *
     * <p>Built through the same builder a row's expectation goes through, so what is compared is what
     * the row asserts: a value a helper answered with is that value, not that value read back into
     * the form a fixture is written in and decoded again (issue #214).
     */
    private Asserted readExpected(Ast.Expr written, Type outType, Set<TypeName> cases) {
        if (written == null || refusedCase(written, cases)) {
            return new Asserted.Unreadable();
        }
        if (caseOnly(written) != null) {
            return new Asserted.CaseOnly(constructedCase(written));
        }
        try {
            return new Asserted.Whole(buildFixture(written, outType));
        } catch (FixtureException | NonTerminationException _) {
            return new Asserted.Unreadable();
        }
    }

    /** Whether {@code written} names a case the position cannot hold — <em>E1904</em> where the row
     * is evaluated, and nothing about the behavior it was written for. */
    private boolean refusedCase(Ast.Expr written, Set<TypeName> cases) {
        TypeName named = constructedCase(written);
        return named != null && !cases.isEmpty() && !cases.contains(named);
    }

    /**
     * Whether two written answers to one input state different things.
     *
     * <p>Where either names a case and nothing more, the comparison is on the case: there is no value
     * under it to compare, and holding a full value against it would report a disagreement the row
     * never stated. The case compared is the one the value turned out to be, resolved to the type
     * this module knows it under — not the class it arrives in, which does not tell one module's
     * {@code Missing} from another's.
     *
     * <p>Where either states nothing there is nothing to disagree with. Read against a written
     * answer, silence is not a contradiction.
     */
    private static boolean differs(Asserted left, Asserted right) {
        if (left instanceof Asserted.Unreadable || right instanceof Asserted.Unreadable) {
            return false;
        }
        if (left instanceof Asserted.Whole l && right instanceof Asserted.Whole r) {
            return !souther.runtime.Values.equal(l.fixture().value(), r.fixture().value());
        }
        TypeName one = caseOf(left);
        TypeName other = caseOf(right);
        return one != null && other != null && !one.equals(other);
    }

    /** The case an assertion is about, or null where nothing says. */
    private static TypeName caseOf(Asserted a) {
        return switch (a) {
            case Asserted.CaseOnly c -> c.name();
            case Asserted.Whole w -> w.fixture().caseName();
            case Asserted.Unreadable _ -> null;
        };
    }

    /** Whether {@code result} matches the row's expected: a name denoting a case asserts only the
     * arm (the concrete case class); anything else asserts the whole value, {@code expectedValue}
     * (built before the behavior ran), by structural equality.
     *
     * <p>Not {@link #differs}. That compares two things a person wrote, and reads each one's case off
     * the text; this compares what was written against what a run produced, and a result carries no
     * text — the class it arrived in is what says which case it is. */
    private boolean matches(Ast.Expr expected, Object result, Object expectedValue) {
        String arm = caseOnly(expected);
        if (arm != null) {
            return NeutralForm.simpleName(result).equals(arm);
        }
        return expectedValue != null && souther.runtime.Values.equal(expectedValue, result);
    }


    private Set<TypeName> outCases(Type out) {
        return TypeOps.outputCases(out, symbols);
    }

    // --- invoke the behavior ------------------------------------------------------------------

    /** The budget a compile that says nothing about it is given. A total behavior finishes in well
     * under this; a `partial` recursion that does not terminate hits it, so the compiler is bounded,
     * never hung. Overridable with the `souther.example.timeout.ms` system property for an unusually
     * slow example. A caller that wants a different one for one compile sets
     * {@link souther.compiler.query.Front.ExampleBudget} instead, which is the only way two compiles
     * in one JVM can be held to different budgets. */
    private static final long DEFAULT_BUDGET_MS = readTimeoutMs();

    /** The budget a compile is given when it asks for none. */
    public static long defaultBudgetMs() {
        return DEFAULT_BUDGET_MS;
    }

    private static long readTimeoutMs() {
        String override = System.getProperty("souther.example.timeout.ms");
        if (override == null) {
            return 2000L;
        }
        try {
            long ms = Long.parseLong(override.trim());
            return ms > 0 ? ms : 2000L;
        } catch (NumberFormatException _) {
            return 2000L;
        }
    }

    /**
     * Applies the behavior. The row it belongs to is what carries the budget ({@link #checkRow}):
     * recursion is total by default, so most code cannot loop, and a `partial` recursion that does not
     * terminate is bounded there along with everything else the row runs — on timeout the row is
     * reported (E1910). A non-terminating recursion that overflows the stack instead of tail-looping is
     * reported the same way (a non-termination, not a generic failure).
     */
    private Object invoke(ExampleTarget target, Object[] args, Object[] fakes) {
        return invokeNow(target, args, fakes);
    }

    /** The {@code $Impl}'s constructor, opened. A behavior its module does not expose generates a
     * package-private class, and an {@code example} runs inside the module rather than across its
     * boundary, so exposure does not decide whether it can be evaluated. */
    private static java.lang.reflect.Constructor<?> openCtor(Class<?> c, Class<?>... params)
            throws ReflectiveOperationException {
        java.lang.reflect.Constructor<?> ctor = c.getDeclaredConstructor(params);
        ctor.setAccessible(true);
        return ctor;
    }

    private Object invokeNow(ExampleTarget target, Object[] args, Object[] fakes) {
        // The public name is now an interface; the fields, constructor and erased apply live on its
        // $Impl (spec 19.8). Instantiate and call apply on the $Impl.
        String className = module.name() + "." + behaviorClass(target.name()) + "$Impl";
        try {
            Class<?> c = loader.loadClass(className);
            Object instance;
            if (target.requirements().isEmpty()) {
                instance = openCtor(c).newInstance();
            } else {
                // the injecting constructor takes one param per dependency: the unary Behavior for a
                // single-input dep (a Proxy), or the dep's own base class for a multi-input dep (a
                // generated subclass) — issue #57. The fake's runtime type tells the two apart.
                Class<?> behaviorIface = loader.loadClass("souther.runtime.Behavior");
                Class<?>[] ctorParams = new Class<?>[fakes.length];
                for (int i = 0; i < fakes.length; i++) {
                    ctorParams[i] = behaviorIface.isInstance(fakes[i])
                            ? behaviorIface
                            : fakes[i].getClass().getSuperclass();
                }
                instance = openCtor(c, ctorParams).newInstance(fakes);
            }
            Class<?>[] paramTypes = new Class<?>[args.length];
            java.util.Arrays.fill(paramTypes, Object.class);
            java.lang.reflect.Method apply = c.getDeclaredMethod("apply", paramTypes);
            apply.setAccessible(true);
            return apply.invoke(instance, args);
        } catch (java.lang.reflect.InvocationTargetException ite) {
            Throwable cause = ite.getCause();
            if (cause instanceof FakeMissException fm) {
                throw fm;   // a fake did not cover an input — reported as its own diagnostic
            }
            // a point the model declared could not arise: what the row found is not a wrong answer
            // but a premise that does not hold, so it is reported as that rather than as a mismatch.
            // Matched by name: the generated code runs under its own loader, and this class only
            // needs to know which abort it was.
            if (cause != null && "souther.runtime.UnreachableReached".equals(cause.getClass().getName())) {
                throw new UnreachableException(cause.getMessage());
            }
            if (cause instanceof StackOverflowError) {
                // a non-tail `partial` recursion that does not terminate — a non-termination, not a
                // failed example (a tail-looping one is caught by the timeout instead)
                throw new NonTerminationException("recursion overflowed the stack");
            }
            throw new AbortException(cause == null ? "aborted" : String.valueOf(cause.getMessage()));
        } catch (ReflectiveOperationException e) {
            throw new AbortException(String.valueOf(e.getMessage()));
        }
    }

    private static String behaviorClass(String name) {
        return Character.toUpperCase(name.charAt(0)) + name.substring(1);
    }

    /** The behavior aborted while evaluating a row (e.g. an invariant violation) — a failed example. */
    private static final class AbortException extends RuntimeException {
        AbortException(String message) {
            super(message);
        }
    }

    /** The row reached an {@code unreachable} — the reason the model wrote is the message. */
    private static final class UnreachableException extends RuntimeException {
        UnreachableException(String message) {
            super(message);
        }
    }

    /** A fake table had no output for an input the behavior asked for (and no {@code _} default). */
    private static final class FakeMissException extends RuntimeException {
        FakeMissException(String message) {
            super(message);
        }
    }
}
