package souther.compiler.partition;

import souther.compiler.numeric.Towards;

import souther.compiler.check.Carrier;
import souther.compiler.inputs.BoundaryDomain;
import souther.compiler.numeric.AdditiveImage;
import souther.compiler.numeric.Count;
import souther.compiler.numeric.Endpoint;
import souther.compiler.numeric.NumericDomain;
import souther.compiler.numeric.OrderedInterval;
import souther.compiler.numeric.Place;
import souther.compiler.numeric.Rational;

import java.math.BigDecimal;
import java.math.RoundingMode;
import java.util.Optional;

/**
 * How one {@link BorderQuantity}'s own values are ordered, and which of them the quantity can take.
 *
 * <p><b>Everything is asked about a run.</b> Whether the quantity takes anything there, which values
 * are at its ends, and whether one can be written down — {@link #inspect} and {@link #witness}, over
 * a {@link LevelInterval}. Nothing here is asked about a point, a side or a run as three different
 * things: they are three runs, and a question shaped for one of them is a question that cannot be
 * asked about the others. Asked as "something past this level", a run bounded at both ends was
 * searched by stepping past it (issue #903), and there was no way to ask the difference.
 *
 * <p><b>Existence and construction are two answers.</b> {@link #inspect} says what the quantity has;
 * {@link #witness} says what this compiler could write down. A run of strings above a bound has
 * every string with that one as a prefix and this names none of them; a run between one and two on
 * an order counting by threes has nothing at all. Answered as one, the second reads like the first
 * and a coverage item goes away (ADR-0091).
 *
 * <p>And a run and its extrema are two answers as well, which is what {@link Occupancy} carries.
 * A decimal difference is attainable everywhere, has a first value nowhere, and has values on both
 * sides of every level. Answered as one question, a border over decimals lost its {@code IN} point
 * along with the point beside its line, and a line at a string lost the whole of the side above it —
 * because a string has no successor.
 *
 * <p>And attainability is not adjacency. {@code 2 * a <= 9} cuts a quantity whose values are the even
 * numbers: the threshold is a level the quantity never takes, and the border is still there, with its
 * {@code ON} point at 8 and its {@code OFF} point at 10. A reader that assumed the threshold was one
 * of the quantity's own values would put a row at 9 and call the rule exercised.
 *
 * <p>Not sealed, and never switched on. Which of these a quantity has is the quantity's own answer
 * and no reader's question: a reader that asked would be asking which variant the quantity is under
 * another name, which is the shape this whole arrangement exists to stop.
 *
 * <p>What it says is about the order alone — the ambient one, before any rule narrows anything. What
 * the rules leave is a separate answer and belongs to whatever holds them: a level this says exists
 * may be one no row can be written at, and that is {@link Realization}'s to report rather than a
 * reason to move the level.
 */
public interface LevelSpace {

    /**
     * Whether {@code l} is below, at or above {@code r}.
     *
     * <p>Both on this space. Two levels of different spaces are never compared — the mistake is this
     * compiler's rather than anything a model can write, and it is said as one, the way
     * {@link Place#notOneOrder} says it of two carriers' places.
     */
    int compare(Level l, Level r);

    /**
     * What this quantity has in {@code run}: nothing, or something and where it ends.
     *
     * <p>Exact. Which is what lets an empty answer be read as a proof — a run between two lines less
     * than one step apart on an order that steps holds nothing, and saying so is a fact about the
     * order rather than a search that gave up.
     */
    Occupancy inspect(LevelInterval run);

    /**
     * One value of this quantity from inside {@code run}, where this compiler can name one.
     *
     * <p>Not a decision. {@link Witness.NotConstructed} says nothing came back and never that the run
     * holds nothing — {@link #inspect} is that question, and the two differ wherever naming a value
     * means choosing something no model wrote.
     *
     * <p>A run and not a level to walk from. An order whose values fill has no next value, so a
     * witness inside a run has to be arithmetic and cannot be a step: past one, an order generated by
     * three offers three, and every one of the thirds between one and two is a value it also takes.
     *
     * <p>{@code from} is which end of the run the value is wanted near, and is the same parameter
     * {@link Occupancy#end} reads. Not a searching policy: where the run has a value at that end it
     * is that value, and where its values fill up to it there is none to name and this offers the
     * plainest one it can reach from there. Left out, a run bounded at both ends answered with the
     * end furthest from the line the point is named for, and a point that exists to be inside a
     * partition and beside its boundary was offered a row at the other side of it.
     */
    Witness witness(LevelInterval run, Towards from);

    /** Whether the quantity can take this level at all. */
    default boolean attainable(Level level) {
        return inspect(LevelInterval.point(level)).any();
    }

    /**
     * The nearest level the quantity can take at or past {@code from}, the way {@code towards} says,
     * or empty where the order names none there.
     *
     * <p>What both points of a border are found with: the threshold itself where the quantity takes
     * it, and the first value it does take otherwise.
     */
    default Optional<Level> nearestAtOrBeyond(Level from, Towards towards) {
        return Optional.ofNullable(inspect(runFrom(from, towards, true)).end(towards));
    }

    /**
     * The nearest level this quantity can take strictly past {@code from}, the way {@code towards}
     * says, or empty where the order names no single value there.
     *
     * <p>Adjacency, and nothing else. Empty says the run past this level has no end, which is not a
     * statement that it is empty: a decimal difference has no successor and has every larger
     * difference. That other question is {@link #anythingBeyond}, and both are read off the one
     * {@link Occupancy} so they cannot disagree.
     */
    default Optional<Level> neighbour(Level from, Towards towards) {
        return Optional.ofNullable(inspect(runFrom(from, towards, false)).end(towards));
    }

    /**
     * Whether this quantity takes any value at all strictly past {@code from}, the way
     * {@code towards} says.
     *
     * <p>What decides whether a border has a side there. False only where the order itself stops —
     * an enumeration at its last case, a string a rule holds another string apart from — and never
     * because the step between two values has no name.
     */
    default boolean anythingBeyond(Level from, Towards towards) {
        return inspect(runFrom(from, towards, false)).any();
    }

    /** Everything one way of a level, which is what the three questions above are asked about. */
    private static LevelInterval runFrom(Level from, Towards towards, boolean itself) {
        Bound at = Bound.at(from, itself);
        return towards == Towards.ABOVE
                ? new LevelInterval(at, null) : new LevelInterval(null, at);
    }

    /**
     * The values of one coordinate, which are the values of the carrier it is ordered by.
     *
     * <p>The one space whose levels a carrier can write. Its neighbours are the carrier's own
     * ({@link BoundaryDomain}), so a date steps a day and a decimal steps nowhere; what it can take
     * is what the carrier holds on its grid, since not every number between two of a carrier's
     * counts is one of them; and its ends are the carrier's extent.
     */
    static LevelSpace onACarrier(Carrier carrier) {
        BoundaryDomain steps = BoundaryDomain.on(carrier);
        OrderedInterval extent = carrier == null ? OrderedInterval.OPEN : carrier.extent();
        return new LevelSpace() {

            @Override
            public int compare(Level l, Level r) {
                return placeOf(l).compareTo(placeOf(r));
            }

            /**
             * Where the run reaches on this carrier, held to what the carrier itself reaches.
             *
             * <p>An end of the run is a value it holds where the carrier has one there, and the
             * nearest value it does hold otherwise — which is the same reading a border's two points
             * are found by, asked of a run rather than of a line.
             */
            @Override
            public Occupancy inspect(LevelInterval run) {
                if (carrier == null) {
                    return new Occupancy.Empty();
                }
                NumericDomain.Bounds look = run.toLookIn(run.digitsToLookIn());
                Endpoint lo = Endpoint.lower(look.min(), extent.low());
                Endpoint hi = Endpoint.upper(look.max(), extent.high());
                if (!Endpoint.someValueLiesBetween(lo, hi)) {
                    return new Occupancy.Empty();
                }
                Level least = reaching(lo, Towards.ABOVE, run);
                Level greatest = reaching(hi, Towards.BELOW, run);
                // Whether no value at an end means no value at all is the carrier's own answer, and
                // it is the whole of what these two spacings differ by. A carrier that steps has a
                // first value wherever it has any, so nothing there is nothing anywhere; one whose
                // values fill has none above a strict bound and has every value past it. Read as one
                // question, a rule holding one string above another lost the whole of the side above
                // it, because a string has no successor.
                if (carrier.spacing() == souther.compiler.numeric.Granularity.DISCRETE) {
                    return lo != null && least == null || hi != null && greatest == null
                            || least != null && greatest != null
                                    && compare(least, greatest) > 0
                            ? new Occupancy.Empty() : new Occupancy.Inhabited(least, greatest);
                }
                // And where they fill, the one run that holds nothing is a single place the carrier
                // has no value at: everything wider than that holds values it does.
                return lo != null && hi != null && lo.at().compareTo(hi.at()) == 0
                        && carrier.onTheGrid(lo.at()) == null
                        ? new Occupancy.Empty() : new Occupancy.Inhabited(least, greatest);
            }

            /**
             * The value at one end of a run, or null where it has none there.
             *
             * <p>An end the run holds is the value it starts at, where the carrier holds it. An end
             * it stops short of is the value beside that one, which only a carrier that steps has —
             * a decimal above a strict bound has every value and no first one.
             */
            private Level reaching(Endpoint end, Towards into, LevelInterval run) {
                if (end == null) {
                    return null;
                }
                Place at = end.inclusive()
                        ? onTheGridAtOrBeyond(end.at(), into)
                        : (into == Towards.ABOVE ? steps.successor(end.at())
                                : steps.predecessor(end.at())).orElse(null);
                if (at == null) {
                    return null;
                }
                Level level = new Level.OnACarrier(carrier, at);
                return run.contains(level) && extent.admits(at) ? level : null;
            }

            /** The count itself where the carrier holds it, and the first one it does hold that way
             *  otherwise. Rounded the way {@code into} asks and never the other way: a threshold
             *  written between two of a carrier's counts has its two points either side of it. */
            private Place onTheGridAtOrBeyond(Place at, Towards into) {
                Place itself = carrier.onTheGrid(at);
                if (itself != null || !(at instanceof Count count)) {
                    return itself;
                }
                return carrier.onTheGrid(count.rounded(
                        into == Towards.ABOVE ? RoundingMode.CEILING : RoundingMode.FLOOR));
            }

            private static boolean bounded(Endpoint of, Endpoint stops) {
                return of != null || stops != null;
            }

            /**
             * A place of the carrier inside the run.
             *
             * <p>Whole numbers first, which is where a run wide enough to hold one has its plainest
             * value, and then as many digits as its own two ends are apart. The second is worked out
             * from the run and not guessed: a scale short of what it takes reports a run with a
             * value in it as one nothing can be written in.
             */
            /**
             * Which value a range gives up is the carrier's own answer
             * ({@link Carrier#somethingInside}), asked from the end this was asked about. Read again
             * here it would be this deciding what a range holds, which is the split that had a row
             * offered for a class the position is not in.
             */
            @Override
            public Witness witness(LevelInterval run, Towards from) {
                if (carrier == null) {
                    return Witness.NONE;
                }
                for (int digits : new int[] {0, run.digitsToLookIn()}) {
                    NumericDomain.Bounds look = run.toLookIn(digits);
                    // Handed the run's own ends and not ends held to the carrier's extent. Which end
                    // a range gives up is the range's own answer and the carrier holds it inside
                    // what it reaches itself; narrowed here first, a run nothing bounds below was
                    // bounded by the order and gave up the least count there is.
                    Place at = carrier.somethingInside(look.min(), look.max(), from);
                    if (at == null) {
                        continue;
                    }
                    Level level = new Level.OnACarrier(carrier, at);
                    if (run.contains(level)) {
                        return new Witness.Found(level);
                    }
                }
                return Witness.NONE;
            }

            private Place placeOf(Level level) {
                if (!(level instanceof Level.OnACarrier on)) {
                    throw new IllegalStateException(
                            "a coordinate's order was asked about a level that is not one of its "
                                    + "values: " + level);
                }
                return on.at();
            }
        };
    }

    /**
     * The numbers a quantity counts to, {@code step} apart, taking every multiple of the step.
     *
     * <p>What two positions on an order that steps stand apart, and what an affine form over whole
     * coordinates comes to. The step is the quantity's and not any position's: two positions on a
     * carrier that steps stand one apart and one apart is the whole of the difference, while
     * {@code 300x + 600y} moves in three hundreds however small a step {@code x} takes.
     */
    static LevelSpace steppingBy(BigDecimal step) {
        return new Lattice(step, new AdditiveImage.OverWholeNumbers(Rational.of(step))) {

            /** Every multiple of the step, so a run has a first value and a last wherever it is
             *  bounded. */
            @Override
            Level generated(BigDecimal at, Towards into, boolean strictly) {
                BigDecimal steps = at.divide(step, 0,
                        into == Towards.ABOVE ? RoundingMode.CEILING : RoundingMode.FLOOR);
                BigDecimal on = steps.multiply(step);
                if (strictly && on.compareTo(at) == 0) {
                    on = into == Towards.ABOVE ? on.add(step) : on.subtract(step);
                }
                return new Level.ACount(new Count(on));
            }
        };
    }

    /**
     * The numbers a quantity takes where its positions' values fill: every multiple of
     * {@code generator} by a number this language can write.
     *
     * <p><b>Dense is not the same as every number.</b> A decimal is a finite decimal, so what
     * {@code 3 * a} takes is every {@code 3 * d} with {@code d} finite — which is dense, and does not
     * include one: {@code 1 / 3} does not terminate and no decimal a model writes is a third.
     * Answered by the topology, the border of {@code 3 * a <= 1} owed a row where the quantity comes
     * arbitrarily close and never arrives, and the search that could not compose it was right.
     *
     * <p>The generator is what is left of the coefficients' greatest common divisor once the factors
     * this language can divide by are taken out. Ten is a unit among the finite decimals, so two and
     * five are too: {@code 2 * a} takes every decimal ({@code a = 4.5} makes nine) while
     * {@code 3 * a} takes a third of them.
     */
    static LevelSpace overFiniteDecimals(BigDecimal generator) {
        return new Lattice(generator,
                new AdditiveImage.OverFiniteDecimals(Rational.of(generator))) {

            /**
             * The level itself where this takes it, and no first value past it where it does not.
             *
             * <p>What this takes is dense, so strictly past a level there is no first one — every
             * one of them has another between. A run that starts at a value it holds still starts
             * there, which is the difference between asking for the nearest at or past a level and
             * asking for its neighbour.
             */
            @Override
            Level generated(BigDecimal at, Towards into, boolean strictly) {
                return !strictly && reaches(at) ? new Level.ACount(new Count(at)) : null;
            }

            /**
             * A multiple of the generator inside the run, at as few digits as the run allows.
             *
             * <p>Arithmetic and not a walk. What this takes is every finite-decimal multiple of the
             * generator, so a value inside a run is one whose quotient by the generator is a finite
             * decimal inside the run divided by it — a division, at the digits the two ends are
             * apart. Stepped a whole generator from an end instead, every value between here and
             * there was walked past: three times a decimal past one is three, and a run that stops
             * at two got nothing (issue #903).
             */
            @Override
            Witness inside(BigDecimal low, boolean lowIn, BigDecimal high, boolean highIn,
                           int digits, Towards from) {
                Witness whole = super.inside(low, lowIn, high, highIn, 0, from);
                if (whole instanceof Witness.Found) {
                    return whole;   // the plainest value the run has, where it has one
                }
                if (low == null && high == null) {
                    return new Witness.Found(new Level.ACount(Count.ZERO));
                }
                // Halfway between the ends, or a step in from the only one there is, and then put on
                // the generator's own multiples at enough digits to stay inside. A quotient rounded
                // at fewer digits than the ends are apart lands outside the run it came from.
                BigDecimal at = low == null ? high.subtract(generator)
                        : high == null ? low.add(generator)
                                : low.add(high).divide(BigDecimal.valueOf(2));
                // Read from the end the caller asked about, so a run whose values fill offers one
                // near the line rather than one halfway across the partition.
                for (int scale : new int[] {digits, digits + 1, digits + 2}) {
                    BigDecimal on = at.divide(generator, Math.max(scale, 0), RoundingMode.HALF_UP)
                            .multiply(generator);
                    if ((low == null || (lowIn ? on.compareTo(low) >= 0 : on.compareTo(low) > 0))
                            && (high == null
                                    || (highIn ? on.compareTo(high) <= 0 : on.compareTo(high) < 0))) {
                        return new Witness.Found(new Level.ACount(new Count(on)));
                    }
                }
                return Witness.NONE;
            }
        };
    }

    /**
     * What is left of {@code step} once the factors a finite decimal can be divided by are taken
     * out, which is what generates the values a form takes over decimals.
     *
     * <p>Ten is a unit among the finite decimals, so two and five are: dividing by either lands on
     * one again. What is left over is what a level has to be a multiple of.
     */
    static BigDecimal generatorOverFiniteDecimals(BigDecimal step) {
        if (step.signum() == 0) {
            return BigDecimal.ONE;
        }
        Rational left = new AdditiveImage.OverFiniteDecimals(Rational.of(step.abs())).generator();
        BigDecimal written = left.asWrittenDecimal();
        if (written == null) {
            throw new IllegalStateException(
                    "a divisor of written coefficients is written: " + left);
        }
        return written;
    }

    /**
     * The numbers a quantity counts to where the order names no step between them.
     *
     * <p>Every number is a level and none of them has a next one. What a rule holding two decimals
     * apart cuts: the pair one step further apart is not a pair this language names, and every pair
     * further apart than the line is one it does.
     */
    static LevelSpace dense() {
        return overFiniteDecimals(BigDecimal.ONE);
    }

    /**
     * The one level a quantity can take, on an order that has sides all the same.
     *
     * <p>What two strings a rule holds apart come to. There is no number between them, so the only
     * level the quantity takes is the one where they meet; and one string is still above another, so
     * both sides of that level are inhabited. Read as an order with nothing past its only value, a
     * rule written {@code a > b} over strings would owe no {@code IN} point at all.
     *
     */
    static LevelSpace onlyWhereTheyMeet() {
        return new LevelSpace() {

            @Override
            public int compare(Level l, Level r) {
                return Counting.countOf(l).compareTo(Counting.countOf(r));
            }

            /**
             * Where they meet, and both sides of it.
             *
             * <p>The one place this order has a number for is where the two are equal, and a run to
             * one side of it is inhabited all the same: one string is above another, and the pairs
             * that stand that way are rows somebody can write. What such a run has no value at
             * either end is the same answer a carrier whose values fill gives, and it is why an end
             * is read apart from whether anything is there — asked as one, {@code a > b} over
             * strings was owed no point at all.
             */
            @Override
            public Occupancy inspect(LevelInterval run) {
                Level meeting = new Level.ACount(Count.ZERO);
                if (run.contains(meeting)) {
                    return new Occupancy.Inhabited(meeting, meeting);
                }
                return run.crossed() || run.onePlace()
                        ? new Occupancy.Empty() : new Occupancy.Inhabited(null, null);
            }

            @Override
            public Witness witness(LevelInterval run, Towards from) {
                return Witness.of(inspect(run).end(from));
            }

        };
    }

    /**
     * The step a lattice made by these coefficients moves in: their greatest common divisor.
     *
     * <p>Bézout's, and exact rather than a guess: what {@code Σ cᵢ·xᵢ} takes over the whole numbers
     * is exactly the multiples of {@code gcd(cᵢ)}. Taken over them as whole numbers at their common
     * scale, so a decimal coefficient answers the way a whole one does.
     *
     * <p>Here rather than on the quantity, because it is what makes the space and a search prunes by
     * it as well: a residue that is not one of these multiples is one no assignment lands on.
     */
    static BigDecimal stepOf(java.util.Collection<BigDecimal> coefs) {
        Rational divisor = AdditiveImage.divisorOf(
                coefs.stream().map(Rational::of).toList());
        // Spelled at the scale the coefficients were written at, which is what it was spelled at
        // before this asked somewhere else for the number. A divisor of the written coefficients
        // divides each of them, so writing it out at their scale never rounds — and the scale is
        // not decoration: a level is a `Count`, two counts are equal by their decimals, and a step
        // written `2` where it used to be `2.0` is a different key in every map that holds one.
        int scale = 0;
        for (BigDecimal coef : coefs) {
            scale = Math.max(scale, Math.max(coef.scale(), 0));
        }
        return divisor.asDecimal(RoundingMode.UNNECESSARY, scale);
    }

    /**
     * The shared half of every space whose levels are numbers, where what it takes is the multiples
     * of one generator.
     *
     * <p>Two of them, and they differ in one thing: what the multiplier may be. Over the whole
     * numbers a run has a first value and a last wherever it is bounded; over the finite decimals it
     * has neither and is still full. Written as two spaces from the start, the second was given the
     * first one's answer about where to look and stepped a whole generator over runs narrower than
     * one.
     */
    abstract class Lattice extends Counting {

        final BigDecimal generator;
        private final AdditiveImage image;

        Lattice(BigDecimal generator, AdditiveImage image) {
            this.generator = generator;
            this.image = image;
        }

        /** The first value this takes at or past {@code at} the way {@code into} says, or null where
         *  it has none there because its values fill. */
        abstract Level generated(BigDecimal at, Towards into, boolean strictly);

        /** Whether this takes a number at all, which is what its multiplier is allowed to be. */
        boolean reaches(BigDecimal at) {
            return image.contains(Rational.of(at));
        }

        @Override
        public Occupancy inspect(LevelInterval run) {
            NumericDomain.Bounds look = run.toLookIn(run.digitsToLookIn());
            BigDecimal low = numberOf(look.min());
            BigDecimal high = numberOf(look.max());
            Level least = low == null ? null
                    : generated(low, Towards.ABOVE, !look.min().inclusive());
            Level greatest = high == null ? null
                    : generated(high, Towards.BELOW, !look.max().inclusive());
            if (least != null && !run.contains(least) || greatest != null
                    && !run.contains(greatest)) {
                return new Occupancy.Empty();
            }
            // Where the values fill there is no first one, and whether the run holds anything is
            // whether anything at all lies between its ends: every number between two of them is
            // arbitrarily close to a multiple of the generator, and one of those multiples is inside.
            if (least == null && greatest == null && low != null && high != null) {
                return Endpoint.someValueLiesBetween(look.min(), look.max())
                        && !(low.compareTo(high) == 0 && !reaches(low))
                        ? new Occupancy.Inhabited(null, null) : new Occupancy.Empty();
            }
            return new Occupancy.Inhabited(least, greatest);
        }

        @Override
        public Witness witness(LevelInterval run, Towards from) {
            int digits = run.digitsToLookIn();
            NumericDomain.Bounds look = run.toLookIn(digits);
            Witness found = inside(numberOf(look.min()),
                    look.min() == null || look.min().inclusive(), numberOf(look.max()),
                    look.max() == null || look.max().inclusive(), digits, from);
            return found.level() != null && run.contains(found.level()) ? found : Witness.NONE;
        }

        /**
         * A multiple of the generator between two plain numbers, taken from the {@code from} end.
         *
         * <p>The first multiple at or past that end, which is the value beside it where this order
         * has one. A run measured from the other end offers a value as far from the line as the run
         * is wide, and the point it is offered for exists to be beside the line.
         */
        Witness inside(BigDecimal low, boolean lowIn, BigDecimal high, boolean highIn, int digits,
                       Towards from) {
            Towards into = from == Towards.ABOVE
                    ? (low != null || high == null ? Towards.ABOVE : Towards.BELOW)
                    : (high != null || low == null ? Towards.BELOW : Towards.ABOVE);
            BigDecimal at = into == Towards.ABOVE ? low : high;
            if (at == null) {
                at = BigDecimal.ZERO;
            }
            BigDecimal steps = at.divide(generator, 0, into == Towards.ABOVE
                    ? RoundingMode.CEILING : RoundingMode.FLOOR);
            BigDecimal on = steps.multiply(generator);
            boolean strict = into == Towards.ABOVE ? !lowIn && low != null : !highIn && high != null;
            if (strict && on.compareTo(at) == 0) {
                on = into == Towards.ABOVE ? on.add(generator) : on.subtract(generator);
            }
            if (low != null && (lowIn ? on.compareTo(low) < 0 : on.compareTo(low) <= 0)
                    || high != null && (highIn ? on.compareTo(high) > 0
                            : on.compareTo(high) >= 0)) {
                return Witness.NONE;
            }
            return new Witness.Found(new Level.ACount(new Count(on)));
        }

        private static BigDecimal numberOf(Endpoint end) {
            return end == null ? null : Count.number(end.at()).at();
        }
    }

    /** The shared half of every space whose levels are numbers: how two of them compare. What stops
     *  a border having a side on one of these is what the rules leave, which is asked of them and
     *  not of the order. */
    abstract class Counting implements LevelSpace {

        @Override
        public int compare(Level l, Level r) {
            return countOf(l).compareTo(countOf(r));
        }

        static Count countOf(Level level) {
            if (!(level instanceof Level.ACount count)) {
                throw new IllegalStateException(
                        "a counted order was asked about a level that is not a number: " + level);
            }
            return count.at();
        }
    }
}
