package souther.compiler.partition;

import souther.compiler.inputs.NumericTerm;
import souther.compiler.numeric.NumericDomain.LinearForm;

import java.math.BigDecimal;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.TreeMap;

/**
 * What a rule cuts, told from how much of it the rule happened to write.
 *
 * <p>{@code n > 10} and {@code 2 * n > 40} cut the same thing in the same place: the second says it
 * in twos, and the values of {@code n} part between twenty and twenty-one either way. Held apart,
 * the first divides the position into classes and the second draws a line on an arithmetic form that
 * divides no position at all — so a report counts two equivalence partitions where the model states
 * three, and neither rule's border knows the other one is there.
 *
 * <p><b>The direction and not the size.</b> A form and any positive multiple of it order the rows
 * the same way, so they are one quantity; how far along it the line falls is the cut's to say. That
 * is the argument that took the constant out of a quantity and put it on the threshold
 * ({@link BorderQuantity.OverAForm}), carried one step further — a quantity carries neither the
 * offset nor the scale, because neither of them is a fact about what is being cut.
 *
 * <p>Positive multiples only. {@code a - b} and {@code b - a} run opposite ways and a row inside one
 * is outside the other, so turning a form round is not free; what settles the direction is done
 * before this, where a comparison is read ({@link AffineReading}).
 *
 * @param direction the coefficients with their common divisor taken out, which is the smallest form
 *                  that runs this way
 */
public record QuantityKey(Map<NumericTerm, BigDecimal> direction) {

    public QuantityKey {
        direction = Map.copyOf(direction);
    }

    /** The quantity {@code form} is a multiple of. */
    public static QuantityKey of(LinearForm<NumericTerm> form) {
        BigDecimal per = per(form);
        Map<NumericTerm, BigDecimal> smallest = new LinkedHashMap<>();
        form.coefs().forEach((term, coef) -> smallest.put(term, coef.divide(per)));
        return new QuantityKey(smallest);
    }

    /**
     * How much of the quantity a form wrote, which is what a level written in its terms divides by.
     *
     * <p>The coefficients' greatest common divisor, which is the same number the lattice of what the
     * form takes is generated by ({@link LevelSpace#stepOf}) — and it is that for the same reason:
     * what {@code Σ cᵢ·xᵢ} takes over the whole numbers is exactly the multiples of it, so the
     * quantity that takes every whole number is the form divided by it.
     *
     * <p>Which makes the division exact wherever it is used. A level the written form attains is a
     * multiple of this, so turning one into the canonical quantity's own units never rounds — and
     * where the written form attains no level at all there is nothing to turn.
     */
    public static BigDecimal per(LinearForm<NumericTerm> form) {
        return form.coefs().isEmpty() ? BigDecimal.ONE
                : LevelSpace.stepOf(form.coefs().values());
    }

    /**
     * What makes two quantities one quantity, as a name a map can hold.
     *
     * <p>In an order the coefficients settle rather than the one they were recorded in, so that a
     * form written {@code 6 * b + 3 * a} and one written {@code 3 * a + 6 * b} are one name. Written
     * out rather than left to the record's own equality because a coefficient of {@code 2} and one
     * of {@code 2.0} are one number and two {@code BigDecimal}s — the same rule {@link Level#key()}
     * states, asked of a direction.
     */
    public String key() {
        Map<String, String> named = new TreeMap<>();
        direction.forEach((term, coef) ->
                named.put(term.toString(), coef.stripTrailingZeros().toPlainString()));
        StringBuilder out = new StringBuilder();
        named.forEach((term, coef) -> out.append(coef).append('*').append(term).append(' '));
        return out.toString().trim();
    }
}
