package souther.compiler.numeric;

/**
 * Which values of one position leave a residue some {@link AdditiveImage} reaches.
 *
 * <p>The answer to {@code { x | t - c·x ∈ I }}, which is what a search has to ask before it can
 * choose a value for a position rather than merely reject one. Asked as a membership — is this
 * residue in the image — the same arithmetic only rejects, and a position offering one candidate has
 * nothing for a rejection to leave.
 *
 * <p><b>A coset, and which kind depends on what the position is made of.</b> Over positions that
 * step it is an arithmetic progression and has a next value. Over positions whose values fill it is
 * dense: between any two of its values there is another, so there is no next value and the whole of
 * what a search can do with one is take the value it names. Held as one kind, a dense coset was
 * walked as though it stepped — and a walk is the thing it does not have.
 *
 * <p><b>Wider than the truth is safe, narrower is not</b>, the same as for the image itself. Where
 * {@code I ⊆ I'} the preimage under {@code I} is inside the preimage under {@code I'}, so an image
 * that answers wider than the set it stands for gives a preimage wider by the same token. A search
 * handed the wider one tries values that do not work out; handed a narrower one it would never try
 * the one that does.
 */
public sealed interface AffinePreimage {

    /** No value of the position leaves a residue the image reaches. A proof and not a search. */
    record None() implements AffinePreimage {}

    /**
     * Every {@code from + by·k} for a whole {@code k}.
     *
     * @param by always positive. One is every whole number, which is what a position under no
     *           congruence is left with
     */
    record Stepping(Rational from, Rational by) implements AffinePreimage {

        public Stepping {
            if (from == null || by == null || by.signum() <= 0) {
                throw new IllegalArgumentException("a progression steps by something positive: " + by);
            }
            from = representing(from, by);
        }
    }

    /**
     * Every {@code from + by·d} for a finite decimal {@code d}.
     *
     * <p>Dense and still not every value: {@code by} carries no factor of two or five, since those
     * are units among the finite decimals and a coset generated by one of them is the whole of them.
     * So {@code 1 + 3·D} holds {@code 1}, {@code 1.3} and {@code 0.7} and does not hold {@code 2}.
     *
     * @param by always positive. One is every finite decimal
     */
    record Filling(Rational from, Rational by) implements AffinePreimage {

        public Filling {
            if (from == null || by == null || by.signum() <= 0) {
                throw new IllegalArgumentException("a coset is generated by something positive: " + by);
            }
            from = representing(from, by);
        }
    }

    /**
     * The member of {@code from + by·k} between none and {@code by}, which every member of the coset
     * comes back as.
     *
     * <p>So that one set is one value. The arithmetic that finds these multiplies by an inverse and
     * the number that falls out depends on which inverse was taken — {@code 12 + 3·k} and
     * {@code 0 + 3·k} hold the same values, and left as they were written they would be two answers
     * with nothing to tell a reader they are one.
     *
     * <p>Sound for a coset over the finite decimals as well as over the whole numbers: what is
     * subtracted is a whole multiple of the generator, and a whole number is a finite decimal.
     */
    private static Rational representing(Rational from, Rational by) {
        return from.minus(by.times(Rational.of(from.dividedBy(by).floor())));
    }
}
